In [1]:
from pathlib import Path
import pandas as pd

# Locate project root and raw dataset folder
current = Path.cwd()

possible_paths = [
    current / "datasets" / "raw",
    current.parent / "datasets" / "raw",
    current / "data" / "raw",
    current.parent / "data" / "raw",
]

RAW_DIR = next((p for p in possible_paths if p.exists()), None)

if RAW_DIR is None:
    raise FileNotFoundError(
        "Could not find datasets/raw or data/raw. "
        "Open the notebook from inside the Jalachakra project."
    )

print("RAW DATA FOLDER:")
print(RAW_DIR)
print("\nFILES FOUND:\n")

files = sorted([f for f in RAW_DIR.iterdir() if f.is_file()])

for f in files:
    print(f.name)

print(f"\nTotal files: {len(files)}")

RAW DATA FOLDER:
c:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\raw

FILES FOUND:

Climate_Data.csv
Crop_Calender.csv
crop_dataset.csv
Crop_recommendation.csv
crop_water_data.csv
data_season.csv
Karnataka_Crop_Growth_Stage_Reference.xlsx
Rainfall_2016_districtwise.csv
Soil data.csv

Total files: 9

In [3]:
# STEP 1B — Load all raw datasets safely

datasets = {}

for file in files:
    try:
        extension = file.suffix.lower()

        if extension == ".csv":
            try:
                df = pd.read_csv(file, encoding="utf-8")
            except UnicodeDecodeError:
                print(f"UTF-8 failed for {file.name} → trying latin1")
                df = pd.read_csv(file, encoding="latin1")

        elif extension in [".xlsx", ".xls"]:
            df = pd.read_excel(file)

        else:
            continue

        datasets[file.name] = df

    except Exception as e:
        print(f"ERROR reading {file.name}: {e}")

print("\nSuccessfully loaded datasets:")
print("=" * 70)

for name, df in datasets.items():
    print(f"{name:45} {df.shape}")

print("\nTotal successfully loaded:", len(datasets))

UTF-8 failed for Crop_Calender.csv → trying latin1

Successfully loaded datasets:
======================================================================
Climate_Data.csv                              (2557, 11)
Crop_Calender.csv                             (25, 14)
crop_dataset.csv                              (5000, 4)
Crop_recommendation.csv                       (2200, 8)
crop_water_data.csv                           (10000, 14)
data_season.csv                               (3158, 12)
Karnataka_Crop_Growth_Stage_Reference.xlsx    (13, 7)
Rainfall_2016_districtwise.csv                (30, 7)
Soil data.csv                                 (875, 5)

Total successfully loaded: 9

In [4]:
# STEP 1C — Inspect columns and data types

for name, df in datasets.items():

    print("\n" + "=" * 80)
    print(f"DATASET: {name}")
    print("=" * 80)

    print(f"Rows    : {df.shape[0]}")
    print(f"Columns : {df.shape[1]}")

    print("\nColumns and data types:")

    column_info = pd.DataFrame({
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values,
        "missing": df.isna().sum().values,
        "unique_values": df.nunique(dropna=True).values
    })

    display(column_info)

================================================================================
DATASET: Climate_Data.csv
================================================================================
Rows    : 2557
Columns : 11

Columns and data types:

               column    dtype  missing  unique_values
0            datetime   object        0           2557
1                DATE    int64        0             31
2               MONTH    int64        0             12
3                YEAR    int64        0              7
4                 T2M  float64        0           1284
5             T2M_MIN  float64        0           1390
6             T2M_MAX  float64        0           1316
7                RH2M  float64        0           2125
8                WS2M  float64        0            572
9         PRECTOTCORR  float64        0            509
10  ALLSKY_SFC_SW_DWN  float64        0           1365

================================================================================
DATASET: Crop_Calender.csv
================================================================================
Rows    : 25
Columns : 14

Columns and data types:

                     column    dtype  missing  unique_values
0                      Crop   object        0              5
1                     Stage   object        0              5
2           Duration (days)    int64        0             14
3           Root Depth (cm)    int64        0             13
4     Kc (Crop Coefficient)   object        1             15
5              ETo (mm/day)   object        0             14
6              ETc (mm/day)  float64        0             19
7   Effective Rainfall (mm)   object        0              5
8                WHC (mm/m)    int64        0              1
9                Unnamed: 9  float64       25              0
10              Unnamed: 10  float64       25              0
11              Unnamed: 11  float64       25              0
12              Unnamed: 12  float64       25              0
13              Unnamed: 13  float64       25              0

================================================================================
DATASET: crop_dataset.csv
================================================================================
Rows    : 5000
Columns : 4

Columns and data types:

                  column    dtype  missing  unique_values
0          temperature_C  float64        0           1836
1             humidity_%  float64        0           3445
2            rainfall_mm  float64        0           3164
3  water_required_liters  float64        0           2232

================================================================================
DATASET: Crop_recommendation.csv
================================================================================
Rows    : 2200
Columns : 8

Columns and data types:

        column    dtype  missing  unique_values
0            N    int64        0            137
1            P    int64        0            117
2            K    int64        0             73
3  temperature  float64        0           2200
4     humidity  float64        0           2200
5           ph  float64        0           2200
6     rainfall  float64        0           2200
7        label   object        0             22

================================================================================
DATASET: crop_water_data.csv
================================================================================
Rows    : 10000
Columns : 14

Columns and data types:

                      column    dtype  missing  unique_values
0                  crop_type   object        0              7
1                  soil_type   object        0              5
2               growth_stage   object        0              5
3                temperature  float64        0            351
4                   humidity  float64        0            751
5                rainfall_mm  float64        0            501
6             wind_speed_kmh  float64        0            401
7            solar_radiation  float64        0            251
8              field_area_ha  float64        0           4289
9          irrigation_method   object        0              4
10             crop_age_days    int64        0            179
11         soil_moisture_pct  float64        0            501
12        evapotranspiration  float64        0           1400
13  water_requirement_liters  float64        0           8967

================================================================================
DATASET: data_season.csv
================================================================================
Rows    : 3158
Columns : 12

Columns and data types:

         column    dtype  missing  unique_values
0          Year    int64        0             16
1      Location   object        0             11
2          Area    int64        0            156
3      Rainfall  float64        0             21
4   Temperature  float64        0            106
5     Soil type   object       58             27
6    Irrigation   object        0              3
7        yeilds  float64        0            162
8      Humidity  float64        0             19
9         Crops   object        0             13
10        price    int64        0             24
11       Season   object        0              3

================================================================================
DATASET: Karnataka_Crop_Growth_Stage_Reference.xlsx
================================================================================
Rows    : 13
Columns : 7

Columns and data types:

                         column   dtype  missing  unique_values
0                          Crop  object        0              3
1                  Growth Stage  object        0              8
2             Stage Description  object        0             13
3  Indicative Duration / Timing  object        0             13
4                  Kc Reference  object        0             13
5                       Kc Type  object        0              6
6               Evidence Source  object        0              7

================================================================================
DATASET: Rainfall_2016_districtwise.csv
================================================================================
Rows    : 30
Columns : 7

Columns and data types:

                             column   dtype  missing  unique_values
0                             Sl.No  object        0             30
1     Districts                      object        0             30
2   RaingaugeStations_Working  R,Gs   int64        0             22
3     RaingaugeStations_Not Working   int64        0             12
4          Raingauge Stations_Total   int64        0             26
5  Annual Normal Rainfall_Rainydays   int64        0             22
6                   Normal Rainfall   int64        0             30

================================================================================
DATASET: Soil data.csv
================================================================================
Rows    : 875
Columns : 5

Columns and data types:

              column    dtype  missing  unique_values
0           District   object        0            101
1     Nitrogen Value  float64        0            499
2  Phosphorous value  float64        0            817
3    Potassium value  float64        0            837
4                 pH  float64        0            616

In [5]:
# STEP 1D — Missing values and duplicate analysis

missing_summary = []
duplicate_summary = []

for name, df in datasets.items():

    # -----------------------------
    # Missing-value information
    # -----------------------------
    total_missing = int(df.isna().sum().sum())

    missing_columns = int(
        (df.isna().sum() > 0).sum()
    )

    missing_summary.append({
        "dataset": name,
        "rows": len(df),
        "total_missing_cells": total_missing,
        "columns_with_missing_values": missing_columns
    })

    # -----------------------------
    # Duplicate information
    # -----------------------------
    duplicate_rows = int(df.duplicated().sum())

    duplicate_summary.append({
        "dataset": name,
        "rows": len(df),
        "duplicate_rows": duplicate_rows
    })


missing_df = pd.DataFrame(missing_summary)
duplicate_df = pd.DataFrame(duplicate_summary)

print("MISSING VALUE SUMMARY")
display(missing_df)

print("\nDUPLICATE SUMMARY")
display(duplicate_df)

MISSING VALUE SUMMARY

,dataset,rows,total_missing_cells,columns_with_missing_values
0,Climate_Data.csv,2557,0,0
1,Crop_Calender.csv,25,126,6
2,crop_dataset.csv,5000,0,0
3,Crop_recommendation.csv,2200,0,0
4,crop_water_data.csv,10000,0,0
5,data_season.csv,3158,58,1
6,Karnataka_Crop_Growth_Stage_Reference.xlsx,13,0,0
7,Rainfall_2016_districtwise.csv,30,0,0
8,Soil data.csv,875,0,0

DUPLICATE SUMMARY

                                      dataset   rows  duplicate_rows
0                            Climate_Data.csv   2557               0
1                           Crop_Calender.csv     25               0
2                            crop_dataset.csv   5000               0
3                     Crop_recommendation.csv   2200               0
4                         crop_water_data.csv  10000               0
5                             data_season.csv   3158               0
6  Karnataka_Crop_Growth_Stage_Reference.xlsx     13               0
7              Rainfall_2016_districtwise.csv     30               0
8                               Soil data.csv    875               0

In [6]:
# STEP 1D-B — Exact columns containing missing values

for name, df in datasets.items():

    missing = df.isna().sum()
    missing = missing[missing > 0]

    if len(missing) > 0:

        print("\n" + "=" * 70)
        print(name)
        print("=" * 70)

        for column, count in missing.items():

            percentage = (count / len(df)) * 100

            print(
                f"{column}: "
                f"{count} missing "
                f"({percentage:.2f}%)"
            )

======================================================================
Crop_Calender.csv
======================================================================
Kc (Crop Coefficient): 1 missing (4.00%)
Unnamed: 9: 25 missing (100.00%)
Unnamed: 10: 25 missing (100.00%)
Unnamed: 11: 25 missing (100.00%)
Unnamed: 12: 25 missing (100.00%)
Unnamed: 13: 25 missing (100.00%)

======================================================================
data_season.csv
======================================================================
Soil type: 58 missing (1.84%)

In [7]:
# STEP 1E — Date, location, crop and time-coverage analysis

DATE_KEYWORDS = [
    "date",
    "datetime",
    "time",
    "year",
    "month"
]

LOCATION_KEYWORDS = [
    "state",
    "district",
    "location",
    "region",
    "latitude",
    "longitude",
    "lat",
    "lon"
]

CROP_KEYWORDS = [
    "crop",
    "crops",
    "crop_type",
    "label"
]

for name, df in datasets.items():

    print("\n" + "=" * 90)
    print(f"DATASET: {name}")
    print("=" * 90)

    # ---------------------------
    # Date-like columns
    # ---------------------------
    date_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in DATE_KEYWORDS
        )
    ]

    if date_columns:
        print("\nDATE/TIME COLUMNS:")

        for col in date_columns:

            print(f"\nColumn: {col}")

            series = df[col].dropna()

            print("Data type:", df[col].dtype)
            print("Unique values:", series.nunique())

            # Try to interpret as dates
            converted = pd.to_datetime(
                series,
                errors="coerce"
            )

            valid_dates = converted.dropna()

            if len(valid_dates) > 0:
                print("Possible minimum date:", valid_dates.min())
                print("Possible maximum date:", valid_dates.max())
            else:
                print("Could not interpret this column as dates.")

    else:
        print("\nNo obvious date/time columns found.")

    # ---------------------------
    # Location columns
    # ---------------------------
    location_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in LOCATION_KEYWORDS
        )
    ]

    if location_columns:
        print("\nLOCATION COLUMNS:")

        for col in location_columns:

            print(f"\nColumn: {col}")
            print("Unique values:", df[col].nunique(dropna=True))

            print(
                df[col]
                .dropna()
                .astype(str)
                .value_counts()
                .head(15)
            )

    else:
        print("\nNo obvious location columns found.")

    # ---------------------------
    # Crop columns
    # ---------------------------
    crop_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in CROP_KEYWORDS
        )
    ]

    if crop_columns:
        print("\nCROP COLUMNS:")

        for col in crop_columns:

            print(f"\nColumn: {col}")
            print(
                "Unique crop values:",
                df[col].nunique(dropna=True)
            )

            print(
                df[col]
                .dropna()
                .astype(str)
                .value_counts()
                .head(20)
            )

    else:
        print("\nNo obvious crop columns found.")

==========================================================================================
DATASET: Climate_Data.csv
==========================================================================================

DATE/TIME COLUMNS:

Column: datetime
Data type: object
Unique values: 2557
Possible minimum date: 2018-01-01 00:00:00
Possible maximum date: 2024-12-31 00:00:00

Column: DATE
Data type: int64
Unique values: 31
Possible minimum date: 1970-01-01 00:00:00.000000001
Possible maximum date: 1970-01-01 00:00:00.000000031

Column: MONTH
Data type: int64
Unique values: 12
Possible minimum date: 1970-01-01 00:00:00.000000001
Possible maximum date: 1970-01-01 00:00:00.000000012

Column: YEAR
Data type: int64
Unique values: 7
Possible minimum date: 1970-01-01 00:00:00.000002018
Possible maximum date: 1970-01-01 00:00:00.000002024

No obvious location columns found.

No obvious crop columns found.

==========================================================================================
DATASET: Crop_Calender.csv
==========================================================================================

No obvious date/time columns found.

No obvious location columns found.

CROP COLUMNS:

Column: Crop
Unique crop values: 5
Crop
Groundnut    5
Cotton       5
Wheat        5
Cumin        5
Chickpea     5
Name: count, dtype: int64

Column: Kc (Crop Coefficient)
Unique crop values: 15
Kc (Crop Coefficient)
       4
0.75    2
0.45    2
1.15    2
0.4     2
0.7     2
0.3     2
0.85    1
0.8     1
0.97    1
1.2     1
0.5     1
0.42    1
1.05    1
0.55    1
Name: count, dtype: int64

==========================================================================================
DATASET: crop_dataset.csv
==========================================================================================

No obvious date/time columns found.

No obvious location columns found.

No obvious crop columns found.

==========================================================================================
DATASET: Crop_recommendation.csv
==========================================================================================

No obvious date/time columns found.

No obvious location columns found.

CROP COLUMNS:

Column: label
Unique crop values: 22
label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
Name: count, dtype: int64

==========================================================================================
DATASET: crop_water_data.csv
==========================================================================================

No obvious date/time columns found.

No obvious location columns found.

CROP COLUMNS:

Column: crop_type
Unique crop values: 7
crop_type
Sugarcane    1464
Cotton       1439
Potato       1429
Wheat        1428
Soybean      1426
Rice         1423
Maize        1391
Name: count, dtype: int64

Column: crop_age_days
Unique crop values: 179
crop_age_days
143    77
84     77
21     76
82     74
58     72
27     72
11     72
53     70
33     70
29     69
142    68
72     68
106    67
111    67
173    66
148    66
37     66
23     66
90     66
40     66
Name: count, dtype: int64

==========================================================================================
DATASET: data_season.csv
==========================================================================================

DATE/TIME COLUMNS:

Column: Year
Data type: int64
Unique values: 16
Possible minimum date: 1970-01-01 00:00:00.000002004
Possible maximum date: 1970-01-01 00:00:00.000002019

LOCATION COLUMNS:

Column: Location
Unique values: 11
Location
Hassan           798
Gulbarga         504
Mangalore        342
Chikmangaluru    340
Madikeri         240
Raichur          231
Kasaragodu       231
Mysuru           222
Kodagu           192
Davangere         42
Bangalore         16
Name: count, dtype: int64

CROP COLUMNS:

Column: Crops
Unique crop values: 13
Crops
Coconut      1458
Ginger        281
Coffee        150
Arecanut      150
Cardamum      150
Blackgram     150
Paddy         150
Tea           150
Pepper        146
Cashew        146
Groundnut     146
Cocoa          60
Cotton         21
Name: count, dtype: int64

==========================================================================================
DATASET: Karnataka_Crop_Growth_Stage_Reference.xlsx
==========================================================================================

No obvious date/time columns found.

No obvious location columns found.

CROP COLUMNS:

Column: Crop
Unique crop values: 3
Crop
Paddy (Rice)            5
Finger Millet (Ragi)    4
Maize                   4
Name: count, dtype: int64

==========================================================================================
DATASET: Rainfall_2016_districtwise.csv
==========================================================================================

No obvious date/time columns found.

LOCATION COLUMNS:

Column: Districts
Unique values: 30
Districts
BENGALURU(R)        1
RAMANAGARA          1
CHITRADURGA         1
DAVANAGERE          1
KOLAR               1
CHIKKABALLAPURA     1
SHIVAMOGGA          1
TUMAKURU            1
CHIKKAMAGALURU      1
DAKSHINA KANNADA    1
UDUPI               1
HASSAN              1
KODAGU              1
MANDYA              1
MYSURU              1
Name: count, dtype: int64

No obvious crop columns found.

==========================================================================================
DATASET: Soil data.csv
==========================================================================================

No obvious date/time columns found.

LOCATION COLUMNS:

Column: District
Unique values: 101
District
Salem             20
Tiruvannamalai    18
Namakkal          15
Belagavi          15
Thiruvallur       14
Cuddalore         14
Erode             14
Bharuch           14
Dindigul          14
Tiruchippalli     14
Banas Kantha      14
Thanjavur         14
Villupuram        13
Madurai           13
Pudukkottai       13
Name: count, dtype: int64

No obvious crop columns found.

In [8]:
# STEP 1E — Compact dataset coverage summary
# This analyzes ALL datasets without producing huge output.

summary_rows = []

for name, df in datasets.items():

    # ---------- Date detection ----------
    date_columns = []

    for col in df.columns:
        col_lower = str(col).lower()

        if any(word in col_lower for word in [
            "date", "datetime", "time"
        ]):
            date_columns.append(col)

    date_start = None
    date_end = None

    for col in date_columns:

        converted = pd.to_datetime(
            df[col],
            errors="coerce"
        )

        valid = converted.dropna()

        # Ignore columns that are not really date-like
        if len(valid) >= max(3, int(len(df) * 0.5)):

            current_start = valid.min()
            current_end = valid.max()

            if date_start is None or current_start < date_start:
                date_start = current_start

            if date_end is None or current_end > date_end:
                date_end = current_end

    # ---------- Crop detection ----------
    crop_columns = []

    for col in df.columns:
        col_lower = str(col).lower()

        if any(word in col_lower for word in [
            "crop", "crops", "crop_type", "label"
        ]):
            crop_columns.append(col)

    crop_count = None

    if crop_columns:
        counts = []

        for col in crop_columns:
            counts.append(df[col].nunique(dropna=True))

        crop_count = max(counts)

    # ---------- Location detection ----------
    location_columns = []

    for col in df.columns:
        col_lower = str(col).lower()

        if any(word in col_lower for word in [
            "state",
            "district",
            "location",
            "region",
            "latitude",
            "longitude",
            "lat",
            "lon"
        ]):
            location_columns.append(col)

    location_count = None

    if location_columns:
        counts = []

        for col in location_columns:
            counts.append(df[col].nunique(dropna=True))

        location_count = max(counts)

    # ---------- Important CWR variables ----------
    cwr_keywords = [
        "water",
        "requirement",
        "evapotranspiration",
        "et0",
        "etc",
        "kc",
        "rainfall",
        "precip",
        "temperature",
        "humidity",
        "wind",
        "solar",
        "moisture",
        "irrigation",
        "growth",
        "stage",
        "root",
        "whc"
    ]

    cwr_columns = []

    for col in df.columns:

        normalized = str(col).lower().replace("_", " ")

        if any(word in normalized for word in cwr_keywords):
            cwr_columns.append(str(col))

    summary_rows.append({
        "dataset": name,
        "rows": len(df),
        "columns": len(df.columns),
        "date_columns": ", ".join(map(str, date_columns))
            if date_columns else "None",
        "date_start": date_start,
        "date_end": date_end,
        "crop_columns": ", ".join(map(str, crop_columns))
            if crop_columns else "None",
        "crop_count": crop_count,
        "location_columns": ", ".join(map(str, location_columns))
            if location_columns else "None",
        "location_count": location_count,
        "cwr_related_columns": ", ".join(cwr_columns)
            if cwr_columns else "None"
    })


coverage_df = pd.DataFrame(summary_rows)

coverage_df

,dataset,rows,columns,date_columns,date_start,date_end,crop_columns,crop_count,location_columns,location_count,cwr_related_columns
0,Climate_Data.csv,2557,11,"datetime, DATE",1970-01-01 00:00:00.000000001,2024-12-31,None,NaN,None,NaN,None
1,Crop_Calender.csv,25,14,None,NaT,NaT,"Crop, Kc (Crop Coefficient)",15.0,None,NaN,"Stage, Root Depth (cm), Kc (Crop Coefficient),..."
2,crop_dataset.csv,5000,4,None,NaT,NaT,None,NaN,None,NaN,"temperature_C, humidity_%, rainfall_mm, water_..."
3,Crop_recommendation.csv,2200,8,None,NaT,NaT,label,22.0,None,NaN,"temperature, humidity, rainfall"
4,crop_water_data.csv,10000,14,None,NaT,NaT,"crop_type, crop_age_days",179.0,None,NaN,"growth_stage, temperature, humidity, rainfall_..."
5,data_season.csv,3158,12,None,NaT,NaT,Crops,13.0,Location,11.0,"Rainfall, Temperature, Irrigation, Humidity"
6,Karnataka_Crop_Growth_Stage_Reference.xlsx,13,7,None,NaT,NaT,Crop,3.0,None,NaN,"Growth Stage, Stage Description, Kc Reference,..."
7,Rainfall_2016_districtwise.csv,30,7,None,NaT,NaT,None,NaN,Districts,30.0,"Annual Normal Rainfall_Rainydays, Normal Rainfall"
8,Soil data.csv,875,5,None,NaT,NaT,None,NaN,District,101.0,None

In [9]:
# STEP 1E-C — Correct date and crop interpretation

corrected_rows = []

for name, df in datasets.items():

    # -----------------------------
    # REAL DATE COLUMNS
    # -----------------------------
    real_date_columns = []

    for col in df.columns:
        col_lower = str(col).lower()

        # Only treat these as true date fields
        if col_lower in ["date", "datetime", "timestamp"]:
            real_date_columns.append(col)

    # Ignore integer DATE/MONTH helper fields unless they
    # can actually be interpreted as calendar dates.
    date_start = pd.NaT
    date_end = pd.NaT
    selected_date_column = "None"

    for col in real_date_columns:

        converted = pd.to_datetime(
            df[col],
            errors="coerce"
        )

        valid = converted.dropna()

        if len(valid) >= max(3, int(len(df) * 0.5)):

            selected_date_column = col
            date_start = valid.min()
            date_end = valid.max()
            break

    # -----------------------------
    # REAL CROP COLUMNS
    # -----------------------------
    real_crop_columns = []

    for col in df.columns:

        col_lower = str(col).lower().strip()

        if (
            col_lower in ["crop", "crop_type", "crops", "label"]
            or col_lower.startswith("crop ")
            or col_lower.endswith(" crop")
        ):
            real_crop_columns.append(col)

    crop_count = None

    if real_crop_columns:

        crop_counts = [
            df[col].nunique(dropna=True)
            for col in real_crop_columns
        ]

        crop_count = max(crop_counts)

    corrected_rows.append({
        "dataset": name,
        "rows": len(df),
        "real_date_column": selected_date_column,
        "date_start": date_start,
        "date_end": date_end,
        "crop_columns": ", ".join(
            map(str, real_crop_columns)
        ) if real_crop_columns else "None",
        "crop_count": crop_count
    })


corrected_coverage_df = pd.DataFrame(corrected_rows)

display(corrected_coverage_df)

,dataset,rows,real_date_column,date_start,date_end,crop_columns,crop_count
0,Climate_Data.csv,2557,datetime,2018-01-01,2024-12-31,None,NaN
1,Crop_Calender.csv,25,None,NaT,NaT,Crop,5.0
2,crop_dataset.csv,5000,None,NaT,NaT,None,NaN
3,Crop_recommendation.csv,2200,None,NaT,NaT,label,22.0
4,crop_water_data.csv,10000,None,NaT,NaT,crop_type,7.0
5,data_season.csv,3158,None,NaT,NaT,Crops,13.0
6,Karnataka_Crop_Growth_Stage_Reference.xlsx,13,None,NaT,NaT,Crop,3.0
7,Rainfall_2016_districtwise.csv,30,None,NaT,NaT,None,NaN
8,Soil data.csv,875,None,NaT,NaT,None,NaN

In [10]:
# STEP 1F — Preliminary scientific role classification

role_rows = []

for name, df in datasets.items():

    columns = [
        str(c).lower().strip()
        for c in df.columns
    ]

    text = " ".join(columns)

    has_weather = any(
        x in text
        for x in [
            "temperature", "temp", "humidity",
            "wind", "solar", "radiation",
            "t2m", "rh2m", "ws2m"
        ]
    )

    has_rainfall = any(
        x in text
        for x in ["rainfall", "precipitation", "precip"]
    )

    has_soil = any(
        x in text
        for x in [
            "soil", "nitrogen", "phosphorous",
            "phosphorus", "potassium", "ph", "moisture"
        ]
    )

    has_crop = any(
        x in columns
        for x in ["crop", "crop_type", "crops", "label"]
    )

    has_growth_stage = any(
        x in text
        for x in [
            "growth_stage", "growth stage",
            "stage", "duration"
        ]
    )

    has_water_target = any(
        x in text
        for x in [
            "water_requirement",
            "water requirement",
            "water_required",
            "water required",
            "water_requirement_liters",
            "evapotranspiration",
            "et0", "etc", "kc"
        ]
    )

    has_irrigation = "irrigation" in text

    has_market = any(
        x in text
        for x in ["price", "market", "commodity", "arrival"]
    )

    if (
        "karnataka_crop_growth_stage_reference" in name.lower()
        or "crop_calender" in name.lower()
    ):
        role = "AGRONOMIC_REFERENCE"

    elif has_market:
        role = "MARKET"

    elif "crop_recommendation" in name.lower():
        role = "CROP_RECOMMENDATION"

    elif has_weather and has_rainfall:
        role = "WEATHER_RAINFALL"

    elif has_soil and not has_weather:
        role = "SOIL_SUPPORTING"

    elif has_water_target and has_crop and has_growth_stage:
        role = "CWR_CANDIDATE"

    elif "data_season" in name.lower():
        role = "SUPPORTING_REVIEW_REQUIRED"

    elif "crop_dataset" in name.lower():
        role = "SUPPORTING_REVIEW_REQUIRED"

    else:
        role = "REVIEW_REQUIRED"

    role_rows.append({
        "dataset": name,
        "preliminary_role": role,
        "has_crop": has_crop,
        "has_soil": has_soil,
        "has_weather": has_weather,
        "has_rainfall": has_rainfall,
        "has_growth_stage": has_growth_stage,
        "has_water_target": has_water_target,
        "has_irrigation": has_irrigation,
        "has_market": has_market
    })

role_df = pd.DataFrame(role_rows)

display(role_df)

,dataset,preliminary_role,has_crop,has_soil,has_weather,has_rainfall,has_growth_stage,has_water_target,has_irrigation,has_market
0,Climate_Data.csv,REVIEW_REQUIRED,False,False,True,False,False,False,False,False
1,Crop_Calender.csv,AGRONOMIC_REFERENCE,True,False,False,True,True,True,False,False
2,crop_dataset.csv,WEATHER_RAINFALL,False,False,True,True,False,True,False,False
3,Crop_recommendation.csv,CROP_RECOMMENDATION,True,True,True,True,False,False,False,False
4,crop_water_data.csv,WEATHER_RAINFALL,True,True,True,True,True,True,True,False
5,data_season.csv,MARKET,True,True,True,True,False,False,True,True
6,Karnataka_Crop_Growth_Stage_Reference.xlsx,AGRONOMIC_REFERENCE,True,False,False,False,True,True,False,False
7,Rainfall_2016_districtwise.csv,REVIEW_REQUIRED,False,False,False,True,False,False,False,False
8,Soil data.csv,SOIL_SUPPORTING,False,True,False,False,False,False,False,False

In [ ]:
# STEP 2A — Investigate possible CWR / water-target datasets
import numpy as np
candidate_files = [
    "crop_water_data.csv",
    "crop_dataset.csv",
    "Crop_Calender.csv",
    "data_season.csv"
]

for name in candidate_files:

    if name not in datasets:
        print(f"\nNOT FOUND: {name}")
        continue

    df = datasets[name]

    print("\n" + "=" * 100)
    print(f"DATASET: {name}")
    print("=" * 100)

    print("\nSHAPE:")
    print(df.shape)

    print("\nCOLUMNS:")
    print(list(df.columns))

    print("\nFIRST 5 ROWS:")
    display(df.head())

    print("\nDATA TYPES:")
    display(
        pd.DataFrame({
            "column": df.columns,
            "dtype": df.dtypes.astype(str).values
        })
    )

    print("\nNUMERICAL SUMMARY:")
    numeric = df.select_dtypes(include=np.number)

    if not numeric.empty:
        display(numeric.describe().T)
    else:
        print("No numeric columns.")

    print("\nUNIQUE VALUES FOR IMPORTANT COLUMNS:")

    important_keywords = [
        "crop",
        "soil",
        "stage",
        "water",
        "require",
        "evapo",
        "rain",
        "temperature",
        "humidity",
        "wind",
        "solar",
        "irrigation",
        "kc",
        "et0",
        "etc"
    ]

    important_columns = []

    for column in df.columns:
        column_text = str(column).lower()

        if any(
            keyword in column_text
            for keyword in important_keywords
        ):
            important_columns.append(column)

    for column in important_columns:

        print(f"\n--- {column} ---")

        values = (
            df[column]
            .dropna()
            .astype(str)
            .value_counts()
            .head(15)
        )

        display(values)

====================================================================================================
DATASET: crop_water_data.csv
====================================================================================================

SHAPE:
(10000, 14)

COLUMNS:
['crop_type', 'soil_type', 'growth_stage', 'temperature', 'humidity', 'rainfall_mm', 'wind_speed_kmh', 'solar_radiation', 'field_area_ha', 'irrigation_method', 'crop_age_days', 'soil_moisture_pct', 'evapotranspiration', 'water_requirement_liters']

FIRST 5 ROWS:

,crop_type,soil_type,growth_stage,temperature,humidity,rainfall_mm,wind_speed_kmh,solar_radiation,field_area_ha,irrigation_method,crop_age_days,soil_moisture_pct,evapotranspiration,water_requirement_liters
0,Potato,Loamy,Fruiting,23.7,91.1,6.1,24.4,18.8,29.55,Flood,42,35.1,13.92,3647.38
1,Cotton,Sandy,Maturity,28.4,40.4,42.0,35.1,22.7,27.96,Sprinkler,163,41.9,7.77,677.58
2,Sugarcane,Loamy,Maturity,22.4,88.4,17.0,28.5,10.0,38.77,Sprinkler,139,15.3,7.54,2390.46
3,Potato,Loamy,Germination,30.9,75.3,21.6,30.8,23.6,47.78,Flood,28,17.8,6.89,946.19
4,Maize,Clay,Germination,44.2,31.6,47.4,26.7,14.0,15.73,Sprinkler,172,21.6,10.13,444.83

DATA TYPES:

                      column    dtype
0                  crop_type   object
1                  soil_type   object
2               growth_stage   object
3                temperature  float64
4                   humidity  float64
5                rainfall_mm  float64
6             wind_speed_kmh  float64
7            solar_radiation  float64
8              field_area_ha  float64
9          irrigation_method   object
10             crop_age_days    int64
11         soil_moisture_pct  float64
12        evapotranspiration  float64
13  water_requirement_liters  float64

NUMERICAL SUMMARY:

NameError: name 'np' is not defined

In [12]:
# STEP 2A — CWR candidate summary
import numpy as np
candidate_files = [
    "crop_water_data.csv",
    "crop_dataset.csv",
    "Crop_Calender.csv",
    "data_season.csv"
]

for name in candidate_files:

    if name not in datasets:
        print(f"NOT FOUND: {name}")
        continue

    df = datasets[name]

    print("\n" + "=" * 80)
    print(f"DATASET: {name}")
    print("=" * 80)
    print("Shape:", df.shape)

    print("\nColumns:")
    print(list(df.columns))

    print("\nFirst 3 rows:")
    display(df.head(3))

    print("\nNumeric columns:")
    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
    print(numeric_cols)

    if numeric_cols:
        print("\nNumeric summary:")
        display(
            df[numeric_cols].describe().T
        )

================================================================================
DATASET: crop_water_data.csv
================================================================================
Shape: (10000, 14)

Columns:
['crop_type', 'soil_type', 'growth_stage', 'temperature', 'humidity', 'rainfall_mm', 'wind_speed_kmh', 'solar_radiation', 'field_area_ha', 'irrigation_method', 'crop_age_days', 'soil_moisture_pct', 'evapotranspiration', 'water_requirement_liters']

First 3 rows:

,crop_type,soil_type,growth_stage,temperature,humidity,rainfall_mm,wind_speed_kmh,solar_radiation,field_area_ha,irrigation_method,crop_age_days,soil_moisture_pct,evapotranspiration,water_requirement_liters
0,Potato,Loamy,Fruiting,23.7,91.1,6.1,24.4,18.8,29.55,Flood,42,35.1,13.92,3647.38
1,Cotton,Sandy,Maturity,28.4,40.4,42.0,35.1,22.7,27.96,Sprinkler,163,41.9,7.77,677.58
2,Sugarcane,Loamy,Maturity,22.4,88.4,17.0,28.5,10.0,38.77,Sprinkler,139,15.3,7.54,2390.46

Numeric columns:
['temperature', 'humidity', 'rainfall_mm', 'wind_speed_kmh', 'solar_radiation', 'field_area_ha', 'crop_age_days', 'soil_moisture_pct', 'evapotranspiration', 'water_requirement_liters']

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
temperature,10000.0,27.482020,10.050012,10.00,18.8000,27.500,36.10,45.00
humidity,10000.0,57.364880,21.631928,20.00,38.6000,57.450,76.00,95.00
rainfall_mm,10000.0,24.962770,14.466699,0.00,12.3000,25.000,37.50,50.00
wind_speed_kmh,10000.0,20.013850,11.478478,0.00,10.3000,19.900,30.00,40.00
solar_radiation,10000.0,17.531440,7.195423,5.00,11.3000,17.600,23.80,30.00
field_area_ha,10000.0,25.323430,14.218665,0.51,12.9675,25.550,37.66,49.99
crop_age_days,10000.0,89.143400,51.418085,1.00,44.0000,89.000,134.00,179.00
soil_moisture_pct,10000.0,34.810230,14.428256,10.00,22.2000,34.900,47.20,60.00
evapotranspiration,10000.0,8.027086,4.049261,1.00,4.4900,8.010,11.59,15.00
water_requirement_liters,10000.0,1368.866571,1363.473560,1.00,321.7300,902.645,2002.78,5000.00

================================================================================
DATASET: crop_dataset.csv
================================================================================
Shape: (5000, 4)

Columns:
['temperature_C', 'humidity_%', 'rainfall_mm', 'water_required_liters']

First 3 rows:

   temperature_C  humidity_%  rainfall_mm  water_required_liters
0          27.49       53.62        18.68                  21.39
1          39.01       58.41        16.65                  26.19
2          34.64       81.27         8.81                  29.71

Numeric columns:
['temperature_C', 'humidity_%', 'rainfall_mm', 'water_required_liters']

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
temperature_C,5000.0,29.936576,5.792694,20.00,24.8775,30.000,34.9600,39.99
humidity_%,5000.0,59.489212,17.137032,30.00,44.8275,59.155,74.0000,89.97
rainfall_mm,5000.0,25.068750,14.538533,0.01,12.3600,24.810,38.0325,49.99
water_required_liters,5000.0,19.373774,6.493081,1.62,14.8375,19.340,24.0600,41.14

================================================================================
DATASET: Crop_Calender.csv
================================================================================
Shape: (25, 14)

Columns:
['Crop', 'Stage', 'Duration (days)', 'Root Depth (cm)', 'Kc (Crop Coefficient)', 'ETo (mm/day)', 'ETc (mm/day)', 'Effective Rainfall (mm)', 'WHC (mm/m)', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

First 3 rows:

,Crop,Stage,Duration (days),Root Depth (cm),Kc (Crop Coefficient),ETo (mm/day),ETc (mm/day),Effective Rainfall (mm),WHC (mm/m),Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Groundnut,Initial,25,30,0.45,5,2.250,,125,NaN,NaN,NaN,NaN,NaN
1,Groundnut,Development,35,60,0.75,5.5,4.125,,125,NaN,NaN,NaN,NaN,NaN
2,Groundnut,Mid-season,45,120,0.97,6,5.820,,125,NaN,NaN,NaN,NaN,NaN

Numeric columns:
['Duration (days)', 'Root Depth (cm)', 'ETc (mm/day)', 'WHC (mm/m)', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
Duration (days),25.0,51.200000,43.905201,10.0,25.00,35.00,55.000,195.0
Root Depth (cm),25.0,81.800000,40.022910,20.0,50.00,80.00,120.000,150.0
ETc (mm/day),25.0,2.227816,1.891341,0.0,0.75,2.25,3.675,6.9
WHC (mm/m),25.0,125.000000,0.000000,125.0,125.00,125.00,125.000,125.0
Unnamed: 9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 10,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 11,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 12,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 13,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
DATASET: data_season.csv
================================================================================
Shape: (3158, 12)

Columns:
['Year', 'Location', 'Area', 'Rainfall', 'Temperature', 'Soil type', 'Irrigation', 'yeilds', 'Humidity', 'Crops', 'price', 'Season']

First 3 rows:

,Year,Location,Area,Rainfall,Temperature,Soil type,Irrigation,yeilds,Humidity,Crops,price,Season
0,2004,Mangalore,1279,2903.1,27.0,Alluvial,Drip,2570.0,57.0,Coconut,200000,Kharif
1,2004,Mangalore,13283,2903.1,27.0,Alluvial,Drip,27170.0,57.5,Coconut,4847,Kharif
2,2004,Mangalore,52119,2903.1,27.0,Alluvial,Drip,114744.0,57.0,Coconut,51239,Kharif

Numeric columns:
['Year', 'Area', 'Rainfall', 'Temperature', 'yeilds', 'Humidity', 'price']

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
Year,3158.0,2009.929702,5.100895,2004.0,2004.0,2010.0,2015.0,2019.0
Area,3158.0,9329.913553,15180.465396,1.0,153.0,2127.0,10910.0,52119.0
Rainfall,3158.0,2813.126662,1163.829953,233.0,2903.1,3296.0,3550.0,3729.8
Temperature,3158.0,65.893699,60.814037,26.8,27.0,38.0,43.0,222.0
yeilds,3158.0,23258.976916,58228.985033,2.0,393.0,2783.0,6589.0,623687.0
Humidity,3158.0,55.582331,2.469773,50.0,54.0,56.0,57.0,60.0
price,3158.0,86271.279291,94123.160706,637.0,2644.0,45186.0,203317.0,249978.0

In [13]:
# STEP 2C — Physical consistency check for water_requirement_liters

df = datasets["crop_water_data.csv"].copy()

# Expected water volume:
# 1 mm of water over 1 hectare = 10,000 litres
df["expected_volume_from_ET_mm"] = (
    df["evapotranspiration"]
    * df["field_area_ha"]
    * 10000
)

# Ratio between supplied target and ET-based volume
df["target_to_physics_ratio"] = (
    df["water_requirement_liters"]
    / df["expected_volume_from_ET_mm"].replace(0, np.nan)
)

print("PHYSICAL CONSISTENCY CHECK")
print("=" * 70)

print("\nTarget statistics:")
display(
    df["water_requirement_liters"].describe()
)

print("\nEvapotranspiration statistics:")
display(
    df["evapotranspiration"].describe()
)

print("\nField area statistics:")
display(
    df["field_area_ha"].describe()
)

print("\nTarget / physics ratio:")
display(
    df["target_to_physics_ratio"].describe()
)

print("\nCorrelation with target:")

correlation_columns = [
    "evapotranspiration",
    "field_area_ha",
    "crop_age_days",
    "soil_moisture_pct",
    "temperature",
    "humidity",
    "rainfall_mm",
    "water_requirement_liters"
]

display(
    df[correlation_columns].corr()["water_requirement_liters"]
    .sort_values(ascending=False)
)

PHYSICAL CONSISTENCY CHECK
======================================================================

Target statistics:

count    10000.000000
mean      1368.866571
std       1363.473560
min          1.000000
25%        321.730000
50%        902.645000
75%       2002.780000
max       5000.000000
Name: water_requirement_liters, dtype: float64

Evapotranspiration statistics:

count    10000.000000
mean         8.027086
std          4.049261
min          1.000000
25%          4.490000
50%          8.010000
75%         11.590000
max         15.000000
Name: evapotranspiration, dtype: float64

Field area statistics:

count    10000.000000
mean        25.323430
std         14.218665
min          0.510000
25%         12.967500
50%         25.550000
75%         37.660000
max         49.990000
Name: field_area_ha, dtype: float64

Target / physics ratio:

count    1.000000e+04
mean     6.550915e-04
std      4.160643e-04
min      3.253175e-07
25%      3.585497e-04
50%      5.944745e-04
75%      8.874168e-04
max      2.659888e-03
Name: target_to_physics_ratio, dtype: float64

Correlation with target:

water_requirement_liters    1.000000
field_area_ha               0.527394
evapotranspiration          0.524619
humidity                    0.011004
temperature                 0.003755
crop_age_days              -0.000594
soil_moisture_pct          -0.009407
rainfall_mm                -0.106373
Name: water_requirement_liters, dtype: float64

In [14]:
# STEP 2D — Compare supplied water requirement with
# physics-based volume for selected records

comparison = df[
    [
        "crop_type",
        "growth_stage",
        "field_area_ha",
        "evapotranspiration",
        "water_requirement_liters",
        "expected_volume_from_ET_mm",
        "target_to_physics_ratio"
    ]
].head(20).copy()

display(comparison)

,crop_type,growth_stage,field_area_ha,evapotranspiration,water_requirement_liters,expected_volume_from_ET_mm,target_to_physics_ratio
0,Potato,Fruiting,29.55,13.92,3647.38,4113360.0,0.000887
1,Cotton,Maturity,27.96,7.77,677.58,2172492.0,0.000312
2,Sugarcane,Maturity,38.77,7.54,2390.46,2923258.0,0.000818
3,Potato,Germination,47.78,6.89,946.19,3292042.0,0.000287
4,Maize,Germination,15.73,10.13,444.83,1593449.0,0.000279
5,Sugarcane,Maturity,36.23,5.52,1853.60,1999896.0,0.000927
6,Sugarcane,Flowering,22.01,10.36,3958.73,2280236.0,0.001736
7,Potato,Flowering,39.30,10.85,1704.82,4264050.0,0.000400
8,Wheat,Germination,8.63,3.96,176.06,341748.0,0.000515
9,Maize,Vegetative,25.29,9.33,901.43,2359557.0,0.000382
10,Potato,Maturity,4.32,11.18,151.68,482976.0,0.000314
11,Maize,Fruiting,28.28,14.46,5000.00,4089288.0,0.001223
12,Maize,Flowering,8.86,14.14,832.65,1252804.0,0.000665
13,Sugarcane,Vegetative,48.02,3.87,2319.10,1858374.0,0.001248
14,Cotton,Flowering,27.94,9.08,2168.62,2536952.0,0.000855
15,Maize,Vegetative,26.70,7.57,1195.07,2021190.0,0.000591
16,Soybean,Maturity,48.63,5.89,1341.47,2864307.0,0.000468
17,Sugarcane,Maturity,25.17,5.79,984.23,1457343.0,0.000675
18,Wheat,Maturity,34.00,14.59,2092.42,4960600.0,0.000422
19,Cotton,Germination,2.81,1.51,9.60,42431.0,0.000226

In [15]:
# STEP 2E — Check how many records have physically plausible ratios

ratio = df["target_to_physics_ratio"]

print("Ratio < 0.01 :", (ratio < 0.01).sum())
print("0.01–0.1     :", ((ratio >= 0.01) & (ratio < 0.1)).sum())
print("0.1–1        :", ((ratio >= 0.1) & (ratio <= 1)).sum())
print("1–10         :", ((ratio > 1) & (ratio <= 10)).sum())
print("> 10         :", (ratio > 10).sum())

print("\nTotal records:", len(df))

Ratio < 0.01 : 10000
0.01–0.1     : 0
0.1–1        : 0
1–10         : 0
> 10         : 0

Total records: 10000

In [16]:
# STEP 3A — Climate dataset provenance and geographic coverage

df = datasets["Climate_Data.csv"]

print("=" * 80)
print("CLIMATE DATASET PROVENANCE CHECK")
print("=" * 80)

print("\nColumns:")
print(list(df.columns))

print("\nShape:")
print(df.shape)

# -----------------------------
# Check possible location fields
# -----------------------------
geo_keywords = [
    "state",
    "district",
    "location",
    "region",
    "latitude",
    "longitude",
    "lat",
    "lon",
    "station",
    "site"
]

geo_columns = [
    col for col in df.columns
    if any(
        key in str(col).lower()
        for key in geo_keywords
    )
]

print("\nPossible geographic columns:")

if geo_columns:
    for col in geo_columns:
        print(f"\n--- {col} ---")
        print("Unique values:", df[col].nunique(dropna=True))
        display(
            df[col]
            .dropna()
            .astype(str)
            .value_counts()
            .head(20)
        )
else:
    print("No obvious geographic columns found.")

# -----------------------------
# Check the actual datetime
# -----------------------------
if "datetime" in df.columns:

    dates = pd.to_datetime(
        df["datetime"],
        errors="coerce"
    )

    print("\nDATETIME INFORMATION")
    print("-" * 50)
    print("Minimum:", dates.min())
    print("Maximum:", dates.max())
    print("Valid:", dates.notna().sum())
    print("Unique dates:", dates.nunique())

# -----------------------------
# Display representative rows
# -----------------------------
print("\nFIRST 5 ROWS")
display(df.head())

print("\nLAST 5 ROWS")
display(df.tail())

================================================================================
CLIMATE DATASET PROVENANCE CHECK
================================================================================

Columns:
['datetime', 'DATE', 'MONTH', 'YEAR', 'T2M', 'T2M_MIN', 'T2M_MAX', 'RH2M', 'WS2M', 'PRECTOTCORR', 'ALLSKY_SFC_SW_DWN']

Shape:
(2557, 11)

Possible geographic columns:
No obvious geographic columns found.

DATETIME INFORMATION
--------------------------------------------------
Minimum: 2018-01-01 00:00:00
Maximum: 2024-12-31 00:00:00
Valid: 2557
Unique dates: 2557

FIRST 5 ROWS

,datetime,DATE,MONTH,YEAR,T2M,T2M_MIN,T2M_MAX,RH2M,WS2M,PRECTOTCORR,ALLSKY_SFC_SW_DWN
0,1/1/2018,1,1,2018,17.92,9.96,27.95,24.23,2.43,0.0,16.95
1,1/2/2018,2,1,2018,18.24,9.34,28.73,28.32,2.19,0.0,15.63
2,1/3/2018,3,1,2018,19.31,11.28,29.70,28.21,1.81,0.0,15.35
3,1/4/2018,4,1,2018,19.20,12.75,28.96,33.37,1.66,0.0,15.68
4,1/5/2018,5,1,2018,19.91,13.21,28.70,62.90,1.45,0.0,16.13

LAST 5 ROWS

,datetime,DATE,MONTH,YEAR,T2M,T2M_MIN,T2M_MAX,RH2M,WS2M,PRECTOTCORR,ALLSKY_SFC_SW_DWN
2552,12/27/2024,27,12,2024,18.32,12.85,26.13,57.37,2.82,0.0,12.12
2553,12/28/2024,28,12,2024,16.02,8.75,25.09,47.81,2.94,0.0,14.85
2554,12/29/2024,29,12,2024,16.68,8.75,27.00,48.06,2.73,0.0,15.23
2555,12/30/2024,30,12,2024,17.46,9.23,27.97,47.30,1.98,0.0,15.42
2556,12/31/2024,31,12,2024,18.65,10.64,29.24,42.59,1.69,0.0,15.73

In [17]:
# STEP 3B — Search project files for Climate_Data provenance

from pathlib import Path

search_terms = [
    "Climate_Data",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN",
    "2018-01-01",
    "2024-12-31"
]

search_extensions = {
    ".md",
    ".txt",
    ".json",
    ".csv",
    ".html",
    ".py"
}

matches = []

for path in PROJECT_ROOT.rglob("*"):

    if not path.is_file():
        continue

    if path.suffix.lower() not in search_extensions:
        continue

    # Avoid searching huge/raw dataset files again
    if "datasets" in path.parts and path.name != "Climate_Data.csv":
        continue

    try:
        text = path.read_text(
            encoding="utf-8",
            errors="ignore"
        )

        found_terms = [
            term for term in search_terms
            if term.lower() in text.lower()
        ]

        if found_terms:

            matches.append({
                "file": str(path.relative_to(PROJECT_ROOT)),
                "matched_terms": ", ".join(found_terms)
            })

    except Exception:
        pass


matches_df = pd.DataFrame(matches)

if matches_df.empty:
    print("No project-documentation reference to Climate_Data provenance was found.")
else:
    display(matches_df)

NameError: name 'PROJECT_ROOT' is not defined

In [18]:
# FIX — define PROJECT_ROOT again

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()

# If notebook is inside notebooks/, move to project root
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

print("PROJECT_ROOT:")
print(PROJECT_ROOT)

PROJECT_ROOT:
c:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro

In [19]:
# STEP 3B — Search project documentation for Climate_Data provenance

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

print("Project root:")
print(PROJECT_ROOT)

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"Project folder not found: {PROJECT_ROOT}"
    )

search_terms = [
    "Climate_Data",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN",
    "2018-01-01",
    "2024-12-31"
]

search_extensions = {
    ".md",
    ".txt",
    ".json",
    ".html",
    ".py"
}

matches = []

for path in PROJECT_ROOT.rglob("*"):

    if not path.is_file():
        continue

    if path.suffix.lower() not in search_extensions:
        continue

    try:
        text = path.read_text(
            encoding="utf-8",
            errors="ignore"
        )

        found_terms = []

        for term in search_terms:
            if term.lower() in text.lower():
                found_terms.append(term)

        if found_terms:
            matches.append({
                "file": str(path.relative_to(PROJECT_ROOT)),
                "matched_terms": ", ".join(found_terms)
            })

    except Exception:
        continue


matches_df = pd.DataFrame(matches)

print("\nRESULT")
print("=" * 70)

if matches_df.empty:
    print("No project documentation was found that identifies")
    print("the geographic/source provenance of Climate_Data.csv.")
else:
    display(matches_df)

Project root:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro

RESULT
======================================================================
No project documentation was found that identifies
the geographic/source provenance of Climate_Data.csv.

In [20]:
# STEP 3C — Weather variable summary

climate = datasets["Climate_Data.csv"]

weather_columns = [
    "T2M",
    "T2M_MIN",
    "T2M_MAX",
    "RH2M",
    "WS2M",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN"
]

existing_weather_columns = [
    col for col in weather_columns
    if col in climate.columns
]

display(
    climate[existing_weather_columns].describe().T
)

,count,mean,std,min,25%,50%,75%,max
T2M,2557.0,26.620939,4.613406,13.49,23.44,27.47,30.09,36.70
T2M_MIN,2557.0,20.904447,5.619031,5.95,16.61,22.62,25.50,29.47
T2M_MAX,2557.0,33.724517,4.520488,21.44,30.59,32.76,37.28,45.18
RH2M,2557.0,58.894408,19.081115,14.79,46.01,57.70,75.96,94.51
WS2M,2557.0,3.090735,1.443017,0.52,1.98,2.73,3.99,12.25
PRECTOTCORR,2557.0,2.385119,9.383539,0.00,0.00,0.00,0.30,174.26
ALLSKY_SFC_SW_DWN,2557.0,18.587927,20.712328,-999.00,15.81,18.68,22.64,28.92

In [21]:
# STEP 3D — Investigate suspicious climate values

climate = datasets["Climate_Data.csv"].copy()

print("=" * 80)
print("CLIMATE DATA QUALITY INVESTIGATION")
print("=" * 80)

# --------------------------------------------------
# 1. Sentinel / suspicious solar radiation values
# --------------------------------------------------

print("\n1. Solar radiation values <= 0 or suspicious")

solar = climate["ALLSKY_SFC_SW_DWN"]

print("Values equal to -999:", (solar == -999).sum())
print("Values below 0:", (solar < 0).sum())
print("Minimum:", solar.min())

if (solar == -999).sum() > 0:

    print("\nRows containing -999:")
    
    display(
        climate.loc[
            solar == -999,
            ["datetime", "ALLSKY_SFC_SW_DWN"]
        ].head(20)
    )

# --------------------------------------------------
# 2. Suspicious precipitation
# --------------------------------------------------

print("\n2. Precipitation values")

rain = climate["PRECTOTCORR"]

print("Minimum:", rain.min())
print("Maximum:", rain.max())
print("Values > 50:", (rain > 50).sum())
print("Values > 100:", (rain > 100).sum())

print("\nLargest precipitation records:")

display(
    climate[
        ["datetime", "PRECTOTCORR"]
    ]
    .sort_values(
        "PRECTOTCORR",
        ascending=False
    )
    .head(20)
)

# --------------------------------------------------
# 3. Temperature sanity check
# --------------------------------------------------

print("\n3. Temperature sanity check")

display(
    climate[
        [
            "datetime",
            "T2M",
            "T2M_MIN",
            "T2M_MAX"
        ]
    ].describe()
)

# --------------------------------------------------
# 4. Humidity check
# --------------------------------------------------

print("\n4. Humidity sanity check")

humidity = climate["RH2M"]

print("Minimum:", humidity.min())
print("Maximum:", humidity.max())
print("Below 0:", (humidity < 0).sum())
print("Above 100:", (humidity > 100).sum())

# --------------------------------------------------
# 5. Wind speed check
# --------------------------------------------------

print("\n5. Wind speed sanity check")

wind = climate["WS2M"]

print("Minimum:", wind.min())
print("Maximum:", wind.max())
print("Below 0:", (wind < 0).sum())

================================================================================
CLIMATE DATA QUALITY INVESTIGATION
================================================================================

1. Solar radiation values <= 0 or suspicious
Values equal to -999: 1
Values below 0: 1
Minimum: -999.0

Rows containing -999:

       datetime  ALLSKY_SFC_SW_DWN
2529  12/4/2024             -999.0

2. Precipitation values
Minimum: 0.0
Maximum: 174.26
Values > 50: 19
Values > 100: 5

Largest precipitation records:

       datetime  PRECTOTCORR
586   8/10/2019       174.26
2430  8/27/2024       147.89
917    7/6/2020       109.41
1992  6/16/2023       108.35
2429  8/26/2024       100.21
972   8/30/2020        95.57
585    8/9/2019        85.59
1352  9/14/2021        83.99
2428  8/25/2024        82.71
966   8/24/2020        75.22
574   7/29/2019        73.14
965   8/23/2020        67.35
1653  7/12/2022        64.27
1652  7/11/2022        62.29
1367  9/29/2021        60.37
197   7/17/2018        57.08
2432  8/29/2024        56.94
636   9/29/2019        56.82
2005  6/29/2023        51.24
2431  8/28/2024        49.94

3. Temperature sanity check

               T2M      T2M_MIN      T2M_MAX
count  2557.000000  2557.000000  2557.000000
mean     26.620939    20.904447    33.724517
std       4.613406     5.619031     4.520488
min      13.490000     5.950000    21.440000
25%      23.440000    16.610000    30.590000
50%      27.470000    22.620000    32.760000
75%      30.090000    25.500000    37.280000
max      36.700000    29.470000    45.180000

4. Humidity sanity check
Minimum: 14.79
Maximum: 94.51
Below 0: 0
Above 100: 0

5. Wind speed sanity check
Minimum: 0.52
Maximum: 12.25
Below 0: 0

In [22]:
# STEP 3E — Quality checks for soil, rainfall and seasonal datasets

# ============================================================
# 1. SOIL DATA
# ============================================================

soil = datasets["Soil data.csv"]

print("=" * 80)
print("SOIL DATA QUALITY")
print("=" * 80)

print("\nShape:", soil.shape)
print("\nColumns:")
print(list(soil.columns))

print("\nNumeric summary:")
display(
    soil.select_dtypes(include=np.number).describe().T
)

print("\nPotentially suspicious soil values:")

if "pH" in soil.columns:
    print("pH < 0:", (soil["pH"] < 0).sum())
    print("pH > 14:", (soil["pH"] > 14).sum())

if "Nitrogen Value" in soil.columns:
    print(
        "Negative nitrogen:",
        (soil["Nitrogen Value"] < 0).sum()
    )

if "Phosphorous value" in soil.columns:
    print(
        "Negative phosphorus:",
        (soil["Phosphorous value"] < 0).sum()
    )

if "Potassium Value" in soil.columns:
    print(
        "Negative potassium:",
        (soil["Potassium Value"] < 0).sum()
    )


# ============================================================
# 2. RAINFALL 2016 DATA
# ============================================================

rainfall = datasets["Rainfall_2016_districtwise.csv"]

print("\n" + "=" * 80)
print("RAINFALL DATA QUALITY")
print("=" * 80)

print("\nShape:", rainfall.shape)

print("\nColumns:")
print(list(rainfall.columns))

print("\nFirst rows:")
display(rainfall.head())

print("\nNumeric summary:")
display(
    rainfall.select_dtypes(include=np.number).describe().T
)

print("\nUnique districts:")
if "Districts" in rainfall.columns:
    print(rainfall["Districts"].nunique())
    display(
        rainfall["Districts"]
        .value_counts()
        .head(35)
    )


# ============================================================
# 3. DATA_SEASON
# ============================================================

season = datasets["data_season.csv"]

print("\n" + "=" * 80)
print("DATA_SEASON QUALITY")
print("=" * 80)

print("\nShape:", season.shape)

print("\nNumeric summary:")
display(
    season.select_dtypes(include=np.number).describe().T
)

# Temperature anomaly check
if "Temperature" in season.columns:

    print(
        "\nTemperature > 50°C:",
        (season["Temperature"] > 50).sum()
    )

    print(
        "Temperature > 100°C:",
        (season["Temperature"] > 100).sum()
    )

    print("\nLargest temperature records:")

    display(
        season[
            ["Year", "Location", "Temperature", "Crops", "Season"]
        ]
        .sort_values(
            "Temperature",
            ascending=False
        )
        .head(20)
    )

# Soil missingness
if "Soil type" in season.columns:

    print(
        "\nMissing soil type:",
        season["Soil type"].isna().sum()
    )

# Irrigation categories
if "Irrigation" in season.columns:

    print("\nIrrigation categories:")
    display(
        season["Irrigation"]
        .value_counts(dropna=False)
    )

# Crop categories
if "Crops" in season.columns:

    print("\nCrop categories:")
    display(
        season["Crops"]
        .value_counts()
        .head(30)
    )

================================================================================
SOIL DATA QUALITY
================================================================================

Shape: (875, 5)

Columns:
['District', 'Nitrogen Value', 'Phosphorous value', 'Potassium value', 'pH']

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
Nitrogen Value,875.0,24.769715,8.703917,20.0000,20.0315,20.267,25.0550,66.959
Phosphorous value,875.0,61.156523,13.504639,20.0450,50.1395,61.890,73.9550,80.000
Potassium value,875.0,61.739981,12.960962,22.9100,52.7130,63.260,72.2900,80.000
pH,875.0,7.074508,0.282960,6.0503,6.9991,7.006,7.0922,9.031

Potentially suspicious soil values:
pH < 0: 0
pH > 14: 0
Negative nitrogen: 0
Negative phosphorus: 0

================================================================================
RAINFALL DATA QUALITY
================================================================================

Shape: (30, 7)

Columns:
['Sl.No', 'Districts                    ', 'RaingaugeStations_Working  R,Gs', 'RaingaugeStations_Not Working', 'Raingauge Stations_Total', 'Annual Normal Rainfall_Rainydays', 'Normal Rainfall']

First rows:

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
0,2,BENGALURU(R),19,4,23,45,751
1,3,RAMANAGARA,24,3,27,43,822
2,4,CHITRADURGA,33,5,38,40,507
3,5,DAVANAGERE,36,5,41,56,637
4,6,KOLAR,30,5,35,35,622

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
"RaingaugeStations_Working R,Gs",30.0,75.733333,201.222631,15.0,28.50,33.0,43.75,1136.0
RaingaugeStations_Not Working,30.0,9.200000,24.498276,0.0,3.00,4.5,7.00,138.0
Raingauge Stations_Total,30.0,84.933333,225.508152,18.0,31.00,39.5,49.75,1274.0
Annual Normal Rainfall_Rainydays,30.0,60.700000,29.019791,34.0,36.25,52.0,74.75,129.0
Normal Rainfall,30.0,1197.400000,994.538417,507.0,633.25,766.5,1081.75,4285.0

Unique districts:

================================================================================
DATA_SEASON QUALITY
================================================================================

Shape: (3158, 12)

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
Year,3158.0,2009.929702,5.100895,2004.0,2004.0,2010.0,2015.0,2019.0
Area,3158.0,9329.913553,15180.465396,1.0,153.0,2127.0,10910.0,52119.0
Rainfall,3158.0,2813.126662,1163.829953,233.0,2903.1,3296.0,3550.0,3729.8
Temperature,3158.0,65.893699,60.814037,26.8,27.0,38.0,43.0,222.0
yeilds,3158.0,23258.976916,58228.985033,2.0,393.0,2783.0,6589.0,623687.0
Humidity,3158.0,55.582331,2.469773,50.0,54.0,56.0,57.0,60.0
price,3158.0,86271.279291,94123.160706,637.0,2644.0,45186.0,203317.0,249978.0

Temperature > 50°C: 767
Temperature > 100°C: 767

Largest temperature records:

      Year       Location  Temperature    Crops  Season
3144  2004      Davangere        222.0   Cashew    Zaid
538   2004       Madikeri        222.0      Tea  Kharif
2317  2005       Gulbarga        222.0  Coconut    Rabi
2004  2013        Raichur        222.0  Coconut    Rabi
1286  2011       Madikeri        222.0  Coconut    Rabi
1645  2004  Chikmangaluru        222.0  Coconut    Zaid
225   2017         Hassan        222.0      Tea  Kharif
2316  2004       Gulbarga        221.0  Coconut    Rabi
1644  2004  Chikmangaluru        221.0  Coconut    Zaid
1285  2010       Madikeri        221.0  Coconut    Rabi
2003  2012        Raichur        221.0  Coconut    Rabi
224   2016         Hassan        221.0      Tea  Kharif
3143  2018      Davangere        221.0   Cashew    Zaid
537   2004       Madikeri        221.0      Tea  Kharif
536   2004       Madikeri        220.0      Tea  Kharif
223   2015         Hassan        220.0      Tea  Kharif
2315  2018       Gulbarga        220.0  Coconut    Rabi
2002  2011        Raichur        220.0  Coconut    Rabi
1284  2009       Madikeri        220.0  Coconut    Rabi
3142  2017      Davangere        220.0   Cashew    Zaid

Missing soil type: 58

Irrigation categories:

Irrigation
Drip     1310
Basin     968
Spray     880
Name: count, dtype: int64

Crop categories:

Crops
Coconut      1458
Ginger        281
Coffee        150
Arecanut      150
Cardamum      150
Blackgram     150
Paddy         150
Tea           150
Pepper        146
Cashew        146
Groundnut     146
Cocoa          60
Cotton         21
Name: count, dtype: int64

In [23]:
# STEP 3F — Karnataka crop growth-stage reference inspection

growth = datasets[
    "Karnataka_Crop_Growth_Stage_Reference.xlsx"
]

print("=" * 80)
print("KARNATAKA GROWTH-STAGE REFERENCE")
print("=" * 80)

print("\nShape:", growth.shape)

print("\nColumns:")
print(list(growth.columns))

print("\nFull reference table:")
display(growth)

print("\nCrop counts:")
display(
    growth["Crop"]
    .value_counts()
)

print("\nGrowth-stage counts:")
display(
    growth["Growth Stage"]
    .value_counts()
)

================================================================================
KARNATAKA GROWTH-STAGE REFERENCE
================================================================================

Shape: (13, 7)

Columns:
['Crop', 'Growth Stage', 'Stage Description', 'Indicative Duration / Timing', 'Kc Reference', 'Kc Type', 'Evidence Source']

Full reference table:

,Crop,Growth Stage,Stage Description,Indicative Duration / Timing,Kc Reference,Kc Type,Evidence Source
0,Paddy (Rice),Initial / Establishment,Transplanting/establishment and early canopy d...,Reference window; verify locally,Wet paddy Kc_ini = 1.05–1.10; local Hemavathy ...,Kc_ini,Thirumalesha et al. (2026) + FAO-56
1,Paddy (Rice),Development / Tillering,Tillering and rapid vegetative development,≈14–34 DAT overlaps cited phenology,Kc curve from initial toward mid-season,Interpolated,FAO-56 + Indian rice study
2,Paddy (Rice),Mid-Season / Flowering,Panicle initiation through flowering/full canopy,≈27–65 DAT in cited Indian field study,Wet paddy Kc_mid = 1.20,Kc_mid,Thirumalesha et al. (2026)
3,Paddy (Rice),Late-Season / Maturity,Physiological maturity and senescence,≈97–101 DAT to maturity,Wet paddy Kc_end = 1.05,Kc_end,Thirumalesha et al. (2026) + FAO-56
4,Paddy (Rice),Harvest,Harvest/end of crop cycle,≈112–113 DAT in cited Indian field study,Terminal reference; harvest timing is variety-...,Terminal,Indian rice study
5,Finger Millet (Ragi),Initial / Establishment,Germination and establishment,Beginning of vegetative phase,Local Hemavathy study Kc_ini = 0.30,Kc_ini,Thirumalesha et al. (2026)
6,Finger Millet (Ragi),Development / Vegetative,Vegetative growth and canopy expansion,≈0–6 weeks after sowing,Interpolate from Kc_ini toward Kc_mid,Interpolated,Thirumalesha et al. (2026) + Indian ragi research
7,Finger Millet (Ragi),Mid-Season / Flowering,Flowering and peak crop development,≈7–9 weeks after sowing,Local Kc_mid = 1.00; Bangalore study peak ≈1.0...,Kc_mid / peak,Thirumalesha et al. (2026); IMD MAUSAM
8,Finger Millet (Ragi),Late-Season / Grain Development & Maturity,Grain development and maturation,Grain development ≈10–12 WAS; maturity ≈13–14 WAS,Local Kc_end = 0.30,Kc_end,Thirumalesha et al. (2026) + Indian ragi research
9,Maize,Initial / Establishment,Emergence and early establishment,20 days (FAO indicative),Local Kc_ini = 0.30,Kc_ini,FAO-56 + Thirumalesha et al. (2026)
10,Maize,Development / Vegetative,Rapid leaf and canopy development,35 days (FAO indicative),Kc increases from initial toward mid-season,Interpolated,FAO-56 + Thirumalesha et al. (2026)
11,Maize,Mid-Season / Flowering & Grain Development,"Full canopy, flowering and peak water demand",40 days (FAO indicative),Local Kc_mid = 1.20; FAO typical = 1.15,Kc_mid,FAO-56 + Thirumalesha et al. (2026)
12,Maize,Late-Season / Maturity,Grain filling and maturity,30 days (FAO indicative),Local Kc_end = 0.35; FAO typical = 0.70,Kc_end,FAO-56 + Thirumalesha et al. (2026)

Crop counts:

Crop
Paddy (Rice)            5
Finger Millet (Ragi)    4
Maize                   4
Name: count, dtype: int64

Growth-stage counts:

Growth Stage
Initial / Establishment                       3
Mid-Season / Flowering                        2
Late-Season / Maturity                        2
Development / Vegetative                      2
Development / Tillering                       1
Harvest                                       1
Late-Season / Grain Development & Maturity    1
Mid-Season / Flowering & Grain Development    1
Name: count, dtype: int64

In [24]:
# STEP 4A — Create cleaned-data structure

from pathlib import Path
import shutil

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Raw data directory:")
print(RAW_DIR)

print("\nCleaned data directory:")
print(CLEAN_DIR)

print("\nRaw data will remain untouched.")

Raw data directory:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\raw

Cleaned data directory:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned

Raw data will remain untouched.

In [2]:
# STEP 4B — Clean Climate_Data.csv
# Self-contained version

from pathlib import Path
import pandas as pd
import numpy as np

# --------------------------------------------------
# 1. Project paths
# --------------------------------------------------

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

# Create cleaned-data folder if it doesn't exist
CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 2. Load RAW climate data
# --------------------------------------------------

raw_file = RAW_DIR / "Climate_Data.csv"

if not raw_file.exists():
    raise FileNotFoundError(
        f"Raw file not found:\n{raw_file}"
    )

climate_raw = pd.read_csv(
    raw_file
)

climate = climate_raw.copy()

print("RAW FILE:")
print(raw_file)

print("\nRAW SHAPE:")
print(climate.shape)

# --------------------------------------------------
# 3. Convert datetime
# --------------------------------------------------

climate["datetime"] = pd.to_datetime(
    climate["datetime"],
    errors="coerce"
)

invalid_dates = climate["datetime"].isna().sum()

print("\nInvalid datetime values:", invalid_dates)

# Remove only rows with invalid dates
climate = climate.dropna(
    subset=["datetime"]
).copy()

# --------------------------------------------------
# 4. Convert known sentinel value
# --------------------------------------------------

solar_column = "ALLSKY_SFC_SW_DWN"

sentinel_count = (
    climate[solar_column] == -999
).sum()

print(
    "Solar radiation values equal to -999:",
    sentinel_count
)

climate.loc[
    climate[solar_column] == -999,
    solar_column
] = np.nan

# --------------------------------------------------
# 5. Duplicate datetime check
# --------------------------------------------------

duplicate_dates = climate["datetime"].duplicated().sum()

print(
    "Duplicate datetime records:",
    duplicate_dates
)

# We are NOT removing duplicates automatically.
# We only report them at this stage.

# --------------------------------------------------
# 6. Missing-value report
# --------------------------------------------------

print("\nMissing values after cleaning:")
missing_report = climate.isna().sum()

display(
    missing_report[missing_report > 0]
)

# --------------------------------------------------
# 7. Sort by datetime
# --------------------------------------------------

climate = climate.sort_values(
    "datetime"
).reset_index(drop=True)

# --------------------------------------------------
# 8. Save cleaned COPY
# --------------------------------------------------

clean_file = CLEAN_DIR / "Climate_Data_cleaned.csv"

climate.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED FILE SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(climate.shape)

print("\nDate range:")
print("Start:", climate["datetime"].min())
print("End  :", climate["datetime"].max())

RAW FILE:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\raw\Climate_Data.csv

RAW SHAPE:
(2557, 11)

Invalid datetime values: 0
Solar radiation values equal to -999: 1
Duplicate datetime records: 0

Missing values after cleaning:

ALLSKY_SFC_SW_DWN    1
dtype: int64

CLEANED FILE SAVED:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\Climate_Data_cleaned.csv

FINAL SHAPE:
(2557, 11)

Date range:
Start: 2018-01-01 00:00:00
End  : 2024-12-31 00:00:00

In [3]:
# STEP 4C — Clean Crop_Calender.csv

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 1. Load raw calendar
# --------------------------------------------------

raw_file = RAW_DIR / "Crop_Calender.csv"

calendar_raw = pd.read_csv(
    raw_file,
    encoding="latin1"
)

calendar = calendar_raw.copy()

print("RAW SHAPE:")
print(calendar.shape)

print("\nRAW COLUMNS:")
print(list(calendar.columns))

# --------------------------------------------------
# 2. Remove completely empty columns
# --------------------------------------------------

empty_columns = [
    col for col in calendar.columns
    if calendar[col].isna().all()
]

print("\nCompletely empty columns:")
print(empty_columns)

calendar = calendar.drop(
    columns=empty_columns
)

# --------------------------------------------------
# 3. Convert numeric fields
# --------------------------------------------------

numeric_columns = [
    "Duration (days)",
    "Root Depth (cm)",
    "Kc (Crop Coefficient)",
    "ETo (mm/day)",
    "ETc (mm/day)",
    "Effective Rainfall (mm)",
    "WHC (mm/mm)"
]

for col in numeric_columns:

    if col in calendar.columns:

        calendar[col] = pd.to_numeric(
            calendar[col],
            errors="coerce"
        )

# --------------------------------------------------
# 4. Clean text fields
# --------------------------------------------------

text_columns = [
    "Crop",
    "Stage"
]

for col in text_columns:

    if col in calendar.columns:

        calendar[col] = (
            calendar[col]
            .astype("string")
            .str.strip()
        )

# --------------------------------------------------
# 5. Check missing values
# --------------------------------------------------

print("\nMissing values after type conversion:")

missing = calendar.isna().sum()

display(
    missing[missing > 0]
)

# --------------------------------------------------
# 6. Duplicate rows
# --------------------------------------------------

duplicates = calendar.duplicated().sum()

print("\nDuplicate rows:", duplicates)

# --------------------------------------------------
# 7. Basic validity checks
# --------------------------------------------------

print("\nValidity checks:")

if "Duration (days)" in calendar.columns:
    print(
        "Negative duration:",
        (calendar["Duration (days)"] < 0).sum()
    )

if "Root Depth (cm)" in calendar.columns:
    print(
        "Negative root depth:",
        (calendar["Root Depth (cm)"] < 0).sum()
    )

if "Kc (Crop Coefficient)" in calendar.columns:
    print(
        "Negative Kc:",
        (calendar["Kc (Crop Coefficient)"] < 0).sum()
    )

if "ETo (mm/day)" in calendar.columns:
    print(
        "Negative ETo:",
        (calendar["ETo (mm/day)"] < 0).sum()
    )

if "ETc (mm/day)" in calendar.columns:
    print(
        "Negative ETc:",
        (calendar["ETc (mm/day)"] < 0).sum()
    )

if "Effective Rainfall (mm)" in calendar.columns:
    print(
        "Negative effective rainfall:",
        (calendar["Effective Rainfall (mm)"] < 0).sum()
    )

if "WHC (mm/mm)" in calendar.columns:
    print(
        "Negative WHC:",
        (calendar["WHC (mm/mm)"] < 0).sum()
    )

# --------------------------------------------------
# 8. DO NOT fill missing Kc yet
# --------------------------------------------------

print(
    "\nIMPORTANT: Missing Kc values are preserved as NaN."
)

# --------------------------------------------------
# 9. Save cleaned copy
# --------------------------------------------------

clean_file = (
    CLEAN_DIR / "Crop_Calender_cleaned.csv"
)

calendar.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED FILE SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(calendar.shape)

print("\nFINAL COLUMNS:")
print(list(calendar.columns))

RAW SHAPE:
(25, 14)

RAW COLUMNS:
['Crop', 'Stage', 'Duration (days)', 'Root Depth (cm)', 'Kc (Crop Coefficient)', 'ETo (mm/day)', 'ETc (mm/day)', 'Effective Rainfall (mm)', 'WHC (mm/m)', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Completely empty columns:
['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Missing values after type conversion:

Kc (Crop Coefficient)       5
ETo (mm/day)                5
Effective Rainfall (mm)    20
dtype: int64

Duplicate rows: 0

Validity checks:
Negative duration: 0
Negative root depth: 0
Negative Kc: 0
Negative ETo: 0
Negative ETc: 0
Negative effective rainfall: 0

IMPORTANT: Missing Kc values are preserved as NaN.

CLEANED FILE SAVED:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\Crop_Calender_cleaned.csv

FINAL SHAPE:
(25, 9)

FINAL COLUMNS:
['Crop', 'Stage', 'Duration (days)', 'Root Depth (cm)', 'Kc (Crop Coefficient)', 'ETo (mm/day)', 'ETc (mm/day)', 'Effective Rainfall (mm)', 'WHC (mm/m)']

In [4]:
# STEP 4D — Clean Karnataka Crop Growth Stage Reference

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 1. Load raw reference workbook
# --------------------------------------------------

raw_file = (
    RAW_DIR /
    "Karnataka_Crop_Growth_Stage_Reference.xlsx"
)

growth_raw = pd.read_excel(raw_file)

growth = growth_raw.copy()

print("RAW SHAPE:")
print(growth.shape)

print("\nRAW COLUMNS:")
print(list(growth.columns))

# --------------------------------------------------
# 2. Remove completely empty columns
# --------------------------------------------------

empty_columns = [
    col for col in growth.columns
    if growth[col].isna().all()
]

print("\nCompletely empty columns:")
print(empty_columns)

growth = growth.drop(
    columns=empty_columns
)

# --------------------------------------------------
# 3. Clean column names
# --------------------------------------------------

growth.columns = (
    growth.columns
    .astype(str)
    .str.strip()
)

# --------------------------------------------------
# 4. Clean text fields
# --------------------------------------------------

text_columns = [
    "Crop",
    "Growth Stage",
    "Stage Description",
    "Indicative Duration / Timing",
    "Kc Reference",
    "Kc Type",
    "Evidence Source"
]

for col in text_columns:

    if col in growth.columns:

        growth[col] = (
            growth[col]
            .astype("string")
            .str.strip()
        )

# --------------------------------------------------
# 5. Check missing values
# --------------------------------------------------

print("\nMissing values:")

missing = growth.isna().sum()

display(
    missing[missing > 0]
)

# --------------------------------------------------
# 6. Duplicate rows
# --------------------------------------------------

duplicates = growth.duplicated().sum()

print("\nDuplicate rows:", duplicates)

# --------------------------------------------------
# 7. Crop summary
# --------------------------------------------------

print("\nCrop summary:")

display(
    growth["Crop"]
    .value_counts()
)

# --------------------------------------------------
# 8. Growth-stage summary
# --------------------------------------------------

print("\nGrowth-stage summary:")

display(
    growth["Growth Stage"]
    .value_counts()
)

# --------------------------------------------------
# 9. Kc type summary
# --------------------------------------------------

print("\nKc type summary:")

display(
    growth["Kc Type"]
    .value_counts()
)

# --------------------------------------------------
# 10. Check suspicious text values
# --------------------------------------------------

print("\nRows with missing critical fields:")

critical_columns = [
    "Crop",
    "Growth Stage",
    "Kc Reference",
    "Evidence Source"
]

available_critical = [
    col for col in critical_columns
    if col in growth.columns
]

display(
    growth[
        growth[available_critical].isna().any(axis=1)
    ]
)

# --------------------------------------------------
# 11. Save cleaned reference
# --------------------------------------------------

clean_file = (
    CLEAN_DIR /
    "Karnataka_Crop_Growth_Stage_Reference_cleaned.csv"
)

growth.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED FILE SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(growth.shape)

print("\nFINAL COLUMNS:")
print(list(growth.columns))

RAW SHAPE:
(13, 7)

RAW COLUMNS:
['Crop', 'Growth Stage', 'Stage Description', 'Indicative Duration / Timing', 'Kc Reference', 'Kc Type', 'Evidence Source']

Completely empty columns:
[]

Missing values:

Series([], dtype: int64)

Duplicate rows: 0

Crop summary:

Crop
Paddy (Rice)            5
Finger Millet (Ragi)    4
Maize                   4
Name: count, dtype: Int64

Growth-stage summary:

Growth Stage
Initial / Establishment                       3
Mid-Season / Flowering                        2
Late-Season / Maturity                        2
Development / Vegetative                      2
Development / Tillering                       1
Harvest                                       1
Late-Season / Grain Development & Maturity    1
Mid-Season / Flowering & Grain Development    1
Name: count, dtype: Int64

Kc type summary:

Kc Type
Kc_ini           3
Interpolated     3
Kc_end           3
Kc_mid           2
Terminal         1
Kc_mid / peak    1
Name: count, dtype: Int64

Rows with missing critical fields:

Empty DataFrame
Columns: [Crop, Growth Stage, Stage Description, Indicative Duration / Timing, Kc Reference, Kc Type, Evidence Source]
Index: []

CLEANED FILE SAVED:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\Karnataka_Crop_Growth_Stage_Reference_cleaned.csv

FINAL SHAPE:
(13, 7)

FINAL COLUMNS:
['Crop', 'Growth Stage', 'Stage Description', 'Indicative Duration / Timing', 'Kc Reference', 'Kc Type', 'Evidence Source']

In [5]:
# STEP 4E — Clean Soil data.csv

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 1. Load raw soil dataset
# --------------------------------------------------

raw_file = RAW_DIR / "Soil data.csv"

soil_raw = pd.read_csv(raw_file)

soil = soil_raw.copy()

print("RAW SHAPE:")
print(soil.shape)

print("\nRAW COLUMNS:")
print(list(soil.columns))

# --------------------------------------------------
# 2. Clean column names
# --------------------------------------------------

soil.columns = (
    soil.columns
    .astype(str)
    .str.strip()
)

# --------------------------------------------------
# 3. Clean district names
# --------------------------------------------------

soil["District"] = (
    soil["District"]
    .astype("string")
    .str.strip()
)

# --------------------------------------------------
# 4. Convert numeric columns
# --------------------------------------------------

numeric_columns = [
    "Nitrogen Value",
    "Phosphorous value",
    "Potassium Value",
    "pH"
]

for col in numeric_columns:

    soil[col] = pd.to_numeric(
        soil[col],
        errors="coerce"
    )

# --------------------------------------------------
# 5. Missing values
# --------------------------------------------------

print("\nMissing values:")

missing = soil.isna().sum()

display(
    missing[missing > 0]
)

# --------------------------------------------------
# 6. Duplicate rows
# --------------------------------------------------

print(
    "\nDuplicate rows:",
    soil.duplicated().sum()
)

# --------------------------------------------------
# 7. Basic validity checks
# --------------------------------------------------

print("\nValidity checks:")

print(
    "Negative Nitrogen:",
    (soil["Nitrogen Value"] < 0).sum()
)

print(
    "Negative Phosphorus:",
    (soil["Phosphorous value"] < 0).sum()
)

print(
    "Negative Potassium:",
    (soil["Potassium Value"] < 0).sum()
)

print(
    "pH below 0:",
    (soil["pH"] < 0).sum()
)

print(
    "pH above 14:",
    (soil["pH"] > 14).sum()
)

# --------------------------------------------------
# 8. Numeric summary
# --------------------------------------------------

print("\nNumeric summary:")

display(
    soil[numeric_columns].describe().T
)

# --------------------------------------------------
# 9. District summary
# --------------------------------------------------

print("\nNumber of unique districts:")
print(
    soil["District"].nunique()
)

print("\nDistrict distribution:")

display(
    soil["District"]
    .value_counts()
    .head(30)
)

# --------------------------------------------------
# 10. Save cleaned copy
# --------------------------------------------------

clean_file = CLEAN_DIR / "Soil_data_cleaned.csv"

soil.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED FILE SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(soil.shape)

RAW SHAPE:
(875, 5)

RAW COLUMNS:
['District', 'Nitrogen Value', 'Phosphorous value', 'Potassium value', 'pH']

KeyError: 'Potassium Value'

In [6]:
# STEP 4E — Inspect and clean Soil data.csv safely

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------
# 1. Load raw soil data
# --------------------------------------------------

raw_file = RAW_DIR / "Soil data.csv"

soil = pd.read_csv(raw_file)

print("RAW SHAPE:", soil.shape)

print("\nACTUAL COLUMN NAMES:")
for i, col in enumerate(soil.columns):
    print(i, repr(col))

RAW SHAPE: (875, 5)

ACTUAL COLUMN NAMES:
0 'District'
1 'Nitrogen Value'
2 'Phosphorous value'
3 'Potassium value'
4 'pH'

In [7]:
# STEP 4E — Robust Soil Cleaning

# Reload raw file
soil = pd.read_csv(raw_file).copy()

# Clean column-name whitespace
soil.columns = (
    soil.columns
    .astype(str)
    .str.strip()
)

print("Cleaned column names:")
print(list(soil.columns))

# --------------------------------------------------
# 2. Identify columns safely
# --------------------------------------------------

def find_column(columns, possible_names):
    """
    Find a column by normalized name.
    """
    normalized = {
        str(col).strip().lower(): col
        for col in columns
    }

    for name in possible_names:
        key = name.strip().lower()

        if key in normalized:
            return normalized[key]

    return None


district_col = find_column(
    soil.columns,
    ["district"]
)

nitrogen_col = find_column(
    soil.columns,
    ["nitrogen value", "nitrogen", "n"]
)

phosphorus_col = find_column(
    soil.columns,
    [
        "phosphorous value",
        "phosphorus value",
        "phosphorous",
        "phosphorus",
        "p"
    ]
)

potassium_col = find_column(
    soil.columns,
    [
        "potassium value",
        "potassium",
        "k"
    ]
)

ph_col = find_column(
    soil.columns,
    ["ph", "pH"]
)

print("\nIDENTIFIED COLUMNS")
print("District   :", district_col)
print("Nitrogen   :", nitrogen_col)
print("Phosphorus :", phosphorus_col)
print("Potassium  :", potassium_col)
print("pH         :", ph_col)

Cleaned column names:
['District', 'Nitrogen Value', 'Phosphorous value', 'Potassium value', 'pH']

IDENTIFIED COLUMNS
District   : District
Nitrogen   : Nitrogen Value
Phosphorus : Phosphorous value
Potassium  : Potassium value
pH         : pH

In [8]:
# STEP 4E-C — Save cleaned soil dataset

clean_file = CLEAN_DIR / "Soil_data_cleaned.csv"

soil.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED SOIL DATA SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(soil.shape)

CLEANED SOIL DATA SAVED:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\Soil_data_cleaned.csv

FINAL SHAPE:
(875, 5)

In [9]:
# STEP 4F — Clean Rainfall_2016_districtwise.csv

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 1. Load raw rainfall data
# --------------------------------------------------

raw_file = RAW_DIR / "Rainfall_2016_districtwise.csv"

rainfall = pd.read_csv(raw_file).copy()

print("RAW SHAPE:")
print(rainfall.shape)

print("\nRAW COLUMNS:")
print(list(rainfall.columns))

# --------------------------------------------------
# 2. Clean column names
# --------------------------------------------------

rainfall.columns = (
    rainfall.columns
    .astype(str)
    .str.strip()
)

# --------------------------------------------------
# 3. Identify text/location columns
# --------------------------------------------------

for col in rainfall.columns:

    if rainfall[col].dtype == "object":
        rainfall[col] = (
            rainfall[col]
            .astype("string")
            .str.strip()
        )

# --------------------------------------------------
# 4. Convert numeric columns
# --------------------------------------------------

for col in rainfall.columns:

    if col not in ["Districts", "District", "Sl.No"]:
        rainfall[col] = pd.to_numeric(
            rainfall[col],
            errors="coerce"
        )

# --------------------------------------------------
# 5. Missing values
# --------------------------------------------------

print("\nMISSING VALUES:")

missing = rainfall.isna().sum()

display(
    missing[missing > 0]
)

# --------------------------------------------------
# 6. Duplicate rows
# --------------------------------------------------

print(
    "\nDuplicate rows:",
    rainfall.duplicated().sum()
)

# --------------------------------------------------
# 7. District analysis
# --------------------------------------------------

possible_district_columns = [
    col for col in rainfall.columns
    if str(col).lower() in [
        "district",
        "districts"
    ]
]

if possible_district_columns:

    district_col = possible_district_columns[0]

    print("\nDistrict column:", district_col)

    print(
        "Unique districts:",
        rainfall[district_col].nunique()
    )

    display(
        rainfall[district_col]
        .value_counts()
    )

# --------------------------------------------------
# 8. Numeric validity
# --------------------------------------------------

numeric_columns = rainfall.select_dtypes(
    include=np.number
).columns.tolist()

print("\nNUMERIC SUMMARY:")

if numeric_columns:
    display(
        rainfall[numeric_columns]
        .describe()
        .T
    )

# --------------------------------------------------
# 9. Negative rainfall check
# --------------------------------------------------

rainfall_numeric = rainfall[
    numeric_columns
]

negative_counts = (
    rainfall_numeric < 0
).sum()

print("\nNEGATIVE VALUES:")

display(
    negative_counts[
        negative_counts > 0
    ]
)

# --------------------------------------------------
# 10. Save cleaned copy
# --------------------------------------------------

clean_file = (
    CLEAN_DIR /
    "Rainfall_2016_districtwise_cleaned.csv"
)

rainfall.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED FILE SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(rainfall.shape)

RAW SHAPE:
(30, 7)

RAW COLUMNS:
['Sl.No', 'Districts                    ', 'RaingaugeStations_Working  R,Gs', 'RaingaugeStations_Not Working', 'Raingauge Stations_Total', 'Annual Normal Rainfall_Rainydays', 'Normal Rainfall']

MISSING VALUES:

Series([], dtype: int64)

Duplicate rows: 0

District column: Districts
Unique districts: 30

Districts
BENGALURU(R)        1
RAMANAGARA          1
CHITRADURGA         1
DAVANAGERE          1
KOLAR               1
CHIKKABALLAPURA     1
SHIVAMOGGA          1
TUMAKURU            1
CHIKKAMAGALURU      1
DAKSHINA KANNADA    1
UDUPI               1
HASSAN              1
KODAGU              1
MANDYA              1
MYSURU              1
CHAMARAJANAGAR      1
BELAGAVI            1
VIJAYAPURA          1
BAGALKOT            1
DHARAWAD            1
GADAG               1
HAVERI              1
UTTARA KANNADA      1
BALLARI             1
BIDAR               1
KALABURAGI          1
YADGIRI             1
RAICHUR             1
KOPPAL              1
Total               1
Name: count, dtype: Int64

NUMERIC SUMMARY:

,count,mean,std,min,25%,50%,75%,max
"RaingaugeStations_Working R,Gs",30.0,75.733333,201.222631,15.0,28.50,33.0,43.75,1136.0
RaingaugeStations_Not Working,30.0,9.200000,24.498276,0.0,3.00,4.5,7.00,138.0
Raingauge Stations_Total,30.0,84.933333,225.508152,18.0,31.00,39.5,49.75,1274.0
Annual Normal Rainfall_Rainydays,30.0,60.700000,29.019791,34.0,36.25,52.0,74.75,129.0
Normal Rainfall,30.0,1197.400000,994.538417,507.0,633.25,766.5,1081.75,4285.0

NEGATIVE VALUES:

Series([], dtype: int64)

CLEANED FILE SAVED:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\Rainfall_2016_districtwise_cleaned.csv

FINAL SHAPE:
(30, 7)

In [10]:
# STEP 4G — Clean crop_water_data.csv

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 1. Load raw dataset
# --------------------------------------------------

raw_file = RAW_DIR / "crop_water_data.csv"

water_raw = pd.read_csv(raw_file)

water = water_raw.copy()

print("RAW SHAPE:")
print(water.shape)

print("\nRAW COLUMNS:")
print(list(water.columns))

# --------------------------------------------------
# 2. Clean column names
# --------------------------------------------------

water.columns = (
    water.columns
    .astype(str)
    .str.strip()
)

# --------------------------------------------------
# 3. Clean categorical fields
# --------------------------------------------------

categorical_columns = [
    "crop_type",
    "soil_type",
    "growth_stage",
    "irrigation_method"
]

for col in categorical_columns:

    if col in water.columns:

        water[col] = (
            water[col]
            .astype("string")
            .str.strip()
        )

# --------------------------------------------------
# 4. Convert numeric fields
# --------------------------------------------------

numeric_columns = [
    "temperature",
    "humidity",
    "rainfall_mm",
    "wind_speed_kmh",
    "solar_radiation",
    "field_area_ha",
    "crop_age_days",
    "soil_moisture_pct",
    "evapotranspiration",
    "water_requirement_liters"
]

for col in numeric_columns:

    if col in water.columns:

        water[col] = pd.to_numeric(
            water[col],
            errors="coerce"
        )

# --------------------------------------------------
# 5. Missing values
# --------------------------------------------------

print("\nMISSING VALUES:")

missing = water.isna().sum()

display(
    missing[missing > 0]
)

# --------------------------------------------------
# 6. Duplicate rows
# --------------------------------------------------

print(
    "\nDuplicate rows:",
    water.duplicated().sum()
)

# --------------------------------------------------
# 7. Basic physical validity checks
# --------------------------------------------------

print("\nPHYSICAL VALIDITY CHECKS")
print("=" * 60)

if "temperature" in water.columns:
    print(
        "Temperature < -20:",
        (water["temperature"] < -20).sum()
    )
    print(
        "Temperature > 60:",
        (water["temperature"] > 60).sum()
    )

if "humidity" in water.columns:
    print(
        "Humidity < 0:",
        (water["humidity"] < 0).sum()
    )
    print(
        "Humidity > 100:",
        (water["humidity"] > 100).sum()
    )

if "rainfall_mm" in water.columns:
    print(
        "Negative rainfall:",
        (water["rainfall_mm"] < 0).sum()
    )

if "wind_speed_kmh" in water.columns:
    print(
        "Negative wind:",
        (water["wind_speed_kmh"] < 0).sum()
    )

if "solar_radiation" in water.columns:
    print(
        "Negative solar radiation:",
        (water["solar_radiation"] < 0).sum()
    )

if "field_area_ha" in water.columns:
    print(
        "Non-positive field area:",
        (water["field_area_ha"] <= 0).sum()
    )

if "crop_age_days" in water.columns:
    print(
        "Negative crop age:",
        (water["crop_age_days"] < 0).sum()
    )

if "soil_moisture_pct" in water.columns:
    print(
        "Soil moisture < 0:",
        (water["soil_moisture_pct"] < 0).sum()
    )
    print(
        "Soil moisture > 100:",
        (water["soil_moisture_pct"] > 100).sum()
    )

if "evapotranspiration" in water.columns:
    print(
        "Negative evapotranspiration:",
        (water["evapotranspiration"] < 0).sum()
    )

if "water_requirement_liters" in water.columns:
    print(
        "Non-positive water requirement:",
        (water["water_requirement_liters"] <= 0).sum()
    )

# --------------------------------------------------
# 8. Dataset summaries
# --------------------------------------------------

print("\nNUMERIC SUMMARY:")

available_numeric = [
    col for col in numeric_columns
    if col in water.columns
]

display(
    water[available_numeric]
    .describe()
    .T
)

print("\nCATEGORICAL SUMMARY:")

for col in categorical_columns:

    if col in water.columns:

        print(f"\n{col}:")

        display(
            water[col]
            .value_counts(dropna=False)
            .head(20)
        )

# --------------------------------------------------
# 9. Explicit target warning
# --------------------------------------------------

print("\nIMPORTANT RESEARCH NOTE")
print("=" * 60)

print(
    "water_requirement_liters is preserved for traceability, "
    "but it is NOT treated as independently observed CWR "
    "ground truth."
)

# --------------------------------------------------
# 10. Save cleaned copy
# --------------------------------------------------

clean_file = (
    CLEAN_DIR /
    "crop_water_data_cleaned.csv"
)

water.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED FILE SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(water.shape)

RAW SHAPE:
(10000, 14)

RAW COLUMNS:
['crop_type', 'soil_type', 'growth_stage', 'temperature', 'humidity', 'rainfall_mm', 'wind_speed_kmh', 'solar_radiation', 'field_area_ha', 'irrigation_method', 'crop_age_days', 'soil_moisture_pct', 'evapotranspiration', 'water_requirement_liters']

MISSING VALUES:

Series([], dtype: int64)

Duplicate rows: 0

PHYSICAL VALIDITY CHECKS
============================================================
Temperature < -20: 0
Temperature > 60: 0
Humidity < 0: 0
Humidity > 100: 0
Negative rainfall: 0
Negative wind: 0
Negative solar radiation: 0
Non-positive field area: 0
Negative crop age: 0
Soil moisture < 0: 0
Soil moisture > 100: 0
Negative evapotranspiration: 0
Non-positive water requirement: 0

NUMERIC SUMMARY:

,count,mean,std,min,25%,50%,75%,max
temperature,10000.0,27.482020,10.050012,10.00,18.8000,27.500,36.10,45.00
humidity,10000.0,57.364880,21.631928,20.00,38.6000,57.450,76.00,95.00
rainfall_mm,10000.0,24.962770,14.466699,0.00,12.3000,25.000,37.50,50.00
wind_speed_kmh,10000.0,20.013850,11.478478,0.00,10.3000,19.900,30.00,40.00
solar_radiation,10000.0,17.531440,7.195423,5.00,11.3000,17.600,23.80,30.00
field_area_ha,10000.0,25.323430,14.218665,0.51,12.9675,25.550,37.66,49.99
crop_age_days,10000.0,89.143400,51.418085,1.00,44.0000,89.000,134.00,179.00
soil_moisture_pct,10000.0,34.810230,14.428256,10.00,22.2000,34.900,47.20,60.00
evapotranspiration,10000.0,8.027086,4.049261,1.00,4.4900,8.010,11.59,15.00
water_requirement_liters,10000.0,1368.866571,1363.473560,1.00,321.7300,902.645,2002.78,5000.00

CATEGORICAL SUMMARY:

crop_type:

crop_type
Sugarcane    1464
Cotton       1439
Potato       1429
Wheat        1428
Soybean      1426
Rice         1423
Maize        1391
Name: count, dtype: Int64

soil_type:

soil_type
Loamy    2068
Peaty    2017
Sandy    2010
Silty    1992
Clay     1913
Name: count, dtype: Int64

growth_stage:

growth_stage
Fruiting       2047
Maturity       2025
Germination    1993
Vegetative     1983
Flowering      1952
Name: count, dtype: Int64

irrigation_method:

irrigation_method
Flood        2531
Furrow       2531
Drip         2493
Sprinkler    2445
Name: count, dtype: Int64

IMPORTANT RESEARCH NOTE
============================================================
water_requirement_liters is preserved for traceability, but it is NOT treated as independently observed CWR ground truth.

CLEANED FILE SAVED:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\crop_water_data_cleaned.csv

FINAL SHAPE:
(10000, 14)

In [11]:
# ============================================================
# JALACHAKRA — STEP 4H
# WATER-AWARE CROP RECOMMENDATION
# DATASET CLEANING
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. PROJECT PATHS
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("PROJECT ROOT:")
print(PROJECT_ROOT)

# ------------------------------------------------------------
# 2. LOAD RAW DATA
# ------------------------------------------------------------

raw_file = RAW_DIR / "Crop_recommendation.csv"

if not raw_file.exists():
    raise FileNotFoundError(
        f"Dataset not found:\n{raw_file}"
    )

crop_rec_raw = pd.read_csv(raw_file)

crop_rec = crop_rec_raw.copy()

print("\nRAW DATASET")
print("=" * 60)
print("File:", raw_file)
print("Shape:", crop_rec.shape)

# ------------------------------------------------------------
# 3. INSPECT ORIGINAL COLUMNS
# ------------------------------------------------------------

print("\nORIGINAL COLUMNS:")
for i, column in enumerate(crop_rec.columns):
    print(i, repr(column))

# ------------------------------------------------------------
# 4. CLEAN COLUMN NAMES
# ------------------------------------------------------------

crop_rec.columns = (
    crop_rec.columns
    .astype(str)
    .str.strip()
)

print("\nCLEANED COLUMN NAMES:")
print(list(crop_rec.columns))

# ------------------------------------------------------------
# 5. EXPECTED DATASET STRUCTURE
# ------------------------------------------------------------

expected_columns = [
    "N",
    "P",
    "K",
    "temperature",
    "humidity",
    "ph",
    "rainfall",
    "label"
]

print("\nEXPECTED COLUMNS CHECK")
print("=" * 60)

for column in expected_columns:

    if column in crop_rec.columns:
        print(f"FOUND     : {column}")
    else:
        print(f"NOT FOUND : {column}")

# ------------------------------------------------------------
# 6. CLEAN CROP LABEL
# ------------------------------------------------------------

if "label" not in crop_rec.columns:
    raise KeyError(
        "The crop target column 'label' was not found."
    )

crop_rec["label"] = (
    crop_rec["label"]
    .astype("string")
    .str.strip()
)

# ------------------------------------------------------------
# 7. CONVERT NUMERIC VARIABLES
# ------------------------------------------------------------

numeric_columns = [
    "N",
    "P",
    "K",
    "temperature",
    "humidity",
    "ph",
    "rainfall"
]

for column in numeric_columns:

    if column in crop_rec.columns:

        crop_rec[column] = pd.to_numeric(
            crop_rec[column],
            errors="coerce"
        )

# ------------------------------------------------------------
# 8. MISSING VALUE ANALYSIS
# ------------------------------------------------------------

print("\nMISSING VALUE CHECK")
print("=" * 60)

missing = crop_rec.isna().sum()

if missing.sum() == 0:
    print("No missing values found.")

else:
    display(
        missing[missing > 0]
    )

# ------------------------------------------------------------
# 9. DUPLICATE ANALYSIS
# ------------------------------------------------------------

duplicate_count = int(
    crop_rec.duplicated().sum()
)

print("\nDUPLICATE ROWS:", duplicate_count)

# IMPORTANT:
# We are NOT deleting duplicates automatically.
# We only report them during this phase.

# ------------------------------------------------------------
# 10. PHYSICAL VALIDITY CHECKS
# ------------------------------------------------------------

print("\nPHYSICAL VALIDITY CHECKS")
print("=" * 60)

# Nitrogen
if "N" in crop_rec.columns:

    print(
        "Negative N:",
        int((crop_rec["N"] < 0).sum())
    )

# Phosphorus
if "P" in crop_rec.columns:

    print(
        "Negative P:",
        int((crop_rec["P"] < 0).sum())
    )

# Potassium
if "K" in crop_rec.columns:

    print(
        "Negative K:",
        int((crop_rec["K"] < 0).sum())
    )

# Temperature
if "temperature" in crop_rec.columns:

    print(
        "Temperature < -20°C:",
        int((crop_rec["temperature"] < -20).sum())
    )

    print(
        "Temperature > 60°C:",
        int((crop_rec["temperature"] > 60).sum())
    )

# Humidity
if "humidity" in crop_rec.columns:

    print(
        "Humidity < 0%:",
        int((crop_rec["humidity"] < 0).sum())
    )

    print(
        "Humidity > 100%:",
        int((crop_rec["humidity"] > 100).sum())
    )

# pH
if "ph" in crop_rec.columns:

    print(
        "pH < 0:",
        int((crop_rec["ph"] < 0).sum())
    )

    print(
        "pH > 14:",
        int((crop_rec["ph"] > 14).sum())
    )

# Rainfall
if "rainfall" in crop_rec.columns:

    print(
        "Negative rainfall:",
        int((crop_rec["rainfall"] < 0).sum())
    )

# ------------------------------------------------------------
# 11. NUMERIC SUMMARY
# ------------------------------------------------------------

print("\nNUMERIC SUMMARY")
print("=" * 60)

available_numeric = [
    col
    for col in numeric_columns
    if col in crop_rec.columns
]

display(
    crop_rec[available_numeric]
    .describe()
    .T
)

# ------------------------------------------------------------
# 12. CROP DISTRIBUTION
# ------------------------------------------------------------

print("\nCROP DISTRIBUTION")
print("=" * 60)

crop_distribution = (
    crop_rec["label"]
    .value_counts()
    .sort_index()
)

display(crop_distribution)

print(
    "\nNumber of crop classes:",
    crop_rec["label"].nunique()
)

# ------------------------------------------------------------
# 13. CROP DISTRIBUTION PERCENTAGE
# ------------------------------------------------------------

crop_percentage = (
    crop_rec["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .sort_index()
)

print("\nCROP DISTRIBUTION (%)")
print("=" * 60)

display(crop_percentage)

# ------------------------------------------------------------
# 14. CHECK CLASS BALANCE
# ------------------------------------------------------------

class_counts = (
    crop_rec["label"]
    .value_counts()
)

print("\nCLASS BALANCE")
print("=" * 60)

print(
    "Minimum records per crop:",
    class_counts.min()
)

print(
    "Maximum records per crop:",
    class_counts.max()
)

print(
    "Mean records per crop:",
    class_counts.mean()
)

# ------------------------------------------------------------
# 15. RANGE BY CROP
# ------------------------------------------------------------

print("\nCROP-WISE FEATURE SUMMARY")
print("=" * 60)

for crop_name in sorted(
    crop_rec["label"].dropna().unique()
):

    subset = crop_rec[
        crop_rec["label"] == crop_name
    ]

    print("\n" + "-" * 60)
    print("CROP:", crop_name)
    print("RECORDS:", len(subset))

    if "N" in subset.columns:
        print(
            "N range:",
            subset["N"].min(),
            "to",
            subset["N"].max()
        )

    if "P" in subset.columns:
        print(
            "P range:",
            subset["P"].min(),
            "to",
            subset["P"].max()
        )

    if "K" in subset.columns:
        print(
            "K range:",
            subset["K"].min(),
            "to",
            subset["K"].max()
        )

    if "temperature" in subset.columns:
        print(
            "Temperature range:",
            subset["temperature"].min(),
            "to",
            subset["temperature"].max()
        )

    if "humidity" in subset.columns:
        print(
            "Humidity range:",
            subset["humidity"].min(),
            "to",
            subset["humidity"].max()
        )

    if "ph" in subset.columns:
        print(
            "pH range:",
            subset["ph"].min(),
            "to",
            subset["ph"].max()
        )

    if "rainfall" in subset.columns:
        print(
            "Rainfall range:",
            subset["rainfall"].min(),
            "to",
            subset["rainfall"].max()
        )

# ------------------------------------------------------------
# 16. SAVE A CLEANED COPY
# ------------------------------------------------------------

clean_file = (
    CLEAN_DIR /
    "Crop_recommendation_cleaned.csv"
)

crop_rec.to_csv(
    clean_file,
    index=False
)

print("\n" + "=" * 60)
print("CLEANED DATASET SAVED")
print("=" * 60)
print(clean_file)

print("\nFINAL SHAPE:")
print(crop_rec.shape)

# ------------------------------------------------------------
# 17. RESEARCH ROLE
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("RESEARCH ROLE")
print("=" * 60)

print(
    """
This dataset is used as the AGRONOMIC CROP-SUITABILITY
COMPONENT of Jalachakra's WATER-AWARE CROP RECOMMENDATION
module.

It is NOT the primary Crop Water Requirement target.

The final water-aware recommendation will combine:

1. Crop suitability
2. Predicted Crop Water Requirement (CWR)
3. Current water availability
4. Crop growth stage
5. Soil context
6. Weather/rainfall conditions
7. Market information
"""
)

# ------------------------------------------------------------
# 18. FINAL CHECK
# ------------------------------------------------------------

print("\nFINAL DATASET CHECK")
print("=" * 60)

print("Rows:", len(crop_rec))
print("Columns:", len(crop_rec.columns))
print("Missing cells:", int(crop_rec.isna().sum().sum()))
print("Duplicate rows:", int(crop_rec.duplicated().sum()))
print("Crop classes:", crop_rec["label"].nunique())

print("\nCrop labels:")
print(
    sorted(
        crop_rec["label"]
        .dropna()
        .unique()
        .tolist()
    )
)

PROJECT ROOT:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro

RAW DATASET
============================================================
File: C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\raw\Crop_recommendation.csv
Shape: (2200, 8)

ORIGINAL COLUMNS:
0 'N'
1 'P'
2 'K'
3 'temperature'
4 'humidity'
5 'ph'
6 'rainfall'
7 'label'

CLEANED COLUMN NAMES:
['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label']

EXPECTED COLUMNS CHECK
============================================================
FOUND     : N
FOUND     : P
FOUND     : K
FOUND     : temperature
FOUND     : humidity
FOUND     : ph
FOUND     : rainfall
FOUND     : label

MISSING VALUE CHECK
============================================================
No missing values found.

DUPLICATE ROWS: 0

PHYSICAL VALIDITY CHECKS
============================================================
Negative N: 0
Negative P: 0
Negative K: 0
Temperature < -20°C: 0
Temperature > 60°C: 0
Humidity < 0%: 0
Humidity > 100%: 0
pH < 0: 0
pH > 14: 0
Negative rainfall: 0

NUMERIC SUMMARY
============================================================

,count,mean,std,min,25%,50%,75%,max
N,2200.0,50.551818,36.917334,0.000000,21.000000,37.000000,84.250000,140.000000
P,2200.0,53.362727,32.985883,5.000000,28.000000,51.000000,68.000000,145.000000
K,2200.0,48.149091,50.647931,5.000000,20.000000,32.000000,49.000000,205.000000
temperature,2200.0,25.616244,5.063749,8.825675,22.769375,25.598693,28.561654,43.675493
humidity,2200.0,71.481779,22.263812,14.258040,60.261953,80.473146,89.948771,99.981876
ph,2200.0,6.469480,0.773938,3.504752,5.971693,6.425045,6.923643,9.935091
rainfall,2200.0,103.463655,54.958389,20.211267,64.551686,94.867624,124.267508,298.560117

CROP DISTRIBUTION
============================================================

label
apple          100
banana         100
blackgram      100
chickpea       100
coconut        100
coffee         100
cotton         100
grapes         100
jute           100
kidneybeans    100
lentil         100
maize          100
mango          100
mothbeans      100
mungbean       100
muskmelon      100
orange         100
papaya         100
pigeonpeas     100
pomegranate    100
rice           100
watermelon     100
Name: count, dtype: Int64

Number of crop classes: 22

CROP DISTRIBUTION (%)
============================================================

label
apple          4.55
banana         4.55
blackgram      4.55
chickpea       4.55
coconut        4.55
coffee         4.55
cotton         4.55
grapes         4.55
jute           4.55
kidneybeans    4.55
lentil         4.55
maize          4.55
mango          4.55
mothbeans      4.55
mungbean       4.55
muskmelon      4.55
orange         4.55
papaya         4.55
pigeonpeas     4.55
pomegranate    4.55
rice           4.55
watermelon     4.55
Name: proportion, dtype: Float64

CLASS BALANCE
============================================================
Minimum records per crop: 100
Maximum records per crop: 100
Mean records per crop: 100.0

CROP-WISE FEATURE SUMMARY
============================================================

------------------------------------------------------------
CROP: apple
RECORDS: 100
N range: 0 to 40
P range: 120 to 145
K range: 195 to 205
Temperature range: 21.0365275 to 23.99686172
Humidity range: 90.02575116 to 94.92048112
pH range: 5.514253142 to 6.4992268210000015
Rainfall range: 100.1173443 to 124.9831618

------------------------------------------------------------
CROP: banana
RECORDS: 100
N range: 80 to 120
P range: 70 to 95
K range: 45 to 55
Temperature range: 25.01018457 to 29.90888522
Humidity range: 75.03193255 to 84.97849241
pH range: 5.505393832999999 to 6.490074429
Rainfall range: 90.10978128 to 119.84797

------------------------------------------------------------
CROP: blackgram
RECORDS: 100
N range: 20 to 60
P range: 55 to 80
K range: 15 to 25
Temperature range: 25.09737391 to 34.9466155
Humidity range: 60.06534859 to 69.96100028
pH range: 6.500144962 to 7.775306272000001
Rainfall range: 60.41790253 to 74.91559514

------------------------------------------------------------
CROP: chickpea
RECORDS: 100
N range: 20 to 60
P range: 55 to 80
K range: 75 to 85
Temperature range: 17.02498456 to 20.99502153
Humidity range: 14.25803981 to 19.96978871
pH range: 5.988992796000002 to 8.868741443
Rainfall range: 65.11365631 to 94.78189594

------------------------------------------------------------
CROP: coconut
RECORDS: 100
N range: 0 to 40
P range: 5 to 30
K range: 25 to 35
Temperature range: 25.00872392 to 29.8690834
Humidity range: 90.01734526 to 99.98187601
pH range: 5.50158009 to 6.470465614
Rainfall range: 131.09000759999998 to 225.6323656

------------------------------------------------------------
CROP: coffee
RECORDS: 100
N range: 80 to 120
P range: 15 to 40
K range: 25 to 35
Temperature range: 23.05951896 to 27.92374437
Humidity range: 50.04557009 to 69.94807345
pH range: 6.020947179 to 7.493191968
Rainfall range: 115.1564012 to 199.4735636

------------------------------------------------------------
CROP: cotton
RECORDS: 100
N range: 100 to 140
P range: 35 to 60
K range: 15 to 25
Temperature range: 22.00085141 to 25.99237426
Humidity range: 75.00539324 to 84.87668973
pH range: 5.801047545 to 7.994679507000001
Rainfall range: 60.65381719 to 99.93100821

------------------------------------------------------------
CROP: grapes
RECORDS: 100
N range: 0 to 40
P range: 120 to 145
K range: 195 to 205
Temperature range: 8.825674745 to 41.94865736
Humidity range: 80.01639435 to 83.98351748
pH range: 5.510924848999999 to 6.499604931
Rainfall range: 65.01095312 to 74.91506217

------------------------------------------------------------
CROP: jute
RECORDS: 100
N range: 60 to 100
P range: 35 to 60
K range: 35 to 45
Temperature range: 23.09433785 to 26.98582182
Humidity range: 70.88259632 to 89.89106506
pH range: 6.002524871 to 7.4880144039999985
Rainfall range: 150.2355238 to 199.83629130000003

------------------------------------------------------------
CROP: kidneybeans
RECORDS: 100
N range: 0 to 40
P range: 55 to 80
K range: 15 to 25
Temperature range: 15.33042636 to 24.92360104
Humidity range: 18.09224048 to 24.96969858
pH range: 5.502999119 to 5.99812453
Rainfall range: 60.27552528 to 149.7441028

------------------------------------------------------------
CROP: lentil
RECORDS: 100
N range: 0 to 40
P range: 55 to 80
K range: 15 to 25
Temperature range: 18.06486101 to 29.94413861
Humidity range: 60.09116626 to 69.92375891
pH range: 5.91645379 to 7.841496029
Rainfall range: 35.03484812 to 54.93937710000001

------------------------------------------------------------
CROP: maize
RECORDS: 100
N range: 60 to 100
P range: 35 to 60
K range: 15 to 25
Temperature range: 18.04185513 to 26.54986394
Humidity range: 55.28220433 to 74.82913698
pH range: 5.513697923 to 6.995843776
Rainfall range: 60.65171481 to 109.7515385

------------------------------------------------------------
CROP: mango
RECORDS: 100
N range: 0 to 40
P range: 15 to 40
K range: 25 to 35
Temperature range: 27.00315545 to 35.99009679
Humidity range: 45.02236377 to 54.9640534
pH range: 4.507523551 to 6.9674177660000005
Rainfall range: 89.29147581 to 100.8124659

------------------------------------------------------------
CROP: mothbeans
RECORDS: 100
N range: 0 to 40
P range: 35 to 60
K range: 15 to 25
Temperature range: 24.01825377 to 31.99928579
Humidity range: 40.00933429 to 64.95585424
pH range: 3.504752314 to 9.93509073
Rainfall range: 30.92014047 to 74.44330654

------------------------------------------------------------
CROP: mungbean
RECORDS: 100
N range: 0 to 40
P range: 35 to 60
K range: 15 to 25
Temperature range: 27.01470397 to 29.914544300000006
Humidity range: 80.03499648 to 89.99615558
pH range: 6.218923893 to 7.199495367999999
Rainfall range: 36.12042927 to 59.87232071

------------------------------------------------------------
CROP: muskmelon
RECORDS: 100
N range: 80 to 120
P range: 5 to 30
K range: 45 to 55
Temperature range: 27.02415146 to 29.94349168
Humidity range: 90.01506395 to 94.96218673
pH range: 6.002927293 to 6.781050372999999
Rainfall range: 20.21126747 to 29.86681385

------------------------------------------------------------
CROP: orange
RECORDS: 100
N range: 0 to 40
P range: 5 to 30
K range: 5 to 15
Temperature range: 10.01081312 to 34.90665289
Humidity range: 90.00621688 to 94.96419851
pH range: 6.010391864 to 7.995848977
Rainfall range: 100.1737964 to 119.6946577

------------------------------------------------------------
CROP: papaya
RECORDS: 100
N range: 31 to 70
P range: 46 to 70
K range: 45 to 55
Temperature range: 23.012401800000006 to 43.67549305
Humidity range: 90.03863107 to 94.94482086
pH range: 6.501521192 to 6.993473247000001
Rainfall range: 40.35153141 to 248.8592986

------------------------------------------------------------
CROP: pigeonpeas
RECORDS: 100
N range: 0 to 40
P range: 55 to 80
K range: 15 to 25
Temperature range: 18.31910448 to 36.97794384
Humidity range: 30.40046769 to 69.69141302
pH range: 4.548202098 to 7.445444882999999
Rainfall range: 90.05422663 to 198.8298806

------------------------------------------------------------
CROP: pomegranate
RECORDS: 100
N range: 0 to 40
P range: 5 to 30
K range: 35 to 45
Temperature range: 18.07132963 to 24.96273236
Humidity range: 85.12912161 to 94.99897537
pH range: 5.561851831 to 7.199504273
Rainfall range: 102.5184759 to 112.4750941

------------------------------------------------------------
CROP: rice
RECORDS: 100
N range: 60 to 99
P range: 35 to 60
K range: 35 to 45
Temperature range: 20.0454142 to 26.92995077
Humidity range: 80.12267476 to 84.96907151
pH range: 5.005306977 to 7.868474653
Rainfall range: 182.5616319 to 298.5601175

------------------------------------------------------------
CROP: watermelon
RECORDS: 100
N range: 80 to 120
P range: 5 to 30
K range: 45 to 55
Temperature range: 24.04355803 to 26.98603693
Humidity range: 80.02621335 to 89.98405233
pH range: 6.000975617000001 to 6.956508826
Rainfall range: 40.12650421 to 59.75980023

============================================================
CLEANED DATASET SAVED
============================================================
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\Crop_recommendation_cleaned.csv

FINAL SHAPE:
(2200, 8)

============================================================
RESEARCH ROLE
============================================================

This dataset is used as the AGRONOMIC CROP-SUITABILITY
COMPONENT of Jalachakra's WATER-AWARE CROP RECOMMENDATION
module.

It is NOT the primary Crop Water Requirement target.

The final water-aware recommendation will combine:

1. Crop suitability
2. Predicted Crop Water Requirement (CWR)
3. Current water availability
4. Crop growth stage
5. Soil context
6. Weather/rainfall conditions
7. Market information


FINAL DATASET CHECK
============================================================
Rows: 2200
Columns: 8
Missing cells: 0
Duplicate rows: 0
Crop classes: 22

Crop labels:
['apple', 'banana', 'blackgram', 'chickpea', 'coconut', 'coffee', 'cotton', 'grapes', 'jute', 'kidneybeans', 'lentil', 'maize', 'mango', 'mothbeans', 'mungbean', 'muskmelon', 'orange', 'papaya', 'pigeonpeas', 'pomegranate', 'rice', 'watermelon']

In [12]:
# ============================================================
# STEP 4I — INVESTIGATE data_season.csv
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"

raw_file = RAW_DIR / "data_season.csv"

season = pd.read_csv(raw_file).copy()

print("=" * 80)
print("DATA_SEASON DATASET INVESTIGATION")
print("=" * 80)

print("\nShape:")
print(season.shape)

print("\nColumns:")
print(list(season.columns))

# ------------------------------------------------------------
# 1. Data types
# ------------------------------------------------------------

print("\nDATA TYPES:")
display(
    pd.DataFrame({
        "column": season.columns,
        "dtype": season.dtypes.astype(str).values,
        "missing": season.isna().sum().values,
        "unique": season.nunique().values
    })
)

# ------------------------------------------------------------
# 2. Missing values
# ------------------------------------------------------------

print("\nMISSING VALUES:")
display(
    season.isna().sum()
)

# ------------------------------------------------------------
# 3. Duplicate rows
# ------------------------------------------------------------

print(
    "\nDuplicate rows:",
    season.duplicated().sum()
)

# ------------------------------------------------------------
# 4. First rows
# ------------------------------------------------------------

print("\nFIRST 10 ROWS:")
display(
    season.head(10)
)

# ------------------------------------------------------------
# 5. Numerical summary
# ------------------------------------------------------------

print("\nNUMERICAL SUMMARY:")
numeric_cols = season.select_dtypes(
    include=np.number
).columns.tolist()

display(
    season[numeric_cols].describe().T
)

# ------------------------------------------------------------
# 6. Temperature investigation
# ------------------------------------------------------------

if "Temperature" in season.columns:

    print("\nTEMPERATURE INVESTIGATION")
    print("-" * 60)

    print(
        "Minimum:",
        season["Temperature"].min()
    )

    print(
        "Maximum:",
        season["Temperature"].max()
    )

    print(
        "Values > 40°C:",
        (season["Temperature"] > 40).sum()
    )

    print(
        "Values > 50°C:",
        (season["Temperature"] > 50).sum()
    )

    print(
        "Values > 100°C:",
        (season["Temperature"] > 100).sum()
    )

    print("\nHighest temperature records:")

    display(
        season[
            [
                "Temperature"
            ] + [
                col for col in [
                    "Year",
                    "Location",
                    "Crops",
                    "Season"
                ]
                if col in season.columns
            ]
        ]
        .sort_values(
            "Temperature",
            ascending=False
        )
        .head(20)
    )

# ------------------------------------------------------------
# 7. Rainfall investigation
# ------------------------------------------------------------

if "Rainfall" in season.columns:

    print("\nRAINFALL SUMMARY:")
    print(
        season["Rainfall"].describe()
    )

# ------------------------------------------------------------
# 8. Irrigation categories
# ------------------------------------------------------------

if "Irrigation" in season.columns:

    print("\nIRRIGATION CATEGORIES:")

    display(
        season["Irrigation"]
        .value_counts(dropna=False)
    )

# ------------------------------------------------------------
# 9. Crop categories
# ------------------------------------------------------------

if "Crops" in season.columns:

    print("\nCROP CATEGORIES:")

    display(
        season["Crops"]
        .value_counts()
        .head(30)
    )

# ------------------------------------------------------------
# 10. Soil type
# ------------------------------------------------------------

if "Soil type" in season.columns:

    print("\nSOIL TYPE CATEGORIES:")

    display(
        season["Soil type"]
        .value_counts(dropna=False)
    )

# ------------------------------------------------------------
# 11. Year coverage
# ------------------------------------------------------------

if "Year" in season.columns:

    print("\nYEAR COVERAGE:")

    print(
        "Minimum year:",
        season["Year"].min()
    )

    print(
        "Maximum year:",
        season["Year"].max()
    )

    display(
        season["Year"]
        .value_counts()
        .sort_index()
    )

# ------------------------------------------------------------
# 12. Location coverage
# ------------------------------------------------------------

if "Location" in season.columns:

    print("\nLOCATION COUNT:")

    print(
        season["Location"].nunique()
    )

    display(
        season["Location"]
        .value_counts()
        .head(30)
    )

================================================================================
DATA_SEASON DATASET INVESTIGATION
================================================================================

Shape:
(3158, 12)

Columns:
['Year', 'Location', 'Area', 'Rainfall', 'Temperature', 'Soil type', 'Irrigation', 'yeilds', 'Humidity', 'Crops', 'price', 'Season']

DATA TYPES:

         column    dtype  missing  unique
0          Year    int64        0      16
1      Location   object        0      11
2          Area    int64        0     156
3      Rainfall  float64        0      21
4   Temperature  float64        0     106
5     Soil type   object       58      27
6    Irrigation   object        0       3
7        yeilds  float64        0     162
8      Humidity  float64        0      19
9         Crops   object        0      13
10        price    int64        0      24
11       Season   object        0       3

MISSING VALUES:

Year            0
Location        0
Area            0
Rainfall        0
Temperature     0
Soil type      58
Irrigation      0
yeilds          0
Humidity        0
Crops           0
price           0
Season          0
dtype: int64

Duplicate rows: 0

FIRST 10 ROWS:

,Year,Location,Area,Rainfall,Temperature,Soil type,Irrigation,yeilds,Humidity,Crops,price,Season
0,2004,Mangalore,1279,2903.1,27.0,Alluvial,Drip,2570.0,57.0,Coconut,200000,Kharif
1,2004,Mangalore,13283,2903.1,27.0,Alluvial,Drip,27170.0,57.5,Coconut,4847,Kharif
2,2004,Mangalore,52119,2903.1,27.0,Alluvial,Drip,114744.0,57.0,Coconut,51239,Kharif
3,2004,Mangalore,725,2996.6,27.0,Alluvial,Drip,1402.0,55.0,Coconut,216396,Kharif
4,2004,Mangalore,12885,2996.6,27.0,Alluvial,Drip,23456.0,56.0,Coconut,2644,Kharif
5,2004,Mangalore,51179,2996.6,27.0,Alluvial,Drip,107809.0,54.0,Coconut,44235,Kharif
6,2004,Mangalore,468,3522.8,27.2,Alluvial,Drip,1132.0,58.0,Coconut,203317,Kharif
7,2004,Mangalore,11841,3522.8,27.2,Alluvial,Drip,23960.0,58.0,Coconut,2134,Kharif
8,2004,Mangalore,50975,3522.8,27.2,Alluvial,Drip,126487.0,59.0,Coconut,45186,Kharif
9,2004,Mangalore,206,3729.8,27.0,Alluvial,Drip,804.0,50.0,Coconut,238542,Kharif

NUMERICAL SUMMARY:

,count,mean,std,min,25%,50%,75%,max
Year,3158.0,2009.929702,5.100895,2004.0,2004.0,2010.0,2015.0,2019.0
Area,3158.0,9329.913553,15180.465396,1.0,153.0,2127.0,10910.0,52119.0
Rainfall,3158.0,2813.126662,1163.829953,233.0,2903.1,3296.0,3550.0,3729.8
Temperature,3158.0,65.893699,60.814037,26.8,27.0,38.0,43.0,222.0
yeilds,3158.0,23258.976916,58228.985033,2.0,393.0,2783.0,6589.0,623687.0
Humidity,3158.0,55.582331,2.469773,50.0,54.0,56.0,57.0,60.0
price,3158.0,86271.279291,94123.160706,637.0,2644.0,45186.0,203317.0,249978.0

TEMPERATURE INVESTIGATION
------------------------------------------------------------
Minimum: 26.8
Maximum: 222.0
Values > 40°C: 1156
Values > 50°C: 767
Values > 100°C: 767

Highest temperature records:

      Temperature  Year       Location    Crops  Season
3144        222.0  2004      Davangere   Cashew    Zaid
538         222.0  2004       Madikeri      Tea  Kharif
2317        222.0  2005       Gulbarga  Coconut    Rabi
2004        222.0  2013        Raichur  Coconut    Rabi
1286        222.0  2011       Madikeri  Coconut    Rabi
1645        222.0  2004  Chikmangaluru  Coconut    Zaid
225         222.0  2017         Hassan      Tea  Kharif
2316        221.0  2004       Gulbarga  Coconut    Rabi
1644        221.0  2004  Chikmangaluru  Coconut    Zaid
1285        221.0  2010       Madikeri  Coconut    Rabi
2003        221.0  2012        Raichur  Coconut    Rabi
224         221.0  2016         Hassan      Tea  Kharif
3143        221.0  2018      Davangere   Cashew    Zaid
537         221.0  2004       Madikeri      Tea  Kharif
536         220.0  2004       Madikeri      Tea  Kharif
223         220.0  2015         Hassan      Tea  Kharif
2315        220.0  2018       Gulbarga  Coconut    Rabi
2002        220.0  2011        Raichur  Coconut    Rabi
1284        220.0  2009       Madikeri  Coconut    Rabi
3142        220.0  2017      Davangere   Cashew    Zaid

RAINFALL SUMMARY:
count    3158.000000
mean     2813.126662
std      1163.829953
min       233.000000
25%      2903.100000
50%      3296.000000
75%      3550.000000
max      3729.800000
Name: Rainfall, dtype: float64

IRRIGATION CATEGORIES:

Irrigation
Drip     1310
Basin     968
Spray     880
Name: count, dtype: int64

CROP CATEGORIES:

Crops
Coconut      1458
Ginger        281
Coffee        150
Arecanut      150
Cardamum      150
Blackgram     150
Paddy         150
Tea           150
Pepper        146
Cashew        146
Groundnut     146
Cocoa          60
Cotton         21
Name: count, dtype: int64

SOIL TYPE CATEGORIES:

Soil type
Alluvial                459
Loam                    281
Laterite                281
Sandy loam              265
Black                   259
Sandy loam              216
Clay loam               196
Sandy                   189
Red                     170
Clay                    105
Dry sandy               100
Drained loam             85
Arid and Desert          66
Red                      64
NaN                      58
Gravelly sand            40
Heavy clay               40
Well drained             39
Heavy cotton             30
River basins             30
loamy sand               29
Light sandy              29
Red laterite             25
Black cotton             25
Sandy clay loam          25
Medium textured          21
Medium textured clay     20
Teelah                   11
Name: count, dtype: int64

YEAR COVERAGE:
Minimum year: 2004
Maximum year: 2019

Year
2004    914
2005    132
2006    126
2007    126
2008    126
2009    126
2010    126
2011    132
2012    144
2013    186
2014    186
2015    192
2016    216
2017    222
2018    186
2019     18
Name: count, dtype: int64

LOCATION COUNT:
11

Location
Hassan           798
Gulbarga         504
Mangalore        342
Chikmangaluru    340
Madikeri         240
Raichur          231
Kasaragodu       231
Mysuru           222
Kodagu           192
Davangere         42
Bangalore         16
Name: count, dtype: int64

In [13]:
# STEP 4I — TEMPERATURE ANOMALY AUDIT FOR data_season.csv

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_FILE = PROJECT_ROOT / "datasets" / "raw" / "data_season.csv"

season = pd.read_csv(RAW_FILE).copy()

print("=" * 80)
print("DATA_SEASON TEMPERATURE ANOMALY AUDIT")
print("=" * 80)

# ---------------------------------------------------------
# 1. TEMPERATURE VALUE DISTRIBUTION
# ---------------------------------------------------------

print("\n1. Most common temperature values")
print("-" * 60)

display(
    season["Temperature"]
    .value_counts()
    .sort_index()
    .tail(40)
)

# ---------------------------------------------------------
# 2. SUSPICIOUS TEMPERATURE RECORDS
# ---------------------------------------------------------

suspicious = season[season["Temperature"] > 40].copy()

print("\n2. Suspicious records: Temperature > 40°C")
print("-" * 60)

print("Number of suspicious records:", len(suspicious))

display(
    suspicious[
        [
            "Year",
            "Location",
            "Crops",
            "Season",
            "Temperature",
            "Rainfall",
            "Humidity",
            "Soil type",
            "Irrigation"
        ]
    ]
    .sort_values("Temperature", ascending=False)
    .head(30)
)

# ---------------------------------------------------------
# 3. VERY HIGH TEMPERATURES
# ---------------------------------------------------------

very_high = season[season["Temperature"] > 100].copy()

print("\n3. Records with Temperature > 100")
print("-" * 60)

print("Count:", len(very_high))

display(
    very_high[
        [
            "Year",
            "Location",
            "Crops",
            "Season",
            "Temperature",
            "Rainfall",
            "Humidity"
        ]
    ]
    .sort_values("Temperature", ascending=False)
    .head(30)
)

# ---------------------------------------------------------
# 4. CHECK WHETHER THE VALUES ARE REPEATED
# ---------------------------------------------------------

print("\n4. Repeated anomalous temperature values")
print("-" * 60)

anomaly_counts = (
    season.loc[season["Temperature"] > 40, "Temperature"]
    .value_counts()
    .sort_index(ascending=False)
)

display(anomaly_counts.head(30))

# ---------------------------------------------------------
# 5. CHECK TEMPERATURE BY LOCATION
# ---------------------------------------------------------

print("\n5. Temperature anomaly count by location")
print("-" * 60)

location_anomalies = (
    season.assign(
        Temperature_Anomaly=season["Temperature"] > 40
    )
    .groupby("Location")["Temperature_Anomaly"]
    .agg(["sum", "count"])
    .rename(
        columns={
            "sum": "anomaly_count",
            "count": "total_records"
        }
    )
)

location_anomalies["anomaly_percent"] = (
    location_anomalies["anomaly_count"]
    / location_anomalies["total_records"]
    * 100
)

display(
    location_anomalies
    .sort_values("anomaly_count", ascending=False)
)

# ---------------------------------------------------------
# 6. CHECK TEMPERATURE BY CROP
# ---------------------------------------------------------

print("\n6. Temperature anomaly count by crop")
print("-" * 60)

crop_anomalies = (
    season.assign(
        Temperature_Anomaly=season["Temperature"] > 40
    )
    .groupby("Crops")["Temperature_Anomaly"]
    .agg(["sum", "count"])
    .rename(
        columns={
            "sum": "anomaly_count",
            "count": "total_records"
        }
    )
)

crop_anomalies["anomaly_percent"] = (
    crop_anomalies["anomaly_count"]
    / crop_anomalies["total_records"]
    * 100
)

display(
    crop_anomalies
    .sort_values("anomaly_count", ascending=False)
)

# ---------------------------------------------------------
# 7. CHECK WHETHER DIVIDING BY 10 WOULD LOOK PLAUSIBLE
#    THIS IS ONLY AN AUDIT — DO NOT MODIFY DATA
# ---------------------------------------------------------

print("\n7. Hypothetical /10 audit")
print("-" * 60)

test_values = suspicious["Temperature"].copy() / 10

print("If /10 was applied:")
print("Minimum:", test_values.min())
print("Maximum:", test_values.max())
print("Median :", test_values.median())
print("Mean   :", test_values.mean())

display(
    pd.DataFrame({
        "original_temperature": suspicious["Temperature"].head(30).values,
        "hypothetical_div10": test_values.head(30).values
    })
)

print("\nIMPORTANT:")
print("The /10 transformation is NOT being applied.")
print("This cell only checks whether such a transformation looks plausible.")

================================================================================
DATA_SEASON TEMPERATURE ANOMALY AUDIT
================================================================================

1. Most common temperature values
------------------------------------------------------------

Temperature
183.0    7
184.0    7
185.0    7
186.0    7
187.0    7
188.0    7
189.0    7
190.0    7
191.0    7
192.0    7
193.0    7
194.0    7
195.0    7
196.0    7
197.0    7
198.0    7
199.0    7
200.0    7
201.0    7
202.0    7
203.0    7
204.0    7
205.0    7
206.0    7
207.0    7
208.0    7
209.0    7
210.0    7
211.0    7
212.0    7
213.0    7
214.0    7
215.0    7
216.0    7
217.0    7
218.0    7
219.0    7
220.0    7
221.0    7
222.0    7
Name: count, dtype: int64

2. Suspicious records: Temperature > 40°C
------------------------------------------------------------
Number of suspicious records: 1156

,Year,Location,Crops,Season,Temperature,Rainfall,Humidity,Soil type,Irrigation
1286,2011,Madikeri,Coconut,Rabi,222.0,234.0,57.0,Loam,Drip
1645,2004,Chikmangaluru,Coconut,Zaid,222.0,2996.6,55.0,Dry sandy,Basin
538,2004,Madikeri,Tea,Kharif,222.0,3296.0,54.0,loamy sand,Spray
2317,2005,Gulbarga,Coconut,Rabi,222.0,3105.0,57.5,Sandy loam,Spray
225,2017,Hassan,Tea,Kharif,222.0,233.0,57.0,Red laterite,Spray
3144,2004,Davangere,Cashew,Zaid,222.0,3360.0,58.0,NaN,Drip
2004,2013,Raichur,Coconut,Rabi,222.0,2996.6,58.0,Sandy loam,Spray
1285,2010,Madikeri,Coconut,Rabi,221.0,233.0,51.0,Loam,Drip
2316,2004,Gulbarga,Coconut,Rabi,221.0,3105.0,57.0,Sandy loam,Spray
2003,2012,Raichur,Coconut,Rabi,221.0,2903.1,54.0,Sandy loam,Spray
3143,2018,Davangere,Cashew,Zaid,221.0,3360.0,54.0,NaN,Drip
224,2016,Hassan,Tea,Kharif,221.0,3654.0,57.0,Sandy loam,Spray
1644,2004,Chikmangaluru,Coconut,Zaid,221.0,2996.6,59.5,Dry sandy,Basin
537,2004,Madikeri,Tea,Kharif,221.0,3512.4,50.0,loamy sand,Spray
2002,2011,Raichur,Coconut,Rabi,220.0,2903.1,56.0,Sandy loam,Spray
2315,2018,Gulbarga,Coconut,Rabi,220.0,3105.0,56.0,Sandy loam,Spray
536,2004,Madikeri,Tea,Kharif,220.0,3512.4,59.0,loamy sand,Spray
3142,2017,Davangere,Cashew,Zaid,220.0,2746.2,56.0,NaN,Drip
1284,2009,Madikeri,Coconut,Rabi,220.0,233.0,52.0,Loam,Drip
1643,2004,Madikeri,Coconut,Zaid,220.0,2996.6,58.5,Dry sandy,Basin
223,2015,Hassan,Tea,Kharif,220.0,3654.0,51.0,Sandy loam,Spray
1283,2008,Madikeri,Coconut,Rabi,219.0,233.0,53.0,Loam,Drip
535,2004,Madikeri,Tea,Kharif,219.0,3512.4,58.0,loamy sand,Basin
1642,2004,Madikeri,Coconut,Zaid,219.0,2903.1,55.5,Dry sandy,Basin
222,2014,Hassan,Tea,Kharif,219.0,3654.0,52.0,Sandy loam,Spray
3141,2016,Davangere,Cashew,Zaid,219.0,2746.2,55.0,NaN,Drip
2001,2010,Raichur,Coconut,Rabi,219.0,2903.1,55.0,Sandy loam,Spray
2314,2017,Gulbarga,Coconut,Rabi,219.0,234.0,52.5,Sandy loam,Spray
3140,2015,Davangere,Cashew,Zaid,218.0,2746.2,57.0,NaN,Drip
221,2013,Hassan,Tea,Kharif,218.0,3550.0,53.0,Sandy loam,Spray

3. Records with Temperature > 100
------------------------------------------------------------
Count: 767

      Year       Location    Crops  Season  Temperature  Rainfall  Humidity
1286  2011       Madikeri  Coconut    Rabi        222.0     234.0      57.0
1645  2004  Chikmangaluru  Coconut    Zaid        222.0    2996.6      55.0
2004  2013        Raichur  Coconut    Rabi        222.0    2996.6      58.0
2317  2005       Gulbarga  Coconut    Rabi        222.0    3105.0      57.5
3144  2004      Davangere   Cashew    Zaid        222.0    3360.0      58.0
225   2017         Hassan      Tea  Kharif        222.0     233.0      57.0
538   2004       Madikeri      Tea  Kharif        222.0    3296.0      54.0
2316  2004       Gulbarga  Coconut    Rabi        221.0    3105.0      57.0
537   2004       Madikeri      Tea  Kharif        221.0    3512.4      50.0
1285  2010       Madikeri  Coconut    Rabi        221.0     233.0      51.0
2003  2012        Raichur  Coconut    Rabi        221.0    2903.1      54.0
1644  2004  Chikmangaluru  Coconut    Zaid        221.0    2996.6      59.5
3143  2018      Davangere   Cashew    Zaid        221.0    3360.0      54.0
224   2016         Hassan      Tea  Kharif        221.0    3654.0      57.0
223   2015         Hassan      Tea  Kharif        220.0    3654.0      51.0
2002  2011        Raichur  Coconut    Rabi        220.0    2903.1      56.0
1643  2004       Madikeri  Coconut    Zaid        220.0    2996.6      58.5
1284  2009       Madikeri  Coconut    Rabi        220.0     233.0      52.0
3142  2017      Davangere   Cashew    Zaid        220.0    2746.2      56.0
2315  2018       Gulbarga  Coconut    Rabi        220.0    3105.0      56.0
536   2004       Madikeri      Tea  Kharif        220.0    3512.4      59.0
3141  2016      Davangere   Cashew    Zaid        219.0    2746.2      55.0
1642  2004       Madikeri  Coconut    Zaid        219.0    2903.1      55.5
1283  2008       Madikeri  Coconut    Rabi        219.0     233.0      53.0
222   2014         Hassan      Tea  Kharif        219.0    3654.0      52.0
2001  2010        Raichur  Coconut    Rabi        219.0    2903.1      55.0
2314  2017       Gulbarga  Coconut    Rabi        219.0     234.0      52.5
535   2004       Madikeri      Tea  Kharif        219.0    3512.4      58.0
1282  2007       Madikeri  Coconut    Rabi        218.0    3654.0      54.0
1641  2004       Madikeri  Coconut    Zaid        218.0    2903.1      56.6

4. Repeated anomalous temperature values
------------------------------------------------------------

Temperature
222.0    7
221.0    7
220.0    7
219.0    7
218.0    7
217.0    7
216.0    7
215.0    7
214.0    7
213.0    7
212.0    7
211.0    7
210.0    7
209.0    7
208.0    7
207.0    7
206.0    7
205.0    7
204.0    7
203.0    7
202.0    7
201.0    7
200.0    7
199.0    7
198.0    7
197.0    7
196.0    7
195.0    7
194.0    7
193.0    7
Name: count, dtype: int64

5. Temperature anomaly count by location
------------------------------------------------------------

               anomaly_count  total_records  anomaly_percent
Location
Gulbarga                 308            504        61.111111
Hassan                   179            798        22.431078
Raichur                  166            231        71.861472
Madikeri                 122            240        50.833333
Kasaragodu               107            231        46.320346
Mangalore                 76            342        22.222222
Kodagu                    58            192        30.208333
Mysuru                    51            222        22.972973
Chikmangaluru             44            340        12.941176
Davangere                 29             42        69.047619
Bangalore                 16             16       100.000000

6. Temperature anomaly count by crop
------------------------------------------------------------

           anomaly_count  total_records  anomaly_percent
Crops
Coconut              496           1458        34.019204
Ginger               126            281        44.839858
Arecanut              74            150        49.333333
Blackgram             69            150        46.000000
Cashew                69            146        47.260274
Coffee                69            150        46.000000
Paddy                 52            150        34.666667
Tea                   48            150        32.000000
Groundnut             43            146        29.452055
Pepper                40            146        27.397260
Cardamum              32            150        21.333333
Cocoa                 29             60        48.333333
Cotton                 9             21        42.857143

7. Hypothetical /10 audit
------------------------------------------------------------
If /10 was applied:
Minimum: 4.1
Maximum: 22.2
Median : 14.2
Mean   : 12.67439446366782

    original_temperature  hypothetical_div10
0                   41.0                 4.1
1                   41.0                 4.1
2                   41.0                 4.1
3                   42.0                 4.2
4                   42.0                 4.2
5                   42.0                 4.2
6                   43.0                 4.3
7                   43.0                 4.3
8                   41.0                 4.1
9                   41.0                 4.1
10                  41.0                 4.1
11                  42.0                 4.2
12                  42.0                 4.2
13                  42.0                 4.2
14                  43.0                 4.3
15                  41.0                 4.1
16                  41.0                 4.1
17                  41.0                 4.1
18                  42.0                 4.2
19                  42.0                 4.2
20                  42.0                 4.2
21                  43.0                 4.3
22                  43.0                 4.3
23                 128.0                12.8
24                 129.0                12.9
25                 130.0                13.0
26                 131.0                13.1
27                 132.0                13.2
28                 133.0                13.3
29                 134.0                13.4

IMPORTANT:
The /10 transformation is NOT being applied.
This cell only checks whether such a transformation looks plausible.

In [15]:
# STEP 4J — ROBUST CLEANING OF data_season.csv
# Handles hidden spaces / column-name differences safely.

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_FILE = PROJECT_ROOT / "datasets" / "raw" / "data_season.csv"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------
# 1. LOAD DATA
# ---------------------------------------------------------

season = pd.read_csv(RAW_FILE).copy()

# ---------------------------------------------------------
# 2. CLEAN COLUMN NAMES
# ---------------------------------------------------------

season.columns = (
    season.columns
    .astype(str)
    .str.strip()
    .str.replace("\ufeff", "", regex=False)
)

print("Actual columns found:")
print(list(season.columns))

# ---------------------------------------------------------
# 3. RENAME COMMON VARIANTS
# ---------------------------------------------------------

rename_map = {}

for col in season.columns:
    normalized = (
        col.lower()
        .strip()
        .replace(" ", "_")
        .replace("-", "_")
    )

    if normalized in ["yield", "yields"]:
        rename_map[col] = "yields"

    elif normalized == "price":
        rename_map[col] = "price"

    elif normalized == "crop":
        rename_map[col] = "Crops"

    elif normalized == "soil_type":
        rename_map[col] = "Soil type"

    elif normalized == "year":
        rename_map[col] = "Year"

    elif normalized == "location":
        rename_map[col] = "Location"

    elif normalized == "area":
        rename_map[col] = "Area"

    elif normalized == "rainfall":
        rename_map[col] = "Rainfall"

    elif normalized == "temperature":
        rename_map[col] = "Temperature"

    elif normalized == "irrigation":
        rename_map[col] = "Irrigation"

    elif normalized == "humidity":
        rename_map[col] = "Humidity"

    elif normalized == "season":
        rename_map[col] = "Season"

season = season.rename(columns=rename_map)

print("\nColumns after standardization:")
print(list(season.columns))

# ---------------------------------------------------------
# 4. CHECK REQUIRED SUPPORTING COLUMNS
# ---------------------------------------------------------

possible_columns = [
    "Year",
    "Location",
    "Area",
    "Rainfall",
    "Soil type",
    "Irrigation",
    "yields",
    "Humidity",
    "Crops",
    "price",
    "Season"
]

available_columns = [
    col for col in possible_columns
    if col in season.columns
]

missing_columns = [
    col for col in possible_columns
    if col not in season.columns
]

print("\nAvailable supporting columns:")
print(available_columns)

print("\nMissing supporting columns:")
print(missing_columns)

# ---------------------------------------------------------
# 5. SELECT ONLY AVAILABLE COLUMNS
# ---------------------------------------------------------

support = season[available_columns].copy()

# ---------------------------------------------------------
# 6. CLEAN TEXT COLUMNS
# ---------------------------------------------------------

text_columns = [
    "Location",
    "Soil type",
    "Irrigation",
    "Crops",
    "Season"
]

for col in text_columns:
    if col in support.columns:
        support[col] = (
            support[col]
            .astype("string")
            .str.strip()
        )

# ---------------------------------------------------------
# 7. CLEAN NUMERIC COLUMNS
# ---------------------------------------------------------

numeric_columns = [
    "Year",
    "Area",
    "Rainfall",
    "yields",
    "Humidity",
    "price"
]

for col in numeric_columns:
    if col in support.columns:
        support[col] = pd.to_numeric(
            support[col],
            errors="coerce"
        )

# ---------------------------------------------------------
# 8. QUALITY CHECK
# ---------------------------------------------------------

print("\n" + "=" * 80)
print("SUPPORTING DATASET QUALITY CHECK")
print("=" * 80)

print("\nShape:")
print(support.shape)

print("\nMissing values:")
display(support.isna().sum())

print("\nDuplicate rows:")
print(support.duplicated().sum())

# ---------------------------------------------------------
# 9. NEGATIVE NUMERIC VALUES
# ---------------------------------------------------------

print("\nNegative-value check:")
print("-" * 60)

for col in numeric_columns:
    if col in support.columns:
        print(
            f"{col}: {(support[col] < 0).sum()}"
        )

# ---------------------------------------------------------
# 10. DISTRIBUTIONS
# ---------------------------------------------------------

if "Crops" in support.columns:
    print("\nCrop distribution:")
    display(support["Crops"].value_counts())

if "Location" in support.columns:
    print("\nLocation distribution:")
    display(support["Location"].value_counts())

if "Irrigation" in support.columns:
    print("\nIrrigation distribution:")
    display(support["Irrigation"].value_counts())

if "Season" in support.columns:
    print("\nSeason distribution:")
    display(support["Season"].value_counts())

# ---------------------------------------------------------
# 11. SAVE
# ---------------------------------------------------------

output_file = (
    CLEAN_DIR /
    "data_season_supporting_cleaned.csv"
)

support.to_csv(
    output_file,
    index=False
)

print("\n" + "=" * 80)
print("SUCCESS")
print("=" * 80)

print("\nSaved file:")
print(output_file)

print("\nScientific role:")
print(
    "Supporting agricultural / market-context dataset only."
)

print(
    "NOT used as the primary CWR ground-truth dataset."
)

print(
    "The problematic Temperature column is intentionally excluded."
)

print(
    "Raw data_season.csv remains unchanged."
)

Actual columns found:
['Year', 'Location', 'Area', 'Rainfall', 'Temperature', 'Soil type', 'Irrigation', 'yeilds', 'Humidity', 'Crops', 'price', 'Season']

Columns after standardization:
['Year', 'Location', 'Area', 'Rainfall', 'Temperature', 'Soil type', 'Irrigation', 'yeilds', 'Humidity', 'Crops', 'price', 'Season']

Available supporting columns:
['Year', 'Location', 'Area', 'Rainfall', 'Soil type', 'Irrigation', 'Humidity', 'Crops', 'price', 'Season']

Missing supporting columns:
['yields']

================================================================================
SUPPORTING DATASET QUALITY CHECK
================================================================================

Shape:
(3158, 10)

Missing values:

Year           0
Location       0
Area           0
Rainfall       0
Soil type     58
Irrigation     0
Humidity       0
Crops          0
price          0
Season         0
dtype: int64

Duplicate rows:
0

Negative-value check:
------------------------------------------------------------
Year: 0
Area: 0
Rainfall: 0
Humidity: 0
price: 0

Crop distribution:

Crops
Coconut      1458
Ginger        281
Coffee        150
Arecanut      150
Cardamum      150
Blackgram     150
Paddy         150
Tea           150
Pepper        146
Cashew        146
Groundnut     146
Cocoa          60
Cotton         21
Name: count, dtype: Int64

Location distribution:

Location
Hassan           798
Gulbarga         504
Mangalore        342
Chikmangaluru    340
Madikeri         240
Raichur          231
Kasaragodu       231
Mysuru           222
Kodagu           192
Davangere         42
Bangalore         16
Name: count, dtype: Int64

Irrigation distribution:

Irrigation
Drip     1310
Basin     968
Spray     880
Name: count, dtype: Int64

Season distribution:

Season
Rabi      1742
Zaid       809
Kharif     607
Name: count, dtype: Int64

================================================================================
SUCCESS
================================================================================

Saved file:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\data_season_supporting_cleaned.csv

Scientific role:
Supporting agricultural / market-context dataset only.
NOT used as the primary CWR ground-truth dataset.
The problematic Temperature column is intentionally excluded.
Raw data_season.csv remains unchanged.

In [1]:
# STEP 4K — FINAL CLEANED DATASET INVENTORY

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

print("=" * 100)
print("JALACHAKRA — FINAL CLEANED DATASET INVENTORY")
print("=" * 100)

files = sorted(CLEAN_DIR.glob("*"))

records = []

for file in files:

    if file.suffix.lower() not in [".csv", ".xlsx"]:
        continue

    try:

        if file.suffix.lower() == ".csv":
            df = pd.read_csv(file)
        else:
            df = pd.read_excel(file)

        records.append({
            "Dataset": file.name,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
            "Missing Cells": int(df.isna().sum().sum()),
            "Duplicate Rows": int(df.duplicated().sum())
        })

    except Exception as e:

        records.append({
            "Dataset": file.name,
            "Rows": "ERROR",
            "Columns": "ERROR",
            "Missing Cells": "ERROR",
            "Duplicate Rows": str(e)
        })

inventory = pd.DataFrame(records)

display(inventory)

print("\n" + "=" * 100)
print("CLEANED DATASET FILES")
print("=" * 100)

for file in sorted(CLEAN_DIR.iterdir()):
    print(file.name)

print("\n" + "=" * 100)
print("TOTAL CLEANED DATASETS:", len(inventory))
print("=" * 100)

====================================================================================================
JALACHAKRA — FINAL CLEANED DATASET INVENTORY
====================================================================================================

,Dataset,Rows,Columns,Missing Cells,Duplicate Rows
0,Climate_Data_cleaned.csv,2557,11,1,0
1,Crop_Calender_cleaned.csv,25,9,30,0
2,Crop_recommendation_cleaned.csv,2200,8,0,0
3,crop_water_data_cleaned.csv,10000,14,0,0
4,data_season_supporting_cleaned.csv,3158,10,58,0
5,Karnataka_Crop_Growth_Stage_Reference_cleaned.csv,13,7,0,0
6,Rainfall_2016_districtwise_cleaned.csv,30,7,0,0
7,Soil_data_cleaned.csv,875,5,0,0

====================================================================================================
CLEANED DATASET FILES
====================================================================================================
Climate_Data_cleaned.csv
Crop_Calender_cleaned.csv
Crop_recommendation_cleaned.csv
crop_water_data_cleaned.csv
data_season_supporting_cleaned.csv
Karnataka_Crop_Growth_Stage_Reference_cleaned.csv
Rainfall_2016_districtwise_cleaned.csv
Soil_data_cleaned.csv

====================================================================================================
TOTAL CLEANED DATASETS: 8
====================================================================================================

In [2]:
# STEP 5A — DEFINE JALACHAKRA CWR MASTER DATA STRUCTURE

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

print("=" * 90)
print("JALACHAKRA — SCIENTIFIC CWR MASTER DATA STRUCTURE")
print("=" * 90)

master_structure = pd.DataFrame([
    ["date", "Time", "Daily observation date"],
    ["location", "Spatial", "Farm/district/location identifier"],
    ["crop", "Crop", "Crop being cultivated"],
    ["growth_stage", "Agronomy", "Crop developmental stage"],
    ["crop_age_days", "Agronomy", "Age of crop in days"],
    ["kc", "Agronomy", "Crop coefficient"],
    ["temperature", "Weather", "Air temperature"],
    ["humidity", "Weather", "Relative humidity"],
    ["wind_speed", "Weather", "Wind speed"],
    ["solar_radiation", "Weather", "Solar radiation"],
    ["rainfall", "Weather", "Rainfall"],
    ["soil_type", "Soil", "Soil classification"],
    ["soil_moisture", "Soil", "Soil moisture information"],
    ["field_area_ha", "Farm", "Farm area in hectares"],
    ["irrigation_method", "Irrigation", "Drip/basin/spray etc."],
    ["et0", "Physics", "Reference evapotranspiration"],
    ["kc_dynamic", "Physics", "Growth-stage-adjusted Kc"],
    ["etc", "Physics", "Crop evapotranspiration"],
    ["effective_rainfall", "Physics", "Usable rainfall contribution"],
    ["cwr_baseline", "Physics", "FAO/reference crop water requirement"],
    ["ml_cwr_target", "ML Target", "Research prediction target"],
    ["uncertainty_lower", "Uncertainty", "Lower prediction bound"],
    ["uncertainty_upper", "Uncertainty", "Upper prediction bound"],
    ["irrigation_requirement", "Decision", "Water required after rainfall/soil balance"],
])

master_structure.columns = [
    "Feature",
    "Category",
    "Scientific_Description"
]

display(master_structure)

print("\nTotal planned master variables:")
print(len(master_structure))

print("\nCategories:")
display(
    master_structure["Category"]
    .value_counts()
)

# ---------------------------------------------------------
# SAVE MASTER STRUCTURE
# ---------------------------------------------------------

output_file = (
    CLEAN_DIR /
    "CWR_master_data_dictionary.csv"
)

master_structure.to_csv(
    output_file,
    index=False
)

print("\nSaved:")
print(output_file)

==========================================================================================
JALACHAKRA — SCIENTIFIC CWR MASTER DATA STRUCTURE
==========================================================================================

,Feature,Category,Scientific_Description
0,date,Time,Daily observation date
1,location,Spatial,Farm/district/location identifier
2,crop,Crop,Crop being cultivated
3,growth_stage,Agronomy,Crop developmental stage
4,crop_age_days,Agronomy,Age of crop in days
5,kc,Agronomy,Crop coefficient
6,temperature,Weather,Air temperature
7,humidity,Weather,Relative humidity
8,wind_speed,Weather,Wind speed
9,solar_radiation,Weather,Solar radiation
10,rainfall,Weather,Rainfall
11,soil_type,Soil,Soil classification
12,soil_moisture,Soil,Soil moisture information
13,field_area_ha,Farm,Farm area in hectares
14,irrigation_method,Irrigation,Drip/basin/spray etc.
15,et0,Physics,Reference evapotranspiration
16,kc_dynamic,Physics,Growth-stage-adjusted Kc
17,etc,Physics,Crop evapotranspiration
18,effective_rainfall,Physics,Usable rainfall contribution
19,cwr_baseline,Physics,FAO/reference crop water requirement
20,ml_cwr_target,ML Target,Research prediction target
21,uncertainty_lower,Uncertainty,Lower prediction bound
22,uncertainty_upper,Uncertainty,Upper prediction bound
23,irrigation_requirement,Decision,Water required after rainfall/soil balance

Total planned master variables:
24

Categories:

Category
Physics        5
Weather        5
Agronomy       3
Uncertainty    2
Soil           2
Crop           1
Time           1
Spatial        1
Irrigation     1
Farm           1
ML Target      1
Decision       1
Name: count, dtype: int64

Saved:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\CWR_master_data_dictionary.csv

In [3]:
# STEP 5B — MAP CWR MASTER VARIABLES TO SOURCE DATASETS

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

print("=" * 100)
print("JALACHAKRA — CWR MASTER VARIABLE → DATASET SOURCE MAPPING")
print("=" * 100)

source_mapping = pd.DataFrame([
    ["date", "Climate_Data_cleaned.csv", "datetime", "Direct", "Available"],
    ["location", "Not yet established", "—", "Requires spatial linkage", "Needs resolution"],
    ["crop", "crop_water_data_cleaned.csv / Crop_Calender_cleaned.csv", "crop_type / Crop", "Direct/reference", "Available"],
    ["growth_stage", "crop_water_data_cleaned.csv / Karnataka_Crop_Growth_Stage_Reference_cleaned.csv", "growth_stage / growth stage", "Direct/reference", "Available"],
    ["crop_age_days", "crop_water_data_cleaned.csv", "crop_age_days", "Direct", "Available"],
    ["kc", "Karnataka_Crop_Growth_Stage_Reference_cleaned.csv / Crop_Calender_cleaned.csv", "Kc reference / Kc (Crop Coefficient)", "Reference", "Available with gaps"],
    ["temperature", "Climate_Data_cleaned.csv", "T2M", "Direct", "Available"],
    ["humidity", "Climate_Data_cleaned.csv", "RH2M", "Direct", "Available"],
    ["wind_speed", "Climate_Data_cleaned.csv", "WS2M", "Direct", "Available"],
    ["solar_radiation", "Climate_Data_cleaned.csv", "ALLSKY_SFC_SW_DWN", "Direct", "Available with 1 missing"],
    ["rainfall", "Climate_Data_cleaned.csv", "PRECTOTCORR", "Direct", "Available"],
    ["soil_type", "Soil_data_cleaned.csv / crop_water_data_cleaned.csv", "Soil type / soil_type", "Direct/supporting", "Available"],
    ["soil_moisture", "crop_water_data_cleaned.csv", "soil_moisture_pct", "Direct", "Available"],
    ["field_area_ha", "crop_water_data_cleaned.csv", "field_area_ha", "Direct", "Available"],
    ["irrigation_method", "crop_water_data_cleaned.csv", "irrigation_method", "Direct", "Available"],
    ["et0", "Derived from weather", "T2M/RH2M/WS2M/solar/radiation", "Derived", "To calculate"],
    ["kc_dynamic", "Karnataka growth reference + crop age/GDD", "Kc + growth stage", "Derived", "To calculate"],
    ["etc", "Derived", "ET0 × Kc", "Derived", "To calculate"],
    ["effective_rainfall", "Derived/reference", "Rainfall", "Derived", "To calculate"],
    ["cwr_baseline", "Derived", "ETc + agronomic assumptions", "Derived", "To calculate"],
    ["ml_cwr_target", "Not independently observed yet", "—", "Research target", "Needs decision"],
    ["uncertainty_lower", "ML model output", "—", "Model-derived", "Future stage"],
    ["uncertainty_upper", "ML model output", "—", "Model-derived", "Future stage"],
    ["irrigation_requirement", "Derived", "CWR + rainfall + soil balance + efficiency", "Derived", "Future stage"],
])

source_mapping.columns = [
    "Master_Feature",
    "Source_Dataset",
    "Source_Column_or_Basis",
    "Source_Type",
    "Status"
]

display(source_mapping)

# ---------------------------------------------------------
# SUMMARY
# ---------------------------------------------------------

print("\n" + "=" * 100)
print("STATUS SUMMARY")
print("=" * 100)

display(
    source_mapping["Status"]
    .value_counts()
)

print("\nSource type summary:")
display(
    source_mapping["Source_Type"]
    .value_counts()
)

# ---------------------------------------------------------
# SHOW VARIABLES THAT STILL NEED SCIENTIFIC RESOLUTION
# ---------------------------------------------------------

print("\n" + "=" * 100)
print("VARIABLES REQUIRING SPECIAL ATTENTION")
print("=" * 100)

attention = source_mapping[
    source_mapping["Status"].isin([
        "Needs resolution",
        "Needs decision",
        "Available with gaps",
        "To calculate",
        "Future stage"
    ])
]

display(attention)

# ---------------------------------------------------------
# SAVE MAPPING
# ---------------------------------------------------------

output_file = (
    CLEAN_DIR /
    "CWR_master_source_mapping.csv"
)

source_mapping.to_csv(
    output_file,
    index=False
)

print("\nSaved:")
print(output_file)

====================================================================================================
JALACHAKRA — CWR MASTER VARIABLE → DATASET SOURCE MAPPING
====================================================================================================

,Master_Feature,Source_Dataset,Source_Column_or_Basis,Source_Type,Status
0,date,Climate_Data_cleaned.csv,datetime,Direct,Available
1,location,Not yet established,—,Requires spatial linkage,Needs resolution
2,crop,crop_water_data_cleaned.csv / Crop_Calender_cl...,crop_type / Crop,Direct/reference,Available
3,growth_stage,crop_water_data_cleaned.csv / Karnataka_Crop_G...,growth_stage / growth stage,Direct/reference,Available
4,crop_age_days,crop_water_data_cleaned.csv,crop_age_days,Direct,Available
5,kc,Karnataka_Crop_Growth_Stage_Reference_cleaned....,Kc reference / Kc (Crop Coefficient),Reference,Available with gaps
6,temperature,Climate_Data_cleaned.csv,T2M,Direct,Available
7,humidity,Climate_Data_cleaned.csv,RH2M,Direct,Available
8,wind_speed,Climate_Data_cleaned.csv,WS2M,Direct,Available
9,solar_radiation,Climate_Data_cleaned.csv,ALLSKY_SFC_SW_DWN,Direct,Available with 1 missing
10,rainfall,Climate_Data_cleaned.csv,PRECTOTCORR,Direct,Available
11,soil_type,Soil_data_cleaned.csv / crop_water_data_cleane...,Soil type / soil_type,Direct/supporting,Available
12,soil_moisture,crop_water_data_cleaned.csv,soil_moisture_pct,Direct,Available
13,field_area_ha,crop_water_data_cleaned.csv,field_area_ha,Direct,Available
14,irrigation_method,crop_water_data_cleaned.csv,irrigation_method,Direct,Available
15,et0,Derived from weather,T2M/RH2M/WS2M/solar/radiation,Derived,To calculate
16,kc_dynamic,Karnataka growth reference + crop age/GDD,Kc + growth stage,Derived,To calculate
17,etc,Derived,ET0 × Kc,Derived,To calculate
18,effective_rainfall,Derived/reference,Rainfall,Derived,To calculate
19,cwr_baseline,Derived,ETc + agronomic assumptions,Derived,To calculate
20,ml_cwr_target,Not independently observed yet,—,Research target,Needs decision
21,uncertainty_lower,ML model output,—,Model-derived,Future stage
22,uncertainty_upper,ML model output,—,Model-derived,Future stage
23,irrigation_requirement,Derived,CWR + rainfall + soil balance + efficiency,Derived,Future stage

====================================================================================================
STATUS SUMMARY
====================================================================================================

Status
Available                   12
To calculate                 5
Future stage                 3
Available with gaps          1
Needs resolution             1
Available with 1 missing     1
Needs decision               1
Name: count, dtype: int64

Source type summary:

Source_Type
Direct                      10
Derived                      6
Model-derived                2
Direct/reference             2
Reference                    1
Requires spatial linkage     1
Direct/supporting            1
Research target              1
Name: count, dtype: int64

====================================================================================================
VARIABLES REQUIRING SPECIAL ATTENTION
====================================================================================================

,Master_Feature,Source_Dataset,Source_Column_or_Basis,Source_Type,Status
1,location,Not yet established,—,Requires spatial linkage,Needs resolution
5,kc,Karnataka_Crop_Growth_Stage_Reference_cleaned....,Kc reference / Kc (Crop Coefficient),Reference,Available with gaps
15,et0,Derived from weather,T2M/RH2M/WS2M/solar/radiation,Derived,To calculate
16,kc_dynamic,Karnataka growth reference + crop age/GDD,Kc + growth stage,Derived,To calculate
17,etc,Derived,ET0 × Kc,Derived,To calculate
18,effective_rainfall,Derived/reference,Rainfall,Derived,To calculate
19,cwr_baseline,Derived,ETc + agronomic assumptions,Derived,To calculate
20,ml_cwr_target,Not independently observed yet,—,Research target,Needs decision
21,uncertainty_lower,ML model output,—,Model-derived,Future stage
22,uncertainty_upper,ML model output,—,Model-derived,Future stage
23,irrigation_requirement,Derived,CWR + rainfall + soil balance + efficiency,Derived,Future stage

Saved:
C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro\datasets\cleaned\CWR_master_source_mapping.csv

In [4]:
# STEP 5C — WEATHER VARIABLES / ET0 INPUT AUDIT

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

WEATHER_FILE = (
    PROJECT_ROOT
    / "datasets"
    / "cleaned"
    / "Climate_Data_cleaned.csv"
)

weather = pd.read_csv(WEATHER_FILE)

print("=" * 90)
print("JALACHAKRA — WEATHER / ET0 INPUT AUDIT")
print("=" * 90)

print("\nShape:")
print(weather.shape)

print("\nColumns:")
print(list(weather.columns))

# Date
weather["datetime"] = pd.to_datetime(
    weather["datetime"],
    errors="coerce"
)

print("\nDate range:")
print("Start:", weather["datetime"].min())
print("End  :", weather["datetime"].max())

print("\nInvalid dates:")
print(weather["datetime"].isna().sum())

# Required ET0 variables
et0_columns = [
    "T2M",
    "T2M_MIN",
    "T2M_MAX",
    "RH2M",
    "WS2M",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN"
]

available = [
    col for col in et0_columns
    if col in weather.columns
]

print("\nET0-related columns available:")
print(available)

print("\nET0-related columns missing:")
print([
    col for col in et0_columns
    if col not in weather.columns
])

# Range summary
print("\n" + "=" * 90)
print("WEATHER VARIABLE RANGES")
print("=" * 90)

summary = weather[available].describe().T

summary["missing"] = weather[available].isna().sum()
summary["unique"] = weather[available].nunique()

display(summary)

# Percentiles
print("\n" + "=" * 90)
print("KEY PERCENTILES")
print("=" * 90)

display(
    weather[available].quantile(
        [0, 0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99, 1.00]
    )
)

# Basic quality checks
print("\n" + "=" * 90)
print("QUALITY CHECK")
print("=" * 90)

for col in available:
    print(
        f"{col:25s} | "
        f"negative={(weather[col] < 0).sum():4d} | "
        f"zero={(weather[col] == 0).sum():4d} | "
        f"missing={weather[col].isna().sum():4d}"
    )

print("\nNOTE:")
print("No ET0 calculation is being performed yet.")
print("No unit conversion is being assumed yet.")

==========================================================================================
JALACHAKRA — WEATHER / ET0 INPUT AUDIT
==========================================================================================

Shape:
(2557, 11)

Columns:
['datetime', 'DATE', 'MONTH', 'YEAR', 'T2M', 'T2M_MIN', 'T2M_MAX', 'RH2M', 'WS2M', 'PRECTOTCORR', 'ALLSKY_SFC_SW_DWN']

Date range:
Start: 2018-01-01 00:00:00
End  : 2024-12-31 00:00:00

Invalid dates:
0

ET0-related columns available:
['T2M', 'T2M_MIN', 'T2M_MAX', 'RH2M', 'WS2M', 'PRECTOTCORR', 'ALLSKY_SFC_SW_DWN']

ET0-related columns missing:
[]

==========================================================================================
WEATHER VARIABLE RANGES
==========================================================================================

,count,mean,std,min,25%,50%,75%,max,missing,unique
T2M,2557.0,26.620939,4.613406,13.49,23.44,27.47,30.09,36.70,0,1284
T2M_MIN,2557.0,20.904447,5.619031,5.95,16.61,22.62,25.50,29.47,0,1390
T2M_MAX,2557.0,33.724517,4.520488,21.44,30.59,32.76,37.28,45.18,0,1316
RH2M,2557.0,58.894408,19.081115,14.79,46.01,57.70,75.96,94.51,0,2125
WS2M,2557.0,3.090735,1.443017,0.52,1.98,2.73,3.99,12.25,0,572
PRECTOTCORR,2557.0,2.385119,9.383539,0.00,0.00,0.00,0.30,174.26,0,509
ALLSKY_SFC_SW_DWN,2556.0,18.986045,4.871540,1.58,15.81,18.68,22.64,28.92,1,1364

==========================================================================================
KEY PERCENTILES
==========================================================================================

,T2M,T2M_MIN,T2M_MAX,RH2M,WS2M,PRECTOTCORR,ALLSKY_SFC_SW_DWN
0.00,13.490,5.9500,21.4400,14.7900,0.5200,0.0000,1.5800
0.01,15.408,7.7812,24.2768,18.8928,0.9800,0.0000,6.4990
0.05,17.788,10.2060,26.9680,25.8820,1.3280,0.0000,11.0575
0.25,23.440,16.6100,30.5900,46.0100,1.9800,0.0000,15.8100
0.50,27.470,22.6200,32.7600,57.7000,2.7300,0.0000,18.6800
0.75,30.090,25.5000,37.2800,75.9600,3.9900,0.3000,22.6400
0.95,33.010,27.6400,41.5420,86.7660,5.7320,13.6400,26.8600
0.99,33.980,28.5732,42.9588,90.9400,7.2632,37.6884,27.8945
1.00,36.700,29.4700,45.1800,94.5100,12.2500,174.2600,28.9200

==========================================================================================
QUALITY CHECK
==========================================================================================
T2M                       | negative=   0 | zero=   0 | missing=   0
T2M_MIN                   | negative=   0 | zero=   0 | missing=   0
T2M_MAX                   | negative=   0 | zero=   0 | missing=   0
RH2M                      | negative=   0 | zero=   0 | missing=   0
WS2M                      | negative=   0 | zero=   0 | missing=   0
PRECTOTCORR               | negative=   0 | zero=1649 | missing=   0
ALLSKY_SFC_SW_DWN         | negative=   0 | zero=   0 | missing=   1

NOTE:
No ET0 calculation is being performed yet.
No unit conversion is being assumed yet.

In [5]:
# STEP 5D — CHECK LOCATION INFORMATION REQUIRED FOR FAO-56 ET0

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

WEATHER_FILE = (
    PROJECT_ROOT
    / "datasets"
    / "cleaned"
    / "Climate_Data_cleaned.csv"
)

weather = pd.read_csv(WEATHER_FILE)

print("=" * 90)
print("JALACHAKRA — FAO-56 ET0 LOCATION AUDIT")
print("=" * 90)

# ---------------------------------------------------------
# 1. SEARCH FOR POSSIBLE LOCATION COLUMNS
# ---------------------------------------------------------

possible_location_keywords = [
    "location",
    "district",
    "latitude",
    "latitude",
    "lat",
    "longitude",
    "longitude",
    "lon",
    "elevation",
    "altitude",
    "site"
]

matched_columns = []

for col in weather.columns:

    col_lower = col.lower().strip()

    for keyword in possible_location_keywords:

        if keyword in col_lower:
            matched_columns.append(col)
            break

matched_columns = list(dict.fromkeys(matched_columns))

print("\nPossible location-related columns:")
print(matched_columns)

# ---------------------------------------------------------
# 2. DISPLAY UNIQUE VALUES IF FOUND
# ---------------------------------------------------------

if matched_columns:

    print("\nLocation-related information:")
    
    for col in matched_columns:

        print("\n" + "-" * 60)
        print("Column:", col)
        print("Unique values:", weather[col].nunique())

        display(
            weather[col]
            .drop_duplicates()
            .head(20)
        )

else:

    print("\nNo location/latitude/longitude/elevation column found.")

# ---------------------------------------------------------
# 3. CHECK ORIGINAL WEATHER STRUCTURE
# ---------------------------------------------------------

print("\n" + "=" * 90)
print("FULL WEATHER COLUMN LIST")
print("=" * 90)

for i, col in enumerate(weather.columns, start=1):
    print(f"{i:02d}. {col}")

# ---------------------------------------------------------
# 4. SCIENTIFIC DECISION
# ---------------------------------------------------------

print("\n" + "=" * 90)
print("DECISION")
print("=" * 90)

if matched_columns:

    print(
        "Location-related information exists and will be "
        "examined before ET0 calculation."
    )

else:

    print(
        "The weather dataset does not contain explicit "
        "location/latitude/elevation information."
    )

print(
    "\nWe will NOT assume Karnataka coordinates automatically."
)

print(
    "We will resolve the spatial context before calculating "
    "the final FAO-56 radiation terms."
)

==========================================================================================
JALACHAKRA — FAO-56 ET0 LOCATION AUDIT
==========================================================================================

Possible location-related columns:
[]

No location/latitude/longitude/elevation column found.

==========================================================================================
FULL WEATHER COLUMN LIST
==========================================================================================
01. datetime
02. DATE
03. MONTH
04. YEAR
05. T2M
06. T2M_MIN
07. T2M_MAX
08. RH2M
09. WS2M
10. PRECTOTCORR
11. ALLSKY_SFC_SW_DWN

==========================================================================================
DECISION
==========================================================================================
The weather dataset does not contain explicit location/latitude/elevation information.

We will NOT assume Karnataka coordinates automatically.
We will resolve the spatial context before calculating the final FAO-56 radiation terms.

In [6]:
# STEP 5E — WEATHER DATA PROVENANCE CHECK

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_FILE = (
    PROJECT_ROOT
    / "datasets"
    / "raw"
    / "Climate_Data.csv"
)

print("=" * 90)
print("JALACHAKRA — CLIMATE DATA PROVENANCE CHECK")
print("=" * 90)

# ---------------------------------------------------------
# 1. READ RAW FILE HEADER
# ---------------------------------------------------------

with open(RAW_FILE, "r", encoding="utf-8", errors="ignore") as f:

    first_lines = []

    for _ in range(15):

        line = f.readline()

        if not line:
            break

        first_lines.append(line.rstrip())

print("\nRAW FILE FIRST 15 LINES")
print("-" * 90)

for i, line in enumerate(first_lines, start=1):
    print(f"{i:02d}: {line}")

# ---------------------------------------------------------
# 2. LOAD RAW FILE
# ---------------------------------------------------------

raw_weather = pd.read_csv(RAW_FILE)

print("\n" + "=" * 90)
print("RAW FILE INFORMATION")
print("=" * 90)

print("\nShape:")
print(raw_weather.shape)

print("\nColumns:")
print(list(raw_weather.columns))

print("\nFirst 5 records:")
display(raw_weather.head())

# ---------------------------------------------------------
# 3. CHECK FOR TEXT / SOURCE-LIKE VALUES
# ---------------------------------------------------------

print("\n" + "=" * 90)
print("POSSIBLE SOURCE / LOCATION INFORMATION")
print("=" * 90)

for col in raw_weather.columns:

    if raw_weather[col].dtype == "object":

        unique_values = raw_weather[col].dropna().astype(str).unique()

        print(
            f"\nColumn: {col}"
            f"\nUnique values: {len(unique_values)}"
        )

        display(
            pd.Series(unique_values[:20], name=col)
        )

# ---------------------------------------------------------
# 4. SCIENTIFIC DECISION
# ---------------------------------------------------------

print("\n" + "=" * 90)
print("PROVENANCE DECISION")
print("=" * 90)

print(
    "We will only assign geographic coordinates if the "
    "dataset/source provides evidence for them."
)

print(
    "No Karnataka coordinate will be assumed from the "
    "dataset name alone."
)

print(
    "ET0 calculation will follow after spatial provenance "
    "is resolved."
)

==========================================================================================
JALACHAKRA — CLIMATE DATA PROVENANCE CHECK
==========================================================================================

RAW FILE FIRST 15 LINES
------------------------------------------------------------------------------------------
01: datetime,DATE,MONTH,YEAR,T2M,T2M_MIN,T2M_MAX,RH2M,WS2M,PRECTOTCORR,ALLSKY_SFC_SW_DWN
02: 1/1/2018,1,1,2018,17.92,9.96,27.95,24.23,2.43,0,16.95
03: 1/2/2018,2,1,2018,18.24,9.34,28.73,28.32,2.19,0,15.63
04: 1/3/2018,3,1,2018,19.31,11.28,29.7,28.21,1.81,0,15.35
05: 1/4/2018,4,1,2018,19.2,12.75,28.96,33.37,1.66,0,15.68
06: 1/5/2018,5,1,2018,19.91,13.21,28.7,62.9,1.45,0,16.13
07: 1/6/2018,6,1,2018,19.76,13.33,27.89,53.62,1.73,0,16.6
08: 1/7/2018,7,1,2018,18.58,11.54,27.25,30.63,2.04,0,16.73
09: 1/8/2018,8,1,2018,18.33,10.35,27.74,29.67,1.98,0,15.77
10: 1/9/2018,9,1,2018,19.97,12.02,29.59,32.64,2.06,0,13.93
11: 1/10/2018,10,1,2018,21.98,14.43,31.25,37.76,2.5,0,12.58
12: 1/11/2018,11,1,2018,22.92,14.86,31.45,35.82,1.86,0,12.17
13: 1/12/2018,12,1,2018,24.2,16.92,31.9,30.99,2.12,0,10.02
14: 1/13/2018,13,1,2018,25.23,19.32,32.61,34.78,2.07,0,12.5
15: 1/14/2018,14,1,2018,25.7,19.25,33.92,38.2,1.8,0,14.44

==========================================================================================
RAW FILE INFORMATION
==========================================================================================

Shape:
(2557, 11)

Columns:
['datetime', 'DATE', 'MONTH', 'YEAR', 'T2M', 'T2M_MIN', 'T2M_MAX', 'RH2M', 'WS2M', 'PRECTOTCORR', 'ALLSKY_SFC_SW_DWN']

First 5 records:

,datetime,DATE,MONTH,YEAR,T2M,T2M_MIN,T2M_MAX,RH2M,WS2M,PRECTOTCORR,ALLSKY_SFC_SW_DWN
0,1/1/2018,1,1,2018,17.92,9.96,27.95,24.23,2.43,0.0,16.95
1,1/2/2018,2,1,2018,18.24,9.34,28.73,28.32,2.19,0.0,15.63
2,1/3/2018,3,1,2018,19.31,11.28,29.70,28.21,1.81,0.0,15.35
3,1/4/2018,4,1,2018,19.20,12.75,28.96,33.37,1.66,0.0,15.68
4,1/5/2018,5,1,2018,19.91,13.21,28.70,62.90,1.45,0.0,16.13

==========================================================================================
POSSIBLE SOURCE / LOCATION INFORMATION
==========================================================================================

Column: datetime
Unique values: 2557

0      1/1/2018
1      1/2/2018
2      1/3/2018
3      1/4/2018
4      1/5/2018
5      1/6/2018
6      1/7/2018
7      1/8/2018
8      1/9/2018
9     1/10/2018
10    1/11/2018
11    1/12/2018
12    1/13/2018
13    1/14/2018
14    1/15/2018
15    1/16/2018
16    1/17/2018
17    1/18/2018
18    1/19/2018
19    1/20/2018
Name: datetime, dtype: object

==========================================================================================
PROVENANCE DECISION
==========================================================================================
We will only assign geographic coordinates if the dataset/source provides evidence for them.
No Karnataka coordinate will be assumed from the dataset name alone.
ET0 calculation will follow after spatial provenance is resolved.

In [7]:
# STEP 5F — SEARCH PROJECT FOR CLIMATE DATA PROVENANCE

from pathlib import Path

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

print("=" * 100)
print("JALACHAKRA — CLIMATE DATA PROVENANCE SEARCH")
print("=" * 100)

search_terms = [
    "Climate_Data.csv",
    "Climate_Data",
    "NASA POWER",
    "POWER API",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN",
    "T2M_MIN",
    "T2M_MAX"
]

allowed_extensions = {
    ".py", ".ipynb", ".md", ".txt", ".csv",
    ".json", ".yml", ".yaml"
}

matches = []

for file in PROJECT_ROOT.rglob("*"):

    if not file.is_file():
        continue

    if file.suffix.lower() not in allowed_extensions:
        continue

    # Skip large/generated directories
    if any(
        part.lower() in {
            ".git",
            ".venv",
            "node_modules",
            "__pycache__"
        }
        for part in file.parts
    ):
        continue

    try:
        text = file.read_text(
            encoding="utf-8",
            errors="ignore"
        )
    except Exception:
        continue

    for term in search_terms:

        if term.lower() in text.lower():

            matches.append({
                "File": str(file.relative_to(PROJECT_ROOT)),
                "Search_Term": term
            })

# ---------------------------------------------------------
# RESULTS
# ---------------------------------------------------------

if matches:

    results = (
        __import__("pandas")
        .DataFrame(matches)
        .drop_duplicates()
        .sort_values(["File", "Search_Term"])
    )

    print("\nPotential provenance references found:")
    display(results)

else:

    print("\nNo provenance references were found in the project.")

# ---------------------------------------------------------
# IMPORTANT FILES TO INSPECT
# ---------------------------------------------------------

print("\n" + "=" * 100)
print("RESULT")
print("=" * 100)

if matches:
    print(
        "References were found. We will inspect the relevant "
        "file(s) before assigning geographic coordinates."
    )
else:
    print(
        "No project documentation identifies the geographic "
        "source of Climate_Data.csv."
    )

print(
    "\nDo NOT calculate final FAO-56 ET0 yet."
)

====================================================================================================
JALACHAKRA — CLIMATE DATA PROVENANCE SEARCH
====================================================================================================

Potential provenance references found:

                                              File        Search_Term
14  datasets\cleaned\CWR_master_source_mapping.csv  ALLSKY_SFC_SW_DWN
12  datasets\cleaned\CWR_master_source_mapping.csv       Climate_Data
13  datasets\cleaned\CWR_master_source_mapping.csv        PRECTOTCORR
9        datasets\cleaned\Climate_Data_cleaned.csv  ALLSKY_SFC_SW_DWN
8        datasets\cleaned\Climate_Data_cleaned.csv        PRECTOTCORR
11       datasets\cleaned\Climate_Data_cleaned.csv            T2M_MAX
10       datasets\cleaned\Climate_Data_cleaned.csv            T2M_MIN
16                   datasets\raw\Climate_Data.csv  ALLSKY_SFC_SW_DWN
15                   datasets\raw\Climate_Data.csv        PRECTOTCORR
18                   datasets\raw\Climate_Data.csv            T2M_MAX
17                   datasets\raw\Climate_Data.csv            T2M_MIN
5              notebooks\01_dataset_analysis.ipynb  ALLSKY_SFC_SW_DWN
1              notebooks\01_dataset_analysis.ipynb       Climate_Data
0              notebooks\01_dataset_analysis.ipynb   Climate_Data.csv
2              notebooks\01_dataset_analysis.ipynb         NASA POWER
3              notebooks\01_dataset_analysis.ipynb          POWER API
4              notebooks\01_dataset_analysis.ipynb        PRECTOTCORR
7              notebooks\01_dataset_analysis.ipynb            T2M_MAX
6              notebooks\01_dataset_analysis.ipynb            T2M_MIN

====================================================================================================
RESULT
====================================================================================================
References were found. We will inspect the relevant file(s) before assigning geographic coordinates.

Do NOT calculate final FAO-56 ET0 yet.

In [8]:
# STEP 5G — INSPECT NOTEBOOK FOR ORIGINAL WEATHER SOURCE

from pathlib import Path
import json

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

NOTEBOOK = (
    PROJECT_ROOT
    / "notebooks"
    / "01_dataset_analysis.ipynb"
)

print("=" * 100)
print("JALACHAKRA — ORIGINAL WEATHER SOURCE CODE SEARCH")
print("=" * 100)

with open(NOTEBOOK, "r", encoding="utf-8") as f:
    notebook = json.load(f)

keywords = [
    "NASA POWER",
    "POWER API",
    "power.larc.nasa.gov",
    "api",
    "Climate_Data.csv",
    "latitude",
    "longitude",
    "elevation"
]

found = []

for cell_number, cell in enumerate(
    notebook.get("cells", []),
    start=1
):

    source = "".join(cell.get("source", []))

    if not source:
        continue

    matched = [
        keyword
        for keyword in keywords
        if keyword.lower() in source.lower()
    ]

    if matched:

        found.append({
            "cell_number": cell_number,
            "cell_type": cell.get("cell_type"),
            "matched_keywords": matched,
            "source": source
        })

# ---------------------------------------------------------
# DISPLAY MATCHING CELLS
# ---------------------------------------------------------

if found:

    print(f"\nMatching cells found: {len(found)}")

    for item in found:

        print("\n" + "=" * 100)
        print(
            f"CELL {item['cell_number']} "
            f"({item['cell_type']})"
        )
        print(
            "Matched:",
            ", ".join(item["matched_keywords"])
        )
        print("-" * 100)

        print(item["source"])

else:

    print("\nNo source/API code was found in the notebook.")

# ---------------------------------------------------------
# FINAL DECISION
# ---------------------------------------------------------

print("\n" + "=" * 100)
print("PROVENANCE STATUS")
print("=" * 100)

if found:
    print(
        "Potential source/download code was found."
    )
    print(
        "We will inspect the matching code to determine "
        "whether coordinates and NASA POWER provenance "
        "are actually documented."
    )
else:
    print(
        "The notebook does not contain identifiable "
        "weather download/provenance code."
    )

print(
    "\nDo NOT assign coordinates or calculate final ET0 yet."
)

====================================================================================================
JALACHAKRA — ORIGINAL WEATHER SOURCE CODE SEARCH
====================================================================================================

Matching cells found: 12

====================================================================================================
CELL 6 (code)
Matched: latitude, longitude
----------------------------------------------------------------------------------------------------
# STEP 1E — Date, location, crop and time-coverage analysis

DATE_KEYWORDS = [
    "date",
    "datetime",
    "time",
    "year",
    "month"
]

LOCATION_KEYWORDS = [
    "state",
    "district",
    "location",
    "region",
    "latitude",
    "longitude",
    "lat",
    "lon"
]

CROP_KEYWORDS = [
    "crop",
    "crops",
    "crop_type",
    "label"
]

for name, df in datasets.items():

    print("\n" + "=" * 90)
    print(f"DATASET: {name}")
    print("=" * 90)

    # ---------------------------
    # Date-like columns
    # ---------------------------
    date_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in DATE_KEYWORDS
        )
    ]

    if date_columns:
        print("\nDATE/TIME COLUMNS:")

        for col in date_columns:

            print(f"\nColumn: {col}")

            series = df[col].dropna()

            print("Data type:", df[col].dtype)
            print("Unique values:", series.nunique())

            # Try to interpret as dates
            converted = pd.to_datetime(
                series,
                errors="coerce"
            )

            valid_dates = converted.dropna()

            if len(valid_dates) > 0:
                print("Possible minimum date:", valid_dates.min())
                print("Possible maximum date:", valid_dates.max())
            else:
                print("Could not interpret this column as dates.")

    else:
        print("\nNo obvious date/time columns found.")

    # ---------------------------
    # Location columns
    # ---------------------------
    location_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in LOCATION_KEYWORDS
        )
    ]

    if location_columns:
        print("\nLOCATION COLUMNS:")

        for col in location_columns:

            print(f"\nColumn: {col}")
            print("Unique values:", df[col].nunique(dropna=True))

            print(
                df[col]
                .dropna()
                .astype(str)
                .value_counts()
                .head(15)
            )

    else:
        print("\nNo obvious location columns found.")

    # ---------------------------
    # Crop columns
    # ---------------------------
    crop_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in CROP_KEYWORDS
        )
    ]

    if crop_columns:
        print("\nCROP COLUMNS:")

        for col in crop_columns:

            print(f"\nColumn: {col}")
            print(
                "Unique crop values:",
                df[col].nunique(dropna=True)
            )

            print(
                df[col]
                .dropna()
                .astype(str)
                .value_counts()
                .head(20)
            )

    else:
        print("\nNo obvious crop columns found.")

====================================================================================================
CELL 7 (code)
Matched: latitude, longitude
----------------------------------------------------------------------------------------------------
# STEP 1E — Compact dataset coverage summary
# This analyzes ALL datasets without producing huge output.

summary_rows = []

for name, df in datasets.items():

    # ---------- Date detection ----------
    date_columns = []

    for col in df.columns:
        col_lower = str(col).lower()

        if any(word in col_lower for word in [
            "date", "datetime", "time"
        ]):
            date_columns.append(col)

    date_start = None
    date_end = None

    for col in date_columns:

        converted = pd.to_datetime(
            df[col],
            errors="coerce"
        )

        valid = converted.dropna()

        # Ignore columns that are not really date-like
        if len(valid) >= max(3, int(len(df) * 0.5)):

            current_start = valid.min()
            current_end = valid.max()

            if date_start is None or current_start < date_start:
                date_start = current_start

            if date_end is None or current_end > date_end:
                date_end = current_end

    # ---------- Crop detection ----------
    crop_columns = []

    for col in df.columns:
        col_lower = str(col).lower()

        if any(word in col_lower for word in [
            "crop", "crops", "crop_type", "label"
        ]):
            crop_columns.append(col)

    crop_count = None

    if crop_columns:
        counts = []

        for col in crop_columns:
            counts.append(df[col].nunique(dropna=True))

        crop_count = max(counts)

    # ---------- Location detection ----------
    location_columns = []

    for col in df.columns:
        col_lower = str(col).lower()

        if any(word in col_lower for word in [
            "state",
            "district",
            "location",
            "region",
            "latitude",
            "longitude",
            "lat",
            "lon"
        ]):
            location_columns.append(col)

    location_count = None

    if location_columns:
        counts = []

        for col in location_columns:
            counts.append(df[col].nunique(dropna=True))

        location_count = max(counts)

    # ---------- Important CWR variables ----------
    cwr_keywords = [
        "water",
        "requirement",
        "evapotranspiration",
        "et0",
        "etc",
        "kc",
        "rainfall",
        "precip",
        "temperature",
        "humidity",
        "wind",
        "solar",
        "moisture",
        "irrigation",
        "growth",
        "stage",
        "root",
        "whc"
    ]

    cwr_columns = []

    for col in df.columns:

        normalized = str(col).lower().replace("_", " ")

        if any(word in normalized for word in cwr_keywords):
            cwr_columns.append(str(col))

    summary_rows.append({
        "dataset": name,
        "rows": len(df),
        "columns": len(df.columns),
        "date_columns": ", ".join(map(str, date_columns))
            if date_columns else "None",
        "date_start": date_start,
        "date_end": date_end,
        "crop_columns": ", ".join(map(str, crop_columns))
            if crop_columns else "None",
        "crop_count": crop_count,
        "location_columns": ", ".join(map(str, location_columns))
            if location_columns else "None",
        "location_count": location_count,
        "cwr_related_columns": ", ".join(cwr_columns)
            if cwr_columns else "None"
    })


coverage_df = pd.DataFrame(summary_rows)

coverage_df

====================================================================================================
CELL 15 (code)
Matched: Climate_Data.csv, latitude, longitude
----------------------------------------------------------------------------------------------------
# STEP 3A — Climate dataset provenance and geographic coverage

df = datasets["Climate_Data.csv"]

print("=" * 80)
print("CLIMATE DATASET PROVENANCE CHECK")
print("=" * 80)

print("\nColumns:")
print(list(df.columns))

print("\nShape:")
print(df.shape)

# -----------------------------
# Check possible location fields
# -----------------------------
geo_keywords = [
    "state",
    "district",
    "location",
    "region",
    "latitude",
    "longitude",
    "lat",
    "lon",
    "station",
    "site"
]

geo_columns = [
    col for col in df.columns
    if any(
        key in str(col).lower()
        for key in geo_keywords
    )
]

print("\nPossible geographic columns:")

if geo_columns:
    for col in geo_columns:
        print(f"\n--- {col} ---")
        print("Unique values:", df[col].nunique(dropna=True))
        display(
            df[col]
            .dropna()
            .astype(str)
            .value_counts()
            .head(20)
        )
else:
    print("No obvious geographic columns found.")

# -----------------------------
# Check the actual datetime
# -----------------------------
if "datetime" in df.columns:

    dates = pd.to_datetime(
        df["datetime"],
        errors="coerce"
    )

    print("\nDATETIME INFORMATION")
    print("-" * 50)
    print("Minimum:", dates.min())
    print("Maximum:", dates.max())
    print("Valid:", dates.notna().sum())
    print("Unique dates:", dates.nunique())

# -----------------------------
# Display representative rows
# -----------------------------
print("\nFIRST 5 ROWS")
display(df.head())

print("\nLAST 5 ROWS")
display(df.tail())

====================================================================================================
CELL 16 (code)
Matched: Climate_Data.csv
----------------------------------------------------------------------------------------------------
# STEP 3B — Search project files for Climate_Data provenance

from pathlib import Path

search_terms = [
    "Climate_Data",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN",
    "2018-01-01",
    "2024-12-31"
]

search_extensions = {
    ".md",
    ".txt",
    ".json",
    ".csv",
    ".html",
    ".py"
}

matches = []

for path in PROJECT_ROOT.rglob("*"):

    if not path.is_file():
        continue

    if path.suffix.lower() not in search_extensions:
        continue

    # Avoid searching huge/raw dataset files again
    if "datasets" in path.parts and path.name != "Climate_Data.csv":
        continue

    try:
        text = path.read_text(
            encoding="utf-8",
            errors="ignore"
        )

        found_terms = [
            term for term in search_terms
            if term.lower() in text.lower()
        ]

        if found_terms:

            matches.append({
                "file": str(path.relative_to(PROJECT_ROOT)),
                "matched_terms": ", ".join(found_terms)
            })

    except Exception:
        pass


matches_df = pd.DataFrame(matches)

if matches_df.empty:
    print("No project-documentation reference to Climate_Data provenance was found.")
else:
    display(matches_df)

====================================================================================================
CELL 18 (code)
Matched: Climate_Data.csv
----------------------------------------------------------------------------------------------------
# STEP 3B — Search project documentation for Climate_Data provenance

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

print("Project root:")
print(PROJECT_ROOT)

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"Project folder not found: {PROJECT_ROOT}"
    )

search_terms = [
    "Climate_Data",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN",
    "2018-01-01",
    "2024-12-31"
]

search_extensions = {
    ".md",
    ".txt",
    ".json",
    ".html",
    ".py"
}

matches = []

for path in PROJECT_ROOT.rglob("*"):

    if not path.is_file():
        continue

    if path.suffix.lower() not in search_extensions:
        continue

    try:
        text = path.read_text(
            encoding="utf-8",
            errors="ignore"
        )

        found_terms = []

        for term in search_terms:
            if term.lower() in text.lower():
                found_terms.append(term)

        if found_terms:
            matches.append({
                "file": str(path.relative_to(PROJECT_ROOT)),
                "matched_terms": ", ".join(found_terms)
            })

    except Exception:
        continue


matches_df = pd.DataFrame(matches)

print("\nRESULT")
print("=" * 70)

if matches_df.empty:
    print("No project documentation was found that identifies")
    print("the geographic/source provenance of Climate_Data.csv.")
else:
    display(matches_df)

====================================================================================================
CELL 19 (code)
Matched: Climate_Data.csv
----------------------------------------------------------------------------------------------------
# STEP 3C — Weather variable summary

climate = datasets["Climate_Data.csv"]

weather_columns = [
    "T2M",
    "T2M_MIN",
    "T2M_MAX",
    "RH2M",
    "WS2M",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN"
]

existing_weather_columns = [
    col for col in weather_columns
    if col in climate.columns
]

display(
    climate[existing_weather_columns].describe().T
)

====================================================================================================
CELL 20 (code)
Matched: Climate_Data.csv
----------------------------------------------------------------------------------------------------
# STEP 3D — Investigate suspicious climate values

climate = datasets["Climate_Data.csv"].copy()

print("=" * 80)
print("CLIMATE DATA QUALITY INVESTIGATION")
print("=" * 80)

# --------------------------------------------------
# 1. Sentinel / suspicious solar radiation values
# --------------------------------------------------

print("\n1. Solar radiation values <= 0 or suspicious")

solar = climate["ALLSKY_SFC_SW_DWN"]

print("Values equal to -999:", (solar == -999).sum())
print("Values below 0:", (solar < 0).sum())
print("Minimum:", solar.min())

if (solar == -999).sum() > 0:

    print("\nRows containing -999:")

    display(
        climate.loc[
            solar == -999,
            ["datetime", "ALLSKY_SFC_SW_DWN"]
        ].head(20)
    )

# --------------------------------------------------
# 2. Suspicious precipitation
# --------------------------------------------------

print("\n2. Precipitation values")

rain = climate["PRECTOTCORR"]

print("Minimum:", rain.min())
print("Maximum:", rain.max())
print("Values > 50:", (rain > 50).sum())
print("Values > 100:", (rain > 100).sum())

print("\nLargest precipitation records:")

display(
    climate[
        ["datetime", "PRECTOTCORR"]
    ]
    .sort_values(
        "PRECTOTCORR",
        ascending=False
    )
    .head(20)
)

# --------------------------------------------------
# 3. Temperature sanity check
# --------------------------------------------------

print("\n3. Temperature sanity check")

display(
    climate[
        [
            "datetime",
            "T2M",
            "T2M_MIN",
            "T2M_MAX"
        ]
    ].describe()
)

# --------------------------------------------------
# 4. Humidity check
# --------------------------------------------------

print("\n4. Humidity sanity check")

humidity = climate["RH2M"]

print("Minimum:", humidity.min())
print("Maximum:", humidity.max())
print("Below 0:", (humidity < 0).sum())
print("Above 100:", (humidity > 100).sum())

# --------------------------------------------------
# 5. Wind speed check
# --------------------------------------------------

print("\n5. Wind speed sanity check")

wind = climate["WS2M"]

print("Minimum:", wind.min())
print("Maximum:", wind.max())
print("Below 0:", (wind < 0).sum())

====================================================================================================
CELL 24 (code)
Matched: Climate_Data.csv
----------------------------------------------------------------------------------------------------
# STEP 4B — Clean Climate_Data.csv
# Self-contained version

from pathlib import Path
import pandas as pd
import numpy as np

# --------------------------------------------------
# 1. Project paths
# --------------------------------------------------

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

RAW_DIR = PROJECT_ROOT / "datasets" / "raw"
CLEAN_DIR = PROJECT_ROOT / "datasets" / "cleaned"

# Create cleaned-data folder if it doesn't exist
CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# --------------------------------------------------
# 2. Load RAW climate data
# --------------------------------------------------

raw_file = RAW_DIR / "Climate_Data.csv"

if not raw_file.exists():
    raise FileNotFoundError(
        f"Raw file not found:\n{raw_file}"
    )

climate_raw = pd.read_csv(
    raw_file
)

climate = climate_raw.copy()

print("RAW FILE:")
print(raw_file)

print("\nRAW SHAPE:")
print(climate.shape)

# --------------------------------------------------
# 3. Convert datetime
# --------------------------------------------------

climate["datetime"] = pd.to_datetime(
    climate["datetime"],
    errors="coerce"
)

invalid_dates = climate["datetime"].isna().sum()

print("\nInvalid datetime values:", invalid_dates)

# Remove only rows with invalid dates
climate = climate.dropna(
    subset=["datetime"]
).copy()

# --------------------------------------------------
# 4. Convert known sentinel value
# --------------------------------------------------

solar_column = "ALLSKY_SFC_SW_DWN"

sentinel_count = (
    climate[solar_column] == -999
).sum()

print(
    "Solar radiation values equal to -999:",
    sentinel_count
)

climate.loc[
    climate[solar_column] == -999,
    solar_column
] = np.nan

# --------------------------------------------------
# 5. Duplicate datetime check
# --------------------------------------------------

duplicate_dates = climate["datetime"].duplicated().sum()

print(
    "Duplicate datetime records:",
    duplicate_dates
)

# We are NOT removing duplicates automatically.
# We only report them at this stage.

# --------------------------------------------------
# 6. Missing-value report
# --------------------------------------------------

print("\nMissing values after cleaning:")
missing_report = climate.isna().sum()

display(
    missing_report[missing_report > 0]
)

# --------------------------------------------------
# 7. Sort by datetime
# --------------------------------------------------

climate = climate.sort_values(
    "datetime"
).reset_index(drop=True)

# --------------------------------------------------
# 8. Save cleaned COPY
# --------------------------------------------------

clean_file = CLEAN_DIR / "Climate_Data_cleaned.csv"

climate.to_csv(
    clean_file,
    index=False
)

print("\nCLEANED FILE SAVED:")
print(clean_file)

print("\nFINAL SHAPE:")
print(climate.shape)

print("\nDate range:")
print("Start:", climate["datetime"].min())
print("End  :", climate["datetime"].max())

====================================================================================================
CELL 41 (code)
Matched: latitude, longitude, elevation
----------------------------------------------------------------------------------------------------
# STEP 5D — CHECK LOCATION INFORMATION REQUIRED FOR FAO-56 ET0

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

WEATHER_FILE = (
    PROJECT_ROOT
    / "datasets"
    / "cleaned"
    / "Climate_Data_cleaned.csv"
)

weather = pd.read_csv(WEATHER_FILE)

print("=" * 90)
print("JALACHAKRA — FAO-56 ET0 LOCATION AUDIT")
print("=" * 90)

# ---------------------------------------------------------
# 1. SEARCH FOR POSSIBLE LOCATION COLUMNS
# ---------------------------------------------------------

possible_location_keywords = [
    "location",
    "district",
    "latitude",
    "latitude",
    "lat",
    "longitude",
    "longitude",
    "lon",
    "elevation",
    "altitude",
    "site"
]

matched_columns = []

for col in weather.columns:

    col_lower = col.lower().strip()

    for keyword in possible_location_keywords:

        if keyword in col_lower:
            matched_columns.append(col)
            break

matched_columns = list(dict.fromkeys(matched_columns))


In [9]:
# STEP 5H — FIND EXACT NASA POWER / WEATHER DOWNLOAD CODE

from pathlib import Path
import json

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

NOTEBOOK = (
    PROJECT_ROOT
    / "notebooks"
    / "01_dataset_analysis.ipynb"
)

with open(NOTEBOOK, "r", encoding="utf-8") as f:
    notebook = json.load(f)

print("=" * 100)
print("JALACHAKRA — EXACT WEATHER API / DOWNLOAD CODE")
print("=" * 100)

strong_keywords = [
    "power.larc.nasa.gov",
    "https://power",
    "requests.get",
    "requests.request",
    "NASA POWER",
    "POWER API",
    "api/temporal",
    "parameters=",
    "latitude=",
    "longitude="
]

found_cells = []

for cell_number, cell in enumerate(
    notebook.get("cells", []),
    start=1
):

    source = "".join(cell.get("source", []))

    if not source:
        continue

    matches = []

    for keyword in strong_keywords:
        if keyword.lower() in source.lower():
            matches.append(keyword)

    if matches:
        found_cells.append(
            (cell_number, cell.get("cell_type"), matches, source)
        )

print("\nMatching cells:", len(found_cells))

for cell_number, cell_type, matches, source in found_cells:

    print("\n" + "=" * 100)
    print(f"CELL {cell_number} — {cell_type}")
    print("Matched keywords:", matches)
    print("-" * 100)

    # Print the complete cell so URL/coordinates are visible
    print(source)

print("\n" + "=" * 100)
print("WHAT WE NEED")
print("=" * 100)

print("""
Look for:
1. power.larc.nasa.gov
2. latitude
3. longitude
4. start/end dates
5. parameters such as T2M, RH2M, WS2M, PRECTOTCORR
6. code that saves the response as Climate_Data.csv
""")

print("\nDo NOT calculate ET0 yet.")

====================================================================================================
JALACHAKRA — EXACT WEATHER API / DOWNLOAD CODE
====================================================================================================

Matching cells: 3

====================================================================================================
CELL 43 — code
Matched keywords: ['NASA POWER', 'POWER API']
----------------------------------------------------------------------------------------------------
# STEP 5F — SEARCH PROJECT FOR CLIMATE DATA PROVENANCE

from pathlib import Path

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

print("=" * 100)
print("JALACHAKRA — CLIMATE DATA PROVENANCE SEARCH")
print("=" * 100)

search_terms = [
    "Climate_Data.csv",
    "Climate_Data",
    "NASA POWER",
    "POWER API",
    "PRECTOTCORR",
    "ALLSKY_SFC_SW_DWN",
    "T2M_MIN",
    "T2M_MAX"
]

allowed_extensions = {
    ".py", ".ipynb", ".md", ".txt", ".csv",
    ".json", ".yml", ".yaml"
}

matches = []

for file in PROJECT_ROOT.rglob("*"):

    if not file.is_file():
        continue

    if file.suffix.lower() not in allowed_extensions:
        continue

    # Skip large/generated directories
    if any(
        part.lower() in {
            ".git",
            ".venv",
            "node_modules",
            "__pycache__"
        }
        for part in file.parts
    ):
        continue

    try:
        text = file.read_text(
            encoding="utf-8",
            errors="ignore"
        )
    except Exception:
        continue

    for term in search_terms:

        if term.lower() in text.lower():

            matches.append({
                "File": str(file.relative_to(PROJECT_ROOT)),
                "Search_Term": term
            })

# ---------------------------------------------------------
# RESULTS
# ---------------------------------------------------------

if matches:

    results = (
        __import__("pandas")
        .DataFrame(matches)
        .drop_duplicates()
        .sort_values(["File", "Search_Term"])
    )

    print("\nPotential provenance references found:")
    display(results)

else:

    print("\nNo provenance references were found in the project.")

# ---------------------------------------------------------
# IMPORTANT FILES TO INSPECT
# ---------------------------------------------------------

print("\n" + "=" * 100)
print("RESULT")
print("=" * 100)

if matches:
    print(
        "References were found. We will inspect the relevant "
        "file(s) before assigning geographic coordinates."
    )
else:
    print(
        "No project documentation identifies the geographic "
        "source of Climate_Data.csv."
    )

print(
    "\nDo NOT calculate final FAO-56 ET0 yet."
)

====================================================================================================
CELL 44 — code
Matched keywords: ['power.larc.nasa.gov', 'NASA POWER', 'POWER API']
----------------------------------------------------------------------------------------------------
# STEP 5G — INSPECT NOTEBOOK FOR ORIGINAL WEATHER SOURCE

from pathlib import Path
import json

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

NOTEBOOK = (
    PROJECT_ROOT
    / "notebooks"
    / "01_dataset_analysis.ipynb"
)

print("=" * 100)
print("JALACHAKRA — ORIGINAL WEATHER SOURCE CODE SEARCH")
print("=" * 100)

with open(NOTEBOOK, "r", encoding="utf-8") as f:
    notebook = json.load(f)

keywords = [
    "NASA POWER",
    "POWER API",
    "power.larc.nasa.gov",
    "api",
    "Climate_Data.csv",
    "latitude",
    "longitude",
    "elevation"
]

found = []

for cell_number, cell in enumerate(
    notebook.get("cells", []),
    start=1
):

    source = "".join(cell.get("source", []))

    if not source:
        continue

    matched = [
        keyword
        for keyword in keywords
        if keyword.lower() in source.lower()
    ]

    if matched:

        found.append({
            "cell_number": cell_number,
            "cell_type": cell.get("cell_type"),
            "matched_keywords": matched,
            "source": source
        })

# ---------------------------------------------------------
# DISPLAY MATCHING CELLS
# ---------------------------------------------------------

if found:

    print(f"\nMatching cells found: {len(found)}")

    for item in found:

        print("\n" + "=" * 100)
        print(
            f"CELL {item['cell_number']} "
            f"({item['cell_type']})"
        )
        print(
            "Matched:",
            ", ".join(item["matched_keywords"])
        )
        print("-" * 100)

        print(item["source"])

else:

    print("\nNo source/API code was found in the notebook.")

# ---------------------------------------------------------
# FINAL DECISION
# ---------------------------------------------------------

print("\n" + "=" * 100)
print("PROVENANCE STATUS")
print("=" * 100)

if found:
    print(
        "Potential source/download code was found."
    )
    print(
        "We will inspect the matching code to determine "
        "whether coordinates and NASA POWER provenance "
        "are actually documented."
    )
else:
    print(
        "The notebook does not contain identifiable "
        "weather download/provenance code."
    )

print(
    "\nDo NOT assign coordinates or calculate final ET0 yet."
)

====================================================================================================
CELL 45 — code
Matched keywords: ['power.larc.nasa.gov', 'https://power', 'requests.get', 'requests.request', 'NASA POWER', 'POWER API', 'api/temporal', 'parameters=', 'latitude=', 'longitude=']
----------------------------------------------------------------------------------------------------
# STEP 5H — FIND EXACT NASA POWER / WEATHER DOWNLOAD CODE

from pathlib import Path
import json

PROJECT_ROOT = Path(
    r"C:\Users\bhavy\OneDrive\Pictures\Desktop\AgriHydro"
)

NOTEBOOK = (
    PROJECT_ROOT
    / "notebooks"
    / "01_dataset_analysis.ipynb"
)

with open(NOTEBOOK, "r", encoding="utf-8") as f:
    notebook = json.load(f)

print("=" * 100)
print("JALACHAKRA — EXACT WEATHER API / DOWNLOAD CODE")
print("=" * 100)

strong_keywords = [
    "power.larc.nasa.gov",
    "https://power",
    "requests.get",
    "requests.request",
    "NASA POWER",
    "POWER API",
    "api/temporal",
    "parameters=",
    "latitude=",
    "longitude="
]

found_cells = []

for cell_number, cell in enumerate(
    notebook.get("cells", []),
    start=1
):

    source = "".join(cell.get("source", []))

    if not source:
        continue

    matches = []

    for keyword in strong_keywords:
        if keyword.lower() in source.lower():
            matches.append(keyword)

    if matches:
        found_cells.append(
            (cell_number, cell.get("cell_type"), matches, source)
        )

print("\nMatching cells:", len(found_cells))

for cell_number, cell_type, matches, source in found_cells:

    print("\n" + "=" * 100)
    print(f"CELL {cell_number} — {cell_type}")
    print("Matched keywords:", matches)
    print("-" * 100)

    # Print the complete cell so URL/coordinates are visible
    print(source)

print("\n" + "=" * 100)
print("WHAT WE NEED")
print("=" * 100)

print("""
Look for:
1. power.larc.nasa.gov
2. latitude
3. longitude
4. start/end dates
5. parameters such as T2M, RH2M, WS2M, PRECTOTCORR
6. code that saves the response as Climate_Data.csv
""")

print("\nDo NOT calculate ET0 yet.")

====================================================================================================
WHAT WE NEED
====================================================================================================

Look for:
1. power.larc.nasa.gov
2. latitude
3. longitude
4. start/end dates
5. parameters such as T2M, RH2M, WS2M, PRECTOTCORR
6. code that saves the response as Climate_Data.csv


Do NOT calculate ET0 yet.